-- -- Projects table (can be under any entity)
-- CREATE TABLE projects (
--     id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
--     tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
--     entity_id UUID NOT NULL REFERENCES entities(uuid) ON DELETE CASCADE,
--     -- parent_project_id INT REFERENCES projects(id), -- Sub-projects
--     name VARCHAR(255) NOT NULL,
--     code VARCHAR(50),
--     description TEXT,
--     project_manager_id  UUID REFERENCES employees(id),
--     start_date DATE,
--     end_date DATE,
--     budget_amount DECIMAL(15,2),
--     actual_cost DECIMAL(15,2) DEFAULT 0,
--     status VARCHAR(20) DEFAULT 'PLANNING'
--         CHECK (status IN ('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED')),
--     metadata JSONB DEFAULT '{}'::jsonb,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );
-- CREATE UNIQUE INDEX tenant_code_entity_unique_idx
-- ON projects (tenant_id, entity_id, code)
-- WHERE code IS NOT NULL;
--
-- -- Budget management
-- CREATE TABLE budgets (
--     id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
--     tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
--     entity_id UUID NOT NULL REFERENCES entities(uuid) ON DELETE CASCADE,
--     project_id UUID REFERENCES projects(id), -- Optional project budget
--     name VARCHAR(255) NOT NULL,
--     budget_type VARCHAR(20) NOT NULL
--         CHECK (budget_type IN ('OPERATIONAL', 'CAPITAL', 'PROJECT', 'DEPARTMENT')),
--     fiscal_year INT NOT NULL,
--     period_start DATE NOT NULL,
--     period_end DATE NOT NULL,
--     total_amount DECIMAL(15,2) NOT NULL,
--     allocated_amount DECIMAL(15,2) DEFAULT 0,
--     spent_amount DECIMAL(15,2) DEFAULT 0,
--     status VARCHAR(20) DEFAULT 'DRAFT'
--         CHECK (status IN ('DRAFT', 'APPROVED', 'ACTIVE', 'CLOSED')),
--     approved_by UUID REFERENCES users(id),
--     approved_at TIMESTAMPTZ,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );
--
-- -- Multi-tenant Unit of Measure (UOM) table with conversion system
-- CREATE TABLE uom (
--     id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
--     tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
--     entity_id UUID NOT NULL REFERENCES entities(uuid) ON DELETE CASCADE,
--     uom_name VARCHAR(255) NOT NULL,
--     must_be_whole_number BOOLEAN DEFAULT FALSE,
--     enabled BOOLEAN DEFAULT TRUE,
--     symbol VARCHAR(50),
--     common_code VARCHAR(3),
--     description TEXT,
--     -- Conversion f qqields
--     base_uom_id UUID REFERENCES uom(id),
--     conversion_factor DECIMAL(15,6) DEFAULT 1.0,
--     uom_type VARCHAR(50), -- 'Weight', 'Length', 'Volume', 'Area', 'Time', 'Count'
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     -- Multi-tenant unique constraint
--     UNIQUE(tenant_id, entity_id, uom_name)
-- );
--
-- -- Multi-tenant UOM Conversion table for complex conversions
-- CREATE TABLE uom_conversion (
--     id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
--     tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
--     entity_id UUID NOT NULL REFERENCES entities(uuid) ON DELETE CASCADE,
--     from_uom_id UUID NOT NULL REFERENCES uom(id),
--     to_uom_id UUID NOT NULL REFERENCES uom(id),
--     conversion_factor DECIMAL(15,6) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     UNIQUE(tenant_id, entity_id, from_uom_id, to_uom_id)
-- );
--
-- -- Add comments to the tables
-- COMMENT ON TABLE uom IS 'Multi-tenant Unit of Measure definitions with conversion capabilities';
-- COMMENT ON TABLE uom_conversion IS 'Multi-tenant UOM conversion factors between different units';
--
-- -- Add comments to UOM columns
-- COMMENT ON COLUMN uom.id IS 'Primary key auto-increment identifier';
-- COMMENT ON COLUMN uom.tenant_id IS 'Tenant identifier for multi-tenancy';
-- COMMENT ON COLUMN uom.entity_id IS 'Entity identifier within tenant';
-- COMMENT ON COLUMN uom.uom_name IS 'Name of the unit of measure (unique per tenant/entity)';
-- COMMENT ON COLUMN uom.must_be_whole_number IS 'Check this to disallow fractions (for Nos)';
-- COMMENT ON COLUMN uom.enabled IS 'Whether this UOM is active and can be used';
-- COMMENT ON COLUMN uom.symbol IS 'Short symbol representation of the UOM (e.g., kg, m, pcs)';
-- COMMENT ON COLUMN uom.common_code IS 'Standard code according to CEFACT/ICG/2010/IC013 or CEFACT/ICG/2010/IC010';
-- COMMENT ON COLUMN uom.description IS 'Additional description or notes about the UOM';
-- COMMENT ON COLUMN uom.base_uom_id IS 'Reference to the base unit for this UOM group (NULL for base units)';
-- COMMENT ON COLUMN uom.conversion_factor IS 'Factor to convert from this UOM to base UOM (1.0 for base units)';
-- COMMENT ON COLUMN uom.uom_type IS 'Category of measurement (Weight, Length, Volume, etc.)';
--
-- -- Add comments to conversion columns
-- COMMENT ON COLUMN uom_conversion.tenant_id IS 'Tenant identifier for multi-tenancy';
-- COMMENT ON COLUMN uom_conversion.entity_id IS 'Entity identifier within tenant';
-- COMMENT ON COLUMN uom_conversion.from_uom_id IS 'Source UOM for conversion';
-- COMMENT ON COLUMN uom_conversion.to_uom_id IS 'Target UOM for conversion';
-- COMMENT ON COLUMN uom_conversion.conversion_factor IS 'Factor to multiply from_uom to get to_uom';
--
-- -- Create indexes for better performance
-- CREATE INDEX idx_uom_tenant_entity ON uom(tenant_id, entity_id);
-- CREATE INDEX idx_uom_enabled ON uom(enabled);
-- CREATE INDEX idx_uom_tenant_entity_type ON uom(tenant_id, entity_id, uom_type);
-- CREATE INDEX idx_uom_base_uom_id ON uom(base_uom_id);
-- CREATE INDEX idx_uom_conversion_tenant_entity ON uom_conversion(tenant_id, entity_id);
-- CREATE INDEX idx_uom_conversion_from ON uom_conversion(from_uom_id);
-- CREATE INDEX idx_uom_conversion_to ON uom_conversion(to_uom_id);
--
--
-- -- Project management policies
-- CREATE POLICY tenant_isolation_policy ON projects 
--     USING (tenant_id = current_tenant_id());
--
-- CREATE POLICY tenant_isolation_policy ON budgets 
--     USING (tenant_id = current_tenant_id());
--
--
-- CREATE TRIGGER update_project_timestamps 
--     BEFORE UPDATE ON projects 
--     FOR EACH ROW EXECUTE FUNCTION update_timestamps();

-- CREATE TRIGGER update_budget_timestamps 
--     BEFORE UPDATE ON budgets 
--     FOR EACH ROW EXECUTE FUNCTION update_timestamps();
--
--ENDS HAR3



-- -- Create trigger to automatically update the updated_at timestamp
-- CREATE OR REPLACE FUNCTION update_updated_at_column()
-- RETURNS TRIGGER AS $$
-- BEGIN
--     NEW.updated_at = CURRENT_TIMESTAMP;
--     RETURN NEW;
-- END;
-- $$ language 'plpgsql';

-- CREATE TRIGGER update_uom_updated_at 
--     BEFORE UPDATE ON uom 
--     FOR EACH ROW 
--     EXECUTE FUNCTION update_updated_at_column();

-- -- Function to get conversion factor between two UOMs (tenant-aware)
-- CREATE OR REPLACE FUNCTION get_conversion_factor(
--     p_tenant_id INTEGER,
--     p_entity_id INTEGER,
--     from_uom_id INTEGER, 
--     to_uom_id INTEGER
-- )
-- RETURNS DECIMAL(15,6) AS $$
-- DECLARE
--     factor DECIMAL(15,6);
--     from_base_factor DECIMAL(15,6);
--     to_base_factor DECIMAL(15,6);
--     from_base_id INTEGER;
--     to_base_id INTEGER;
-- BEGIN
--     -- If same UOM, return 1
--     IF from_uom_id = to_uom_id THEN
--         RETURN 1.0;
--     END IF;
--     
--     -- Check direct conversion first
--     SELECT conversion_factor INTO factor 
--     FROM uom_conversion 
--     WHERE tenant_id = p_tenant_id 
--       AND entity_id = p_entity_id
--       AND from_uom_id = get_conversion_factor.from_uom_id 
--       AND to_uom_id = get_conversion_factor.to_uom_id;
--     
--     IF FOUND THEN
--         RETURN factor;
--     END IF;
--     
--     -- Try indirect conversion through base units
--     SELECT COALESCE(base_uom_id, id), conversion_factor 
--     INTO from_base_id, from_base_factor
--     FROM uom 
--     WHERE id = from_uom_id 
--       AND tenant_id = p_tenant_id 
--       AND entity_id = p_entity_id;
--     
--     SELECT COALESCE(base_uom_id, id), conversion_factor 
--     INTO to_base_id, to_base_factor
--     FROM uom 
--     WHERE id = to_uom_id 
--       AND tenant_id = p_tenant_id 
--       AND entity_id = p_entity_id;
--     
--     -- If both have same base unit, calculate conversion
--     IF from_base_id = to_base_id THEN
--         RETURN from_base_factor / to_base_factor;
--     END IF;
--     
--     -- No conversion found
--     RETURN NULL;
-- END;
-- $$ LANGUAGE plpgsql;

-- -- Function to convert quantity between UOMs (tenant-aware)
-- CREATE OR REPLACE FUNCTION convert_quantity(
--     p_tenant_id INTEGER,
--     p_entity_id INTEGER,
--     quantity DECIMAL(15,6), 
--     from_uom_id INTEGER, 
--     to_uom_id INTEGER
-- ) RETURNS DECIMAL(15,6) AS $$
-- DECLARE
--     factor DECIMAL(15,6);
-- BEGIN
--     factor := get_conversion_factor(p_tenant_id, p_entity_id, from_uom_id, to_uom_id);
--     
--     IF factor IS NULL THEN
--         RAISE EXCEPTION 'No conversion available between UOM % and % for tenant % entity %', 
--             from_uom_id, to_uom_id, p_tenant_id, p_entity_id;
--     END IF;
--     
--     RETURN quantity * factor;
-- END;
-- $$ LANGUAGE plpgsql;

-- -- Function to get conversion factor using UOM names (tenant-aware)
-- CREATE OR REPLACE FUNCTION get_conversion_by_name(
--     p_tenant_id INTEGER,
--     p_entity_id INTEGER,
--     from_uom_name VARCHAR, 
--     to_uom_name VARCHAR
-- )
-- RETURNS DECIMAL(15,6) AS $$
-- DECLARE
--     from_id INTEGER;
--     to_id INTEGER;
-- BEGIN
--     SELECT id INTO from_id 
--     FROM uom 
--     WHERE uom_name = from_uom_name 
--       AND tenant_id = p_tenant_id 
--       AND entity_id = p_entity_id;
--       
--     SELECT id INTO to_id 
--     FROM uom 
--     WHERE uom_name = to_uom_name 
--       AND tenant_id = p_tenant_id 
--       AND entity_id = p_entity_id;
--     
--     IF from_id IS NULL THEN
--         RAISE EXCEPTION 'UOM "%" not found for tenant % entity %', from_uom_name, p_tenant_id, p_entity_id;
--     END IF;
--     
--     IF to_id IS NULL THEN
--         RAISE EXCEPTION 'UOM "%" not found for tenant % entity %', to_uom_name, p_tenant_id, p_entity_id;
--     END IF;
--     
--     RETURN get_conversion_factor(p_tenant_id, p_entity_id, from_id, to_id);
-- END;
-- $$ LANGUAGE plpgsql;

-- -- Function to check if conversion is possible (tenant-aware)
-- CREATE OR REPLACE FUNCTION can_convert(
--     p_tenant_id INTEGER,
--     p_entity_id INTEGER,
--     from_uom_name VARCHAR, 
--     to_uom_name VARCHAR
-- )
-- RETURNS BOOLEAN AS $$
-- BEGIN
--     RETURN get_conversion_by_name(p_tenant_id, p_entity_id, from_uom_name, to_uom_name) IS NOT NULL;
-- EXCEPTION
--     WHEN OTHERS THEN
--         RETURN FALSE;
-- END;
-- $$ LANGUAGE plpgsql;

-- -- Multi-tenant conversion lookup view
-- CREATE OR REPLACE VIEW uom_conversion_lookup AS
-- SELECT 
--     from_uom.tenant_id,
--     from_uom.entity_id,
--     from_uom.id as from_uom_id,
--     from_uom.uom_name as from_uom_name,
--     from_uom.symbol as from_symbol,
--     to_uom.id as to_uom_id,
--     to_uom.uom_name as to_uom_name,
--     to_uom.symbol as to_symbol,
--     get_conversion_factor(from_uom.tenant_id, from_uom.entity_id, from_uom.id, to_uom.id) as conversion_factor
-- FROM uom from_uom
-- JOIN uom to_uom ON from_uom.tenant_id = to_uom.tenant_id 
--                 AND from_uom.entity_id = to_uom.entity_id
-- WHERE from_uom.enabled = TRUE 
--   AND to_uom.enabled = TRUE
--   AND get_conversion_factor(from_uom.tenant_id, from_uom.entity_id, from_uom.id, to_uom.id) IS NOT NULL;

-- -- Insert sample data for tenant_id = 1, entity_id = 1
-- -- Weight units (base unit: gram)
-- INSERT INTO uom (tenant_id, entity_id, uom_name, symbol, common_code, uom_type, base_uom_id, conversion_factor, description) VALUES
-- (1, 1, 'Gram', 'g', 'GRM', 'Weight', NULL, 1.0, 'Base unit of weight - 1 gram'),
-- (1, 1, 'Kilogram', 'kg', 'KGM', 'Weight', 1, 1000.0, 'Unit of mass - 1000 grams'),
-- (1, 1, 'Ton', 't', 'TNE', 'Weight', 1, 1000000.0, 'Metric ton - 1,000,000 grams'),
-- (1, 1, 'Pound', 'lb', 'LBR', 'Weight', 1, 453.592, 'Imperial pound - 453.592 grams'),
-- (1, 1, 'Ounce', 'oz', 'ONZ', 'Weight', 1, 28.3495, 'Imperial ounce - 28.3495 grams');

-- -- Length units (base unit: meter)
-- INSERT INTO uom (tenant_id, entity_id, uom_name, symbol, common_code, uom_type, base_uom_id, conversion_factor, description) VALUES
-- (1, 1, 'Meter', 'm', 'MTR', 'Length', NULL, 1.0, 'Base unit of length - 1 meter'),
-- (1, 1, 'Centimeter', 'cm', 'CMT', 'Length', 6, 0.01, 'Unit of length - 0.01 meters'),
-- (1, 1, 'Millimeter', 'mm', 'MMT', 'Length', 6, 0.001, 'Unit of length - 0.001 meters'),
-- (1, 1, 'Kilometer', 'km', 'KTM', 'Length', 6, 1000.0, 'Unit of length - 1000 meters'),
-- (1, 1, 'Inch', 'in', 'INH', 'Length', 6, 0.0254, 'Imperial inch - 0.0254 meters'),
-- (1, 1, 'Foot', 'ft', 'FOT', 'Length', 6, 0.3048, 'Imperial foot - 0.3048 meters');

-- -- Volume units (base unit: liter)
-- INSERT INTO uom (tenant_id, entity_id, uom_name, symbol, common_code, uom_type, base_uom_id, conversion_factor, description) VALUES
-- (1, 1, 'Liter', 'L', 'LTR', 'Volume', NULL, 1.0, 'Base unit of volume - 1 liter'),
-- (1, 1, 'Milliliter', 'ml', 'MLT', 'Volume', 12, 0.001, 'Unit of volume - 0.001 liters'),
-- (1, 1, 'Gallon', 'gal', 'GLL', 'Volume', 12, 3.78541, 'US gallon - 3.78541 liters');

-- -- Count units
-- INSERT INTO uom (tenant_id, entity_id, uom_name, symbol, common_code, uom_type, must_be_whole_number, description) VALUES
-- (1, 1, 'Piece', 'pcs', 'PCE', 'Count', TRUE, 'Individual countable items'),
-- (1, 1, 'Dozen', 'doz', 'DZN', 'Count', TRUE, 'Set of 12 pieces'),
-- (1, 1, 'Gross', 'gr', 'GRO', 'Count', TRUE, 'Set of 144 pieces (12 dozen)');

-- -- Add conversions for count units
-- INSERT INTO uom_conversion (tenant_id, entity_id, from_uom_id, to_uom_id, conversion_factor) VALUES
-- (1, 1, 15, 16, 12.0),   -- Piece to Dozen
-- (1, 1, 16, 15, 0.0833), -- Dozen to Piece  
-- (1, 1, 16, 17, 12.0),   -- Dozen to Gross
-- (1, 1, 17, 16, 0.0833), -- Gross to Dozen
-- (1, 1, 15, 17, 144.0),  -- Piece to Gross
-- (1, 1, 17, 15, 0.0069); -- Gross to Piece

-- -- Time units (base unit: minute)
-- INSERT INTO uom (tenant_id, entity_id, uom_name, symbol, common_code, uom_type, base_uom_id, conversion_factor, description) VALUES
-- (1, 1, 'Minute', 'min', 'MIN', 'Time', NULL, 1.0, 'Base unit of time - 1 minute'),
-- (1, 1, 'Hour', 'hr', 'HUR', 'Time', 18, 60.0, 'Unit of time - 60 minutes'),
-- (1, 1, 'Day', 'day', 'DAY', 'Time', 18, 1440.0, 'Unit of time - 1440 minutes'),
-- (1, 1, 'Second', 'sec', 'SEC', 'Time', 18, 0.0167, 'Unit of time - 0.0167 minutes');

-- -- Example usage with tenant/entity context:

-- -- Convert 5 kg to grams for tenant 1, entity 1
-- -- SELECT convert_quantity(1, 1, 5, 2, 1) as result; -- Should return 5000

-- -- Get conversion factor from kg to gram for tenant 1, entity 1
-- -- SELECT get_conversion_by_name(1, 1, 'Kilogram', 'Gram') as factor; -- Should return 1000

-- -- Check if conversion is possible for tenant 1, entity 1
-- -- SELECT can_convert(1, 1, 'Kilogram', 'Gram') as possible; -- Should return TRUE

-- -- Get all conversions for tenant 1, entity 1
-- -- SELECT * FROM uom_conversion_lookup WHERE tenant_id = 1 AND entity_id = 1;

-- -- Query to show weight conversions for specific tenant/entity
-- -- SELECT 
-- --     u.uom_name,
-- --     u.symbol,
-- --     u.conversion_factor,
-- --     CASE 
-- --         WHEN u.conversion_factor = 1.0 THEN '1 gram = 1 gram'
-- --         WHEN u.conversion_factor > 1.0 THEN '1 ' || u.uom_name || ' = ' || u.conversion_factor || ' grams'
-- --         ELSE '1 gram = ' || ROUND(1.0/u.conversion_factor, 6) || ' ' || u.uom_name
-- --     END as conversion_description
-- -- FROM uom u
-- -- WHERE u.tenant_id = 1 
-- --   AND u.entity_id = 1
-- --   AND u.uom_type = 'Weight' 
-- --   AND u.enabled = TRUE
-- -- ORDER BY u.conversion_factor;


-- --_____________________________________________
-- -- Currency and Exchange
-- --_____________________________________________

-- -- Currency Table (Master data for currencies)
-- CREATE TABLE currency (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(255) UNIQUE NOT NULL,
--     
--     -- Multi-tenancy fields
--     tenant_id INT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
--     entity_id INT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
--     
--     -- Core currency fields
--     currency_code VARCHAR(3) NOT NULL, -- ISO 4217 currency code (USD, EUR, etc.)
--     currency_name VARCHAR(100) NOT NULL, -- Full name (US Dollar, Euro, etc.)
--     currency_symbol VARCHAR(10), -- Symbol ($, €, £, etc.)
--     fraction VARCHAR(50) DEFAULT 'Cent', -- Fraction unit name
--     fraction_units SMALLINT DEFAULT 100, -- Number of fraction units (100 cents = 1 dollar)
--     
--     -- Display settings
--     -- number_format VARCHAR(50) DEFAULT '#,###.##',
--     smallest_currency_fraction_value DECIMAL(10,6) DEFAULT 0.01,
--     
--     -- Status
--     enabled BOOLEAN NOT NULL DEFAULT TRUE,
--     
--     -- System fields
--     docstatus SMALLINT NOT NULL DEFAULT 0, -- 0=Draft, 1=Submitted, 2=Cancelled
--     creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     
--     -- Constraints
--     CONSTRAINT chk_currency_code_format CHECK (currency_code ~ '^[A-Z]{3}$'),
--     CONSTRAINT chk_fraction_units_positive CHECK (fraction_units > 0),
--     CONSTRAINT chk_docstatus_currency CHECK (docstatus IN (0, 1, 2)),
--     
--     -- Unique constraint for currency code within tenant/entity
--     CONSTRAINT uk_currency_code_tenant_entity UNIQUE (tenant_id, entity_id, currency_code)
-- );

-- -- Indexes for currency table
-- CREATE INDEX idx_currency_tenant_entity ON currency(tenant_id, entity_id);
-- CREATE INDEX idx_currency_code ON currency(currency_code);
-- CREATE INDEX idx_currency_enabled ON currency(enabled) WHERE enabled = TRUE;

-- -- Trigger to update currency modified timestamp
-- CREATE OR REPLACE FUNCTION update_currency_modified()
-- RETURNS TRIGGER AS $$
-- BEGIN
--     NEW.modified = CURRENT_TIMESTAMP;
--     RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;

-- CREATE TRIGGER tr_currency_modified
--     BEFORE UPDATE ON currency
--     FOR EACH ROW
--     EXECUTE FUNCTION update_currency_modified();

-- -- Sample currency data (commonly used currencies)
-- INSERT INTO currency (tenant_id, entity_id, name, currency_code, currency_name, currency_symbol, fraction, fraction_units, number_format) 
-- VALUES 
--     (1, 1, 'USD', 'USD', 'US Dollar', '$', 'Cent', 100, '#,###.##'),
--     (1, 1, 'EUR', 'EUR', 'Euro', '€', 'Cent', 100, '#,###.##'),
--     (1, 1, 'GBP', 'GBP', 'Pound Sterling', '£', 'Penny', 100, '#,###.##'),
--     (1, 1, 'JPY', 'JPY', 'Japanese Yen', '¥', 'Sen', 100, '#,###'),
--     (1, 1, 'CAD', 'CAD', 'Canadian Dollar', 'C$', 'Cent', 100, '#,###.##'),
--     (1, 1, 'AUD', 'AUD', 'Australian Dollar', 'A$', 'Cent', 100, '#,###.##'),
--     (1, 1, 'CHF', 'CHF', 'Swiss Franc', 'CHF', 'Rappen', 100, '#,###.##'),
--     (1, 1, 'CNY', 'CNY', 'Chinese Yuan', '¥', 'Jiao', 10, '#,###.##'),
--     (1, 1, 'INR', 'INR', 'Indian Rupee', '₹', 'Paisa', 100, '#,###.##'),
--     (1, 1, 'KES', 'KES', 'Kenyan Shilling', 'KSh', 'Cent', 100, '#,###.##');

-- -- Comments for currency table
-- COMMENT ON TABLE currency IS 'Master data for currencies with multi-tenant support';
-- COMMENT ON COLUMN currency.tenant_id IS 'Reference to tenant for multi-tenancy';
-- COMMENT ON COLUMN currency.entity_id IS 'Reference to entity within tenant';
-- COMMENT ON COLUMN currency.currency_code IS 'ISO 4217 three-letter currency code';
-- COMMENT ON COLUMN currency.currency_name IS 'Full descriptive name of the currency';
-- COMMENT ON COLUMN currency.currency_symbol IS 'Symbol used to represent the currency';
-- COMMENT ON COLUMN currency.fraction IS 'Name of the fractional unit (cent, penny, etc.)';
-- COMMENT ON COLUMN currency.fraction_units IS 'Number of fractional units in one major unit';
-- COMMENT ON COLUMN currency.number_format IS 'Format string for displaying currency amounts';
-- -- COMMENT ON COLUMN currency.smallest_currency_fraction_value IS 'Smallest tradeable fraction of the currency';

-- -- Currency Exchange Table
-- CREATE TABLE currency_exchange (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(255) UNIQUE NOT NULL,
--     
--     -- Multi-tenancy fields
--     tenant_id INT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
--     entity_id INT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
--     
--     -- Core exchange rate fields
--     date DATE NOT NULL,
--     from_currency VARCHAR(3) NOT NULL REFERENCES currency(currency_code) ON DELETE RESTRICT,
--     to_currency VARCHAR(3) NOT NULL REFERENCES currency(currency_code) ON DELETE RESTRICT,
--     exchange_rate DECIMAL(15,9) NOT NULL, -- High precision for exchange rates
--     
--     -- Usage flags
--     for_buying BOOLEAN NOT NULL DEFAULT TRUE,
--     for_selling BOOLEAN NOT NULL DEFAULT TRUE,
--     
--     -- System fields
--     docstatus SMALLINT NOT NULL DEFAULT 0, -- 0=Draft, 1=Submitted, 2=Cancelled
--     creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     -- modified_by VARCHAR(255) NOT NULL DEFAULT 'Administrator',
--     -- owner VARCHAR(255) NOT NULL DEFAULT 'Administrator',
--     
--     -- Constraints
--     CONSTRAINT chk_exchange_rate_positive CHECK (exchange_rate > 0),
--     CONSTRAINT chk_different_currencies CHECK (from_currency != to_currency),
--     CONSTRAINT chk_docstatus CHECK (docstatus IN (0, 1, 2)),
--     
--     -- Unique constraint to prevent duplicate rates for same date and currency pair
--     CONSTRAINT uk_currency_exchange_date_currencies UNIQUE (tenant_id, entity_id, date, from_currency, to_currency, for_buying, for_selling)
-- );

-- -- Indexes for better performance
-- CREATE INDEX idx_currency_exchange_tenant_entity ON currency_exchange(tenant_id, entity_id);
-- CREATE INDEX idx_currency_exchange_date ON currency_exchange(date DESC);
-- CREATE INDEX idx_currency_exchange_from_currency ON currency_exchange(from_currency);
-- CREATE INDEX idx_currency_exchange_to_currency ON currency_exchange(to_currency);
-- CREATE INDEX idx_currency_exchange_lookup ON currency_exchange(tenant_id, entity_id, from_currency, to_currency, date DESC);

-- -- Trigger to update modified timestamp
-- CREATE OR REPLACE FUNCTION update_currency_exchange_modified()
-- RETURNS TRIGGER AS $$
-- BEGIN
--     NEW.modified = CURRENT_TIMESTAMP;
--     RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;

-- CREATE TRIGGER tr_currency_exchange_modified
--     BEFORE UPDATE ON currency_exchange
--     FOR EACH ROW
--     EXECUTE FUNCTION update_currency_exchange_modified();

-- -- Comments for documentation
-- COMMENT ON TABLE currency_exchange IS 'Exchange rates for currency conversion with multi-tenant support';
-- COMMENT ON COLUMN currency_exchange.tenant_id IS 'Reference to tenant for multi-tenancy';
-- COMMENT ON COLUMN currency_exchange.entity_id IS 'Reference to entity within tenant';
-- COMMENT ON COLUMN currency_exchange.date IS 'Date when the exchange rate is applicable';
-- COMMENT ON COLUMN currency_exchange.from_currency IS 'Source currency code (3-letter ISO)';
-- COMMENT ON COLUMN currency_exchange.to_currency IS 'Target currency code (3-letter ISO)';
-- COMMENT ON COLUMN currency_exchange.exchange_rate IS 'Rate to convert from source to target currency';
-- COMMENT ON COLUMN currency_exchange.for_buying IS 'Whether this rate applies to buying transactions';
-- COMMENT ON COLUMN currency_exchange.for_selling IS 'Whether this rate applies to selling transactions';
-- COMMENT ON COLUMN currency_exchange.docstatus IS 'Document status: 0=Draft, 1=Submitted, 2=Cancelled';
