-- =============================================================================
-- V2.0 RESERVED — ABAC migration. DO NOT DROP. Not active in v1.0.
-- internal/core/access/ is gated with //go:build ignore until v2.0.
-- =============================================================================

-- ------------------------------------------------------------------------------------------------
-- USER ENTITY ACCESS
-- ------------------------------------------------------------------------------------------------
-- Entity-scoped access for users is handled via the entity_id column in the user_roles table.
-- No additional table is needed; this migration is intentionally a no-op placeholder.
--
-- NOTE: See 000064_platform_iam.up.sql for the user_roles table definition and
--       000412_user_roles_functions.up.sql for the FK and helper functions.
-- ------------------------------------------------------------------------------------------------
