// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (
    tenant_id,
    name,
    key_hash,
    scopes,
    expires_at,
    created_by
) VALUES (
    current_tenant_id(),
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, tenant_id, name, key_hash, scopes, created_by, expires_at, revoked_at, last_used_at, created_at
`

type CreateAPIKeyParams struct {
	Name      string       `json:"name"`
	KeyHash   string       `json:"key_hash"`
	Scopes    []string     `json:"scopes"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedBy uuid.UUID    `json:"created_by"`
}

// API key management queries.
// Run `make sqlc` after modifying this file.
//
// GetAPIKeyByHash intentionally omits key_hash from the SELECT list (no need
// to return the hash to Go code) and runs WITHOUT tenant context — the
// key_hash column is globally unique and the lookup must work cross-tenant
// during the authentication middleware.  This query MUST be executed by
// admin_role (or a BYPASSRLS role) at the DB layer.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (*ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.KeyHash,
		arg.Scopes,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyHash,
		&i.Scopes,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT
    id,
    tenant_id,
    name,
    scopes,
    created_by,
    expires_at,
    revoked_at,
    last_used_at,
    created_at
FROM api_keys
WHERE  key_hash   = $1
  AND  revoked_at IS NULL
  AND  (expires_at IS NULL OR expires_at > NOW())
`

type GetAPIKeyByHashRow struct {
	ID         uuid.UUID    `json:"id"`
	TenantID   uuid.UUID    `json:"tenant_id"`
	Name       string       `json:"name"`
	Scopes     []string     `json:"scopes"`
	CreatedBy  uuid.UUID    `json:"created_by"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

// Called on every API-key-authenticated request. Returns nil if revoked or expired.
// NOTE: runs without tenant context (admin_role required); key_hash is globally unique.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (*GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Scopes,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT
    id,
    tenant_id,
    name,
    scopes,
    created_by,
    expires_at,
    revoked_at,
    last_used_at,
    created_at
FROM api_keys
WHERE  tenant_id = current_tenant_id()
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID         uuid.UUID    `json:"id"`
	TenantID   uuid.UUID    `json:"tenant_id"`
	Name       string       `json:"name"`
	Scopes     []string     `json:"scopes"`
	CreatedBy  uuid.UUID    `json:"created_by"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]*ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Scopes,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys
SET    revoked_at = NOW()
WHERE  tenant_id  = current_tenant_id()
  AND  id         = $1
  AND  revoked_at IS NULL
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}
