// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: employee.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one

INSERT INTO employees (
    tenant_id, person_id, employee_number, entity_id, position_title,
    department_id, manager_id, hire_date, termination_date, salary_info,
    employment_status, work_schedule
) VALUES (
    current_tenant_id(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, person_id, employee_number, entity_id, position_title, department_id, manager_id, hire_date, termination_date, salary_info, employment_status, work_schedule, created_at, updated_at
`

type CreateEmployeeParams struct {
	PersonID         int32       `json:"person_id"`
	EmployeeNumber   string      `json:"employee_number"`
	EntityID         uuid.UUID   `json:"entity_id"`
	PositionTitle    pgtype.Text `json:"position_title"`
	DepartmentID     pgtype.UUID `json:"department_id"`
	ManagerID        pgtype.Int4 `json:"manager_id"`
	HireDate         pgtype.Date `json:"hire_date"`
	TerminationDate  pgtype.Date `json:"termination_date"`
	SalaryInfo       []byte      `json:"salary_info"`
	EmploymentStatus pgtype.Text `json:"employment_status"`
	WorkSchedule     []byte      `json:"work_schedule"`
}

// ==============================================
// EMPLOYEES TABLE OPERATIONS
// ==============================================
func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.PersonID,
		arg.EmployeeNumber,
		arg.EntityID,
		arg.PositionTitle,
		arg.DepartmentID,
		arg.ManagerID,
		arg.HireDate,
		arg.TerminationDate,
		arg.SalaryInfo,
		arg.EmploymentStatus,
		arg.WorkSchedule,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PersonID,
		&i.EmployeeNumber,
		&i.EntityID,
		&i.PositionTitle,
		&i.DepartmentID,
		&i.ManagerID,
		&i.HireDate,
		&i.TerminationDate,
		&i.SalaryInfo,
		&i.EmploymentStatus,
		&i.WorkSchedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, tenant_id, person_id, employee_number, entity_id, position_title, department_id, manager_id, hire_date, termination_date, salary_info, employment_status, work_schedule, created_at, updated_at FROM employees 
WHERE id = $1 AND tenant_id = current_tenant_id()
`

func (q *Queries) GetEmployee(ctx context.Context, id int32) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PersonID,
		&i.EmployeeNumber,
		&i.EntityID,
		&i.PositionTitle,
		&i.DepartmentID,
		&i.ManagerID,
		&i.HireDate,
		&i.TerminationDate,
		&i.SalaryInfo,
		&i.EmploymentStatus,
		&i.WorkSchedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByNumber = `-- name: GetEmployeeByNumber :one
SELECT id, tenant_id, person_id, employee_number, entity_id, position_title, department_id, manager_id, hire_date, termination_date, salary_info, employment_status, work_schedule, created_at, updated_at FROM employees 
WHERE employee_number = $1 AND tenant_id = current_tenant_id()
`

func (q *Queries) GetEmployeeByNumber(ctx context.Context, employeeNumber string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByNumber, employeeNumber)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PersonID,
		&i.EmployeeNumber,
		&i.EntityID,
		&i.PositionTitle,
		&i.DepartmentID,
		&i.ManagerID,
		&i.HireDate,
		&i.TerminationDate,
		&i.SalaryInfo,
		&i.EmploymentStatus,
		&i.WorkSchedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByPersonId = `-- name: GetEmployeeByPersonId :one
SELECT id, tenant_id, person_id, employee_number, entity_id, position_title, department_id, manager_id, hire_date, termination_date, salary_info, employment_status, work_schedule, created_at, updated_at FROM employees 
WHERE person_id = $1 AND tenant_id = current_tenant_id()
`

func (q *Queries) GetEmployeeByPersonId(ctx context.Context, personID int32) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByPersonId, personID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PersonID,
		&i.EmployeeNumber,
		&i.EntityID,
		&i.PositionTitle,
		&i.DepartmentID,
		&i.ManagerID,
		&i.HireDate,
		&i.TerminationDate,
		&i.SalaryInfo,
		&i.EmploymentStatus,
		&i.WorkSchedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeHierarchy = `-- name: GetEmployeeHierarchy :many
WITH RECURSIVE employee_hierarchy AS (
    SELECT 
        e.id, e.person_id, e.employee_number, e.position_title, e.manager_id,
        p.first_name, p.last_name, 0 as level
    FROM employees e
    JOIN persons p ON e.person_id = p.id
    WHERE e.id = $1 AND e.tenant_id = current_tenant_id()
    
    UNION ALL
    
    SELECT 
        e.id, e.person_id, e.employee_number, e.position_title, e.manager_id,
        p.first_name, p.last_name, eh.level + 1
    FROM employees e
    JOIN persons p ON e.person_id = p.id
    JOIN employee_hierarchy eh ON e.manager_id = eh.id
    WHERE e.tenant_id = current_tenant_id() AND eh.level < 10
)
SELECT id, person_id, employee_number, position_title, manager_id, first_name, last_name, level FROM employee_hierarchy
ORDER BY level, last_name, first_name
`

type GetEmployeeHierarchyRow struct {
	ID             int32       `json:"id"`
	PersonID       int32       `json:"person_id"`
	EmployeeNumber string      `json:"employee_number"`
	PositionTitle  pgtype.Text `json:"position_title"`
	ManagerID      pgtype.Int4 `json:"manager_id"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	Level          int32       `json:"level"`
}

func (q *Queries) GetEmployeeHierarchy(ctx context.Context, id int32) ([]GetEmployeeHierarchyRow, error) {
	rows, err := q.db.Query(ctx, getEmployeeHierarchy, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEmployeeHierarchyRow{}
	for rows.Next() {
		var i GetEmployeeHierarchyRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.EmployeeNumber,
			&i.PositionTitle,
			&i.ManagerID,
			&i.FirstName,
			&i.LastName,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeStats = `-- name: GetEmployeeStats :one
SELECT 
    COUNT(*) as total_employees,
    COUNT(*) FILTER (WHERE employment_status = 'ACTIVE') as active_employees,
    COUNT(*) FILTER (WHERE employment_status = 'TERMINATED') as terminated_employees,
    COUNT(*) FILTER (WHERE employment_status = 'ON_LEAVE') as on_leave_employees,
    COUNT(DISTINCT department_id) as departments_count,
    COUNT(*) FILTER (WHERE manager_id IS NULL) as managers_count
FROM employees
WHERE tenant_id = current_tenant_id()
`

type GetEmployeeStatsRow struct {
	TotalEmployees      int64 `json:"total_employees"`
	ActiveEmployees     int64 `json:"active_employees"`
	TerminatedEmployees int64 `json:"terminated_employees"`
	OnLeaveEmployees    int64 `json:"on_leave_employees"`
	DepartmentsCount    int64 `json:"departments_count"`
	ManagersCount       int64 `json:"managers_count"`
}

func (q *Queries) GetEmployeeStats(ctx context.Context) (GetEmployeeStatsRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeStats)
	var i GetEmployeeStatsRow
	err := row.Scan(
		&i.TotalEmployees,
		&i.ActiveEmployees,
		&i.TerminatedEmployees,
		&i.OnLeaveEmployees,
		&i.DepartmentsCount,
		&i.ManagersCount,
	)
	return i, err
}

const listActiveEmployees = `-- name: ListActiveEmployees :many
SELECT e.id, e.tenant_id, e.person_id, e.employee_number, e.entity_id, e.position_title, e.department_id, e.manager_id, e.hire_date, e.termination_date, e.salary_info, e.employment_status, e.work_schedule, e.created_at, e.updated_at, p.first_name, p.last_name, p.email, p.phone
FROM employees e
JOIN persons p ON e.person_id = p.id
WHERE e.tenant_id = current_tenant_id() AND e.employment_status = 'ACTIVE'
ORDER BY p.last_name, p.first_name
`

type ListActiveEmployeesRow struct {
	ID               int32              `json:"id"`
	TenantID         int32              `json:"tenant_id"`
	PersonID         int32              `json:"person_id"`
	EmployeeNumber   string             `json:"employee_number"`
	EntityID         uuid.UUID          `json:"entity_id"`
	PositionTitle    pgtype.Text        `json:"position_title"`
	DepartmentID     pgtype.UUID        `json:"department_id"`
	ManagerID        pgtype.Int4        `json:"manager_id"`
	HireDate         pgtype.Date        `json:"hire_date"`
	TerminationDate  pgtype.Date        `json:"termination_date"`
	SalaryInfo       []byte             `json:"salary_info"`
	EmploymentStatus pgtype.Text        `json:"employment_status"`
	WorkSchedule     []byte             `json:"work_schedule"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            pgtype.Text        `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
}

func (q *Queries) ListActiveEmployees(ctx context.Context) ([]ListActiveEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listActiveEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveEmployeesRow{}
	for rows.Next() {
		var i ListActiveEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PersonID,
			&i.EmployeeNumber,
			&i.EntityID,
			&i.PositionTitle,
			&i.DepartmentID,
			&i.ManagerID,
			&i.HireDate,
			&i.TerminationDate,
			&i.SalaryInfo,
			&i.EmploymentStatus,
			&i.WorkSchedule,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT e.id, e.tenant_id, e.person_id, e.employee_number, e.entity_id, e.position_title, e.department_id, e.manager_id, e.hire_date, e.termination_date, e.salary_info, e.employment_status, e.work_schedule, e.created_at, e.updated_at, p.first_name, p.last_name, p.email, p.phone
FROM employees e
JOIN persons p ON e.person_id = p.id
WHERE e.tenant_id = current_tenant_id()
ORDER BY p.last_name, p.first_name
`

type ListEmployeesRow struct {
	ID               int32              `json:"id"`
	TenantID         int32              `json:"tenant_id"`
	PersonID         int32              `json:"person_id"`
	EmployeeNumber   string             `json:"employee_number"`
	EntityID         uuid.UUID          `json:"entity_id"`
	PositionTitle    pgtype.Text        `json:"position_title"`
	DepartmentID     pgtype.UUID        `json:"department_id"`
	ManagerID        pgtype.Int4        `json:"manager_id"`
	HireDate         pgtype.Date        `json:"hire_date"`
	TerminationDate  pgtype.Date        `json:"termination_date"`
	SalaryInfo       []byte             `json:"salary_info"`
	EmploymentStatus pgtype.Text        `json:"employment_status"`
	WorkSchedule     []byte             `json:"work_schedule"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            pgtype.Text        `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
}

func (q *Queries) ListEmployees(ctx context.Context) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesRow{}
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PersonID,
			&i.EmployeeNumber,
			&i.EntityID,
			&i.PositionTitle,
			&i.DepartmentID,
			&i.ManagerID,
			&i.HireDate,
			&i.TerminationDate,
			&i.SalaryInfo,
			&i.EmploymentStatus,
			&i.WorkSchedule,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByDepartment = `-- name: ListEmployeesByDepartment :many
SELECT e.id, e.tenant_id, e.person_id, e.employee_number, e.entity_id, e.position_title, e.department_id, e.manager_id, e.hire_date, e.termination_date, e.salary_info, e.employment_status, e.work_schedule, e.created_at, e.updated_at, p.first_name, p.last_name, p.email, p.phone
FROM employees e
JOIN persons p ON e.person_id = p.id
WHERE e.tenant_id = current_tenant_id() AND e.department_id = $1
ORDER BY p.last_name, p.first_name
`

type ListEmployeesByDepartmentRow struct {
	ID               int32              `json:"id"`
	TenantID         int32              `json:"tenant_id"`
	PersonID         int32              `json:"person_id"`
	EmployeeNumber   string             `json:"employee_number"`
	EntityID         uuid.UUID          `json:"entity_id"`
	PositionTitle    pgtype.Text        `json:"position_title"`
	DepartmentID     pgtype.UUID        `json:"department_id"`
	ManagerID        pgtype.Int4        `json:"manager_id"`
	HireDate         pgtype.Date        `json:"hire_date"`
	TerminationDate  pgtype.Date        `json:"termination_date"`
	SalaryInfo       []byte             `json:"salary_info"`
	EmploymentStatus pgtype.Text        `json:"employment_status"`
	WorkSchedule     []byte             `json:"work_schedule"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            pgtype.Text        `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
}

func (q *Queries) ListEmployeesByDepartment(ctx context.Context, departmentID pgtype.UUID) ([]ListEmployeesByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesByDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesByDepartmentRow{}
	for rows.Next() {
		var i ListEmployeesByDepartmentRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PersonID,
			&i.EmployeeNumber,
			&i.EntityID,
			&i.PositionTitle,
			&i.DepartmentID,
			&i.ManagerID,
			&i.HireDate,
			&i.TerminationDate,
			&i.SalaryInfo,
			&i.EmploymentStatus,
			&i.WorkSchedule,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByManager = `-- name: ListEmployeesByManager :many
SELECT e.id, e.tenant_id, e.person_id, e.employee_number, e.entity_id, e.position_title, e.department_id, e.manager_id, e.hire_date, e.termination_date, e.salary_info, e.employment_status, e.work_schedule, e.created_at, e.updated_at, p.first_name, p.last_name, p.email, p.phone
FROM employees e
JOIN persons p ON e.person_id = p.id
WHERE e.tenant_id = current_tenant_id() AND e.manager_id = $1
ORDER BY p.last_name, p.first_name
`

type ListEmployeesByManagerRow struct {
	ID               int32              `json:"id"`
	TenantID         int32              `json:"tenant_id"`
	PersonID         int32              `json:"person_id"`
	EmployeeNumber   string             `json:"employee_number"`
	EntityID         uuid.UUID          `json:"entity_id"`
	PositionTitle    pgtype.Text        `json:"position_title"`
	DepartmentID     pgtype.UUID        `json:"department_id"`
	ManagerID        pgtype.Int4        `json:"manager_id"`
	HireDate         pgtype.Date        `json:"hire_date"`
	TerminationDate  pgtype.Date        `json:"termination_date"`
	SalaryInfo       []byte             `json:"salary_info"`
	EmploymentStatus pgtype.Text        `json:"employment_status"`
	WorkSchedule     []byte             `json:"work_schedule"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            pgtype.Text        `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
}

func (q *Queries) ListEmployeesByManager(ctx context.Context, managerID pgtype.Int4) ([]ListEmployeesByManagerRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesByManager, managerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesByManagerRow{}
	for rows.Next() {
		var i ListEmployeesByManagerRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PersonID,
			&i.EmployeeNumber,
			&i.EntityID,
			&i.PositionTitle,
			&i.DepartmentID,
			&i.ManagerID,
			&i.HireDate,
			&i.TerminationDate,
			&i.SalaryInfo,
			&i.EmploymentStatus,
			&i.WorkSchedule,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees 
SET 
    employee_number = COALESCE($2, employee_number),
    entity_id = COALESCE($3, entity_id),
    position_title = COALESCE($4, position_title),
    department_id = COALESCE($5, department_id),
    manager_id = COALESCE($6, manager_id),
    hire_date = COALESCE($7, hire_date),
    termination_date = COALESCE($8, termination_date),
    salary_info = COALESCE($9, salary_info),
    employment_status = COALESCE($10, employment_status),
    work_schedule = COALESCE($11, work_schedule),
    updated_at = NOW()
WHERE id = $1 AND tenant_id = current_tenant_id()
RETURNING id, tenant_id, person_id, employee_number, entity_id, position_title, department_id, manager_id, hire_date, termination_date, salary_info, employment_status, work_schedule, created_at, updated_at
`

type UpdateEmployeeParams struct {
	ID               int32       `json:"id"`
	EmployeeNumber   string      `json:"employee_number"`
	EntityID         uuid.UUID   `json:"entity_id"`
	PositionTitle    pgtype.Text `json:"position_title"`
	DepartmentID     pgtype.UUID `json:"department_id"`
	ManagerID        pgtype.Int4 `json:"manager_id"`
	HireDate         pgtype.Date `json:"hire_date"`
	TerminationDate  pgtype.Date `json:"termination_date"`
	SalaryInfo       []byte      `json:"salary_info"`
	EmploymentStatus pgtype.Text `json:"employment_status"`
	WorkSchedule     []byte      `json:"work_schedule"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.EmployeeNumber,
		arg.EntityID,
		arg.PositionTitle,
		arg.DepartmentID,
		arg.ManagerID,
		arg.HireDate,
		arg.TerminationDate,
		arg.SalaryInfo,
		arg.EmploymentStatus,
		arg.WorkSchedule,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PersonID,
		&i.EmployeeNumber,
		&i.EntityID,
		&i.PositionTitle,
		&i.DepartmentID,
		&i.ManagerID,
		&i.HireDate,
		&i.TerminationDate,
		&i.SalaryInfo,
		&i.EmploymentStatus,
		&i.WorkSchedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
