// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: entities.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const archiveOldDeletedEntities = `-- name: ArchiveOldDeletedEntities :exec
DELETE FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND deleted_at < $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) ArchiveOldDeletedEntities(ctx context.Context, deletedAt sql.NullTime) error {
	_, err := q.db.Exec(ctx, archiveOldDeletedEntities, deletedAt)
	return err
}

const batchSoftDeleteEntities = `-- name: BatchSoftDeleteEntities :exec
UPDATE
  entities
SET
  deleted_at = NOW(),
  updated_at = NOW()
WHERE
  tenant_id = current_tenant_id()
  AND uuid = ANY($1::UUID [])
`

func (q *Queries) BatchSoftDeleteEntities(ctx context.Context, uuids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, batchSoftDeleteEntities, uuids)
	return err
}

const batchUpdateEntityStatus = `-- name: BatchUpdateEntityStatus :exec
UPDATE
  entities
SET
  is_active = $1,
  updated_at = NOW()
WHERE
  tenant_id = current_tenant_id()
  AND uuid = ANY($2::UUID [])
  AND deleted_at IS NULL
`

type BatchUpdateEntityStatusParams struct {
	IsActive bool        `json:"is_active"`
	Uuids    []uuid.UUID `json:"uuids"`
}

// ===============================================
// Batch Operations
// -- ===============================================
func (q *Queries) BatchUpdateEntityStatus(ctx context.Context, arg BatchUpdateEntityStatusParams) error {
	_, err := q.db.Exec(ctx, batchUpdateEntityStatus, arg.IsActive, arg.Uuids)
	return err
}

type BulkCreateEntityStatesParams struct {
	Uuid         uuid.UUID    `json:"uuid"`
	TenantID     uuid.UUID    `json:"tenant_id"`
	FiscalYear   *int16       `json:"fiscal_year"`
	Key          string       `json:"key"`
	Sequence     int64        `json:"sequence"`
	EntityID     uuid.UUID    `json:"entity_id"`
	EntityUnitID *uuid.UUID   `json:"entity_unit_id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

const bulkMoveEntities = `-- name: BulkMoveEntities :exec
UPDATE
  entities
SET
  parent_id = $1,
  updated_at = NOW()
WHERE
  tenant_id = current_tenant_id()
  AND uuid = ANY($2::UUID [])
  AND deleted_at IS NULL
`

type BulkMoveEntitiesParams struct {
	ParentID  *uuid.UUID  `json:"parent_id"`
	EntityIds []uuid.UUID `json:"entity_ids"`
}

func (q *Queries) BulkMoveEntities(ctx context.Context, arg BulkMoveEntitiesParams) error {
	_, err := q.db.Exec(ctx, bulkMoveEntities, arg.ParentID, arg.EntityIds)
	return err
}

const checkCircularReference = `-- name: CheckCircularReference :one
SELECT
  EXISTS(
    SELECT
      1
    FROM
      hierarchy_paths
    WHERE
      tenant_id = current_tenant_id()
      AND ancestor_id = $2
      AND descendant_id = $1
  )::BOOLEAN AS EXISTS
`

type CheckCircularReferenceParams struct {
	DescendantID uuid.UUID `json:"descendant_id"`
	AncestorID   uuid.UUID `json:"ancestor_id"`
}

func (q *Queries) CheckCircularReference(ctx context.Context, arg CheckCircularReferenceParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkCircularReference, arg.DescendantID, arg.AncestorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const cleanupOrphanedHierarchyPaths = `-- name: CleanupOrphanedHierarchyPaths :exec
DELETE FROM
  hierarchy_paths
WHERE
  tenant_id = current_tenant_id()
  AND (
    NOT EXISTS(
      SELECT
        1
      FROM
        entities
      WHERE
        uuid = ancestor_id
        AND tenant_id = current_tenant_id()
    )
    OR NOT EXISTS(
      SELECT
        1
      FROM
        entities
      WHERE
        uuid = descendant_id
        AND tenant_id = current_tenant_id()
    )
  )
`

// =====================================================================
// 7. MAINTENANCE AND CLEANUP QUERIES
// =====================================================================
func (q *Queries) CleanupOrphanedHierarchyPaths(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOrphanedHierarchyPaths)
	return err
}

const countEntitiesWithFilters = `-- name: CountEntitiesWithFilters :one
SELECT
  COUNT(*) AS count
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND (
    $1 IS NULL
    OR TYPE = $1
  )
  AND (
    $2 IS NULL
    OR is_active = $2
  )
  AND (
    $3 IS NULL
    OR hidden = $3
  )
`

type CountEntitiesWithFiltersParams struct {
	Type     interface{} `json:"type"`
	IsActive interface{} `json:"is_active"`
	Hidden   interface{} `json:"hidden"`
}

func (q *Queries) CountEntitiesWithFilters(ctx context.Context, arg CountEntitiesWithFiltersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEntitiesWithFilters, arg.Type, arg.IsActive, arg.Hidden)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntityStatesByEntity = `-- name: CountEntityStatesByEntity :one
SELECT
  COUNT(*)
FROM
  entitystate
WHERE
  entity_id = $1::UUID
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

func (q *Queries) CountEntityStatesByEntity(ctx context.Context, entityID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEntityStatesByEntity, entityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntityStatesByKey = `-- name: CountEntityStatesByKey :one
SELECT
  COUNT(*)
FROM
  entitystate
WHERE
  KEY = $1::VARCHAR(10)
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

func (q *Queries) CountEntityStatesByKey(ctx context.Context, key string) (int64, error) {
	row := q.db.QueryRow(ctx, countEntityStatesByKey, key)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntity = `-- name: CreateEntity :one
INSERT INTO
  entities (
    uuid,
    tenant_id,
    parent_id,
    name,
    code,
    TYPE,
    is_active,
    hidden,
    accrual_method,
    fy_start_month,
    address,
    picture,
    metadata,
    settings
  )
VALUES
  (
    $1,
    current_tenant_id(),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
  )
RETURNING
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
`

type CreateEntityParams struct {
	Uuid          uuid.UUID  `json:"uuid"`
	ParentID      *uuid.UUID `json:"parent_id"`
	Name          string     `json:"name"`
	Code          *string    `json:"code"`
	Type          string     `json:"type"`
	IsActive      bool       `json:"is_active"`
	Hidden        bool       `json:"hidden"`
	AccrualMethod bool       `json:"accrual_method"`
	FyStartMonth  int32      `json:"fy_start_month"`
	Address       []byte     `json:"address"`
	Picture       *string    `json:"picture"`
	Metadata      []byte     `json:"metadata"`
	Settings      []byte     `json:"settings"`
}

// Entity CRUD Operations
func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (*Entity, error) {
	row := q.db.QueryRow(ctx, createEntity,
		arg.Uuid,
		arg.ParentID,
		arg.Name,
		arg.Code,
		arg.Type,
		arg.IsActive,
		arg.Hidden,
		arg.AccrualMethod,
		arg.FyStartMonth,
		arg.Address,
		arg.Picture,
		arg.Metadata,
		arg.Settings,
	)
	var i Entity
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.IsActive,
		&i.Hidden,
		&i.AccrualMethod,
		&i.FyStartMonth,
		&i.Address,
		&i.Picture,
		&i.Settings,
		&i.Metadata,
		&i.Version,
		&i.LastValidationRun,
		&i.ValidationStatus,
		&i.ValidationErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const createEntityState = `-- name: CreateEntityState :one
INSERT INTO
  entitystate (
    uuid,
    tenant_id,
    fiscal_year,
    KEY,
    sequence,
    entity_id,
    entity_unit_id,
    created_at,
    updated_at
  )
VALUES
  (
    $1::UUID,
    current_tenant_id(),
    $2::SMALLINT,
    $3::VARCHAR(10),
    $4::BIGINT,
    $5::UUID,
    $6::UUID,
    NOW(),
    NOW()
  )
RETURNING
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
`

type CreateEntityStateParams struct {
	Uuid         uuid.UUID  `json:"uuid"`
	FiscalYear   *int16     `json:"fiscal_year"`
	Key          string     `json:"key"`
	Sequence     int64      `json:"sequence"`
	EntityID     uuid.UUID  `json:"entity_id"`
	EntityUnitID *uuid.UUID `json:"entity_unit_id"`
}

// =====================================================================
// ENTITYSTATE SQLC QUERIES
// =====================================================================
func (q *Queries) CreateEntityState(ctx context.Context, arg CreateEntityStateParams) (*Entitystate, error) {
	row := q.db.QueryRow(ctx, createEntityState,
		arg.Uuid,
		arg.FiscalYear,
		arg.Key,
		arg.Sequence,
		arg.EntityID,
		arg.EntityUnitID,
	)
	var i Entitystate
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.FiscalYear,
		&i.Key,
		&i.Sequence,
		&i.EntityID,
		&i.EntityUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const createHierarchyPath = `-- name: CreateHierarchyPath :exec
INSERT INTO
  hierarchy_paths (tenant_id, ancestor_id, descendant_id, depth)
VALUES
  (current_tenant_id(), $1, $2, $3)
`

type CreateHierarchyPathParams struct {
	AncestorID   uuid.UUID `json:"ancestor_id"`
	DescendantID uuid.UUID `json:"descendant_id"`
	Depth        int32     `json:"depth"`
}

// Entity Hierarchy Operations
func (q *Queries) CreateHierarchyPath(ctx context.Context, arg CreateHierarchyPathParams) error {
	_, err := q.db.Exec(ctx, createHierarchyPath, arg.AncestorID, arg.DescendantID, arg.Depth)
	return err
}

const deleteHierarchyPaths = `-- name: DeleteHierarchyPaths :exec
DELETE FROM
  hierarchy_paths
WHERE
  tenant_id = current_tenant_id()
  AND (
    ancestor_id = $1
    OR descendant_id = $1
  )
`

func (q *Queries) DeleteHierarchyPaths(ctx context.Context, ancestorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHierarchyPaths, ancestorID)
	return err
}

const getEntitiesByFiscalYear = `-- name: GetEntitiesByFiscalYear :many
SELECT
  DISTINCT e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at
FROM
  entities e
  JOIN entitystate es ON e.uuid = es.entity_id
WHERE
  e.tenant_id = current_tenant_id()
  AND es.fiscal_year = $1
  AND e.deleted_at IS NULL
ORDER BY
  e.name
`

func (q *Queries) GetEntitiesByFiscalYear(ctx context.Context, fiscalYear *int16) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, getEntitiesByFiscalYear, fiscalYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitiesByFiscalYearStart = `-- name: GetEntitiesByFiscalYearStart :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND fy_start_month = $1
  AND deleted_at IS NULL
ORDER BY
  name
`

func (q *Queries) GetEntitiesByFiscalYearStart(ctx context.Context, fyStartMonth int32) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, getEntitiesByFiscalYearStart, fyStartMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitiesByUUIDs = `-- name: GetEntitiesByUUIDs :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND uuid = ANY($1::UUID [])
  AND deleted_at IS NULL
ORDER BY
  name
`

func (q *Queries) GetEntitiesByUUIDs(ctx context.Context, uuids []uuid.UUID) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, getEntitiesByUUIDs, uuids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntity = `-- name: GetEntity :one
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  uuid = $1
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

func (q *Queries) GetEntity(ctx context.Context, argUuid uuid.UUID) (*Entity, error) {
	row := q.db.QueryRow(ctx, getEntity, argUuid)
	var i Entity
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.IsActive,
		&i.Hidden,
		&i.AccrualMethod,
		&i.FyStartMonth,
		&i.Address,
		&i.Picture,
		&i.Settings,
		&i.Metadata,
		&i.Version,
		&i.LastValidationRun,
		&i.ValidationStatus,
		&i.ValidationErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getEntityAncestors = `-- name: GetEntityAncestors :many
SELECT
  e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at,
  hp.depth
FROM
  entities e
  JOIN hierarchy_paths hp ON e.uuid = hp.ancestor_id
WHERE
  hp.tenant_id = current_tenant_id()
  AND hp.descendant_id = $1
  AND hp.depth > 0
  AND e.deleted_at IS NULL
ORDER BY
  hp.depth DESC
`

type GetEntityAncestorsRow struct {
	Uuid              uuid.UUID    `json:"uuid"`
	TenantID          uuid.UUID    `json:"tenant_id"`
	ParentID          *uuid.UUID   `json:"parent_id"`
	Name              string       `json:"name"`
	Code              *string      `json:"code"`
	Type              string       `json:"type"`
	IsActive          bool         `json:"is_active"`
	Hidden            bool         `json:"hidden"`
	AccrualMethod     bool         `json:"accrual_method"`
	FyStartMonth      int32        `json:"fy_start_month"`
	Address           []byte       `json:"address"`
	Picture           *string      `json:"picture"`
	Settings          []byte       `json:"settings"`
	Metadata          []byte       `json:"metadata"`
	Version           int32        `json:"version"`
	LastValidationRun sql.NullTime `json:"last_validation_run"`
	ValidationStatus  *string      `json:"validation_status"`
	ValidationErrors  []byte       `json:"validation_errors"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
	Depth             int32        `json:"depth"`
}

func (q *Queries) GetEntityAncestors(ctx context.Context, descendantID uuid.UUID) ([]*GetEntityAncestorsRow, error) {
	rows, err := q.db.Query(ctx, getEntityAncestors, descendantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEntityAncestorsRow{}
	for rows.Next() {
		var i GetEntityAncestorsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityAuditLog = `-- name: GetEntityAuditLog :many
SELECT
  uuid,
  name,
  TYPE,
  is_active,
  hidden,
  created_at,
  updated_at,
  deleted_at,
  CASE
    WHEN deleted_at IS NOT NULL THEN 'DELETED'
    WHEN updated_at > created_at THEN 'UPDATED'
    ELSE 'CREATED'
  END AS ACTION
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND (
    created_at >= $1
    OR updated_at >= $1
    OR deleted_at >= $1
  )
ORDER BY
  GREATEST(
    created_at,
    updated_at,
    COALESCE(deleted_at, created_at)
  ) DESC
`

type GetEntityAuditLogRow struct {
	Uuid      uuid.UUID    `json:"uuid"`
	Name      string       `json:"name"`
	Type      string       `json:"type"`
	IsActive  bool         `json:"is_active"`
	Hidden    bool         `json:"hidden"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Action    string       `json:"action"`
}

func (q *Queries) GetEntityAuditLog(ctx context.Context, createdAt time.Time) ([]*GetEntityAuditLogRow, error) {
	rows, err := q.db.Query(ctx, getEntityAuditLog, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEntityAuditLogRow{}
	for rows.Next() {
		var i GetEntityAuditLogRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityByCode = `-- name: GetEntityByCode :one
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  code = $1
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

func (q *Queries) GetEntityByCode(ctx context.Context, code *string) (*Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByCode, code)
	var i Entity
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.IsActive,
		&i.Hidden,
		&i.AccrualMethod,
		&i.FyStartMonth,
		&i.Address,
		&i.Picture,
		&i.Settings,
		&i.Metadata,
		&i.Version,
		&i.LastValidationRun,
		&i.ValidationStatus,
		&i.ValidationErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getEntityByName = `-- name: GetEntityByName :one
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  name = $1
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

func (q *Queries) GetEntityByName(ctx context.Context, name string) (*Entity, error) {
	row := q.db.QueryRow(ctx, getEntityByName, name)
	var i Entity
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.IsActive,
		&i.Hidden,
		&i.AccrualMethod,
		&i.FyStartMonth,
		&i.Address,
		&i.Picture,
		&i.Settings,
		&i.Metadata,
		&i.Version,
		&i.LastValidationRun,
		&i.ValidationStatus,
		&i.ValidationErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getEntityChildren = `-- name: GetEntityChildren :many
SELECT
  e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at
FROM
  entities e
  JOIN hierarchy_paths hp ON e.uuid = hp.descendant_id
WHERE
  hp.tenant_id = current_tenant_id()
  AND hp.ancestor_id = $1
  AND hp.depth = 1
  AND e.deleted_at IS NULL
ORDER BY
  e.name
`

func (q *Queries) GetEntityChildren(ctx context.Context, ancestorID uuid.UUID) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, getEntityChildren, ancestorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityCountByType = `-- name: GetEntityCountByType :many
SELECT
  TYPE,
  COUNT(*) AS count
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND deleted_at IS NULL
GROUP BY
  TYPE
ORDER BY
  count DESC
`

type GetEntityCountByTypeRow struct {
	Type  string `json:"type"`
	Count int64  `json:"count"`
}

// =====================================================================
// 6. PERFORMANCE AND ANALYTICS QUERIES
// =====================================================================
func (q *Queries) GetEntityCountByType(ctx context.Context) ([]*GetEntityCountByTypeRow, error) {
	rows, err := q.db.Query(ctx, getEntityCountByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEntityCountByTypeRow{}
	for rows.Next() {
		var i GetEntityCountByTypeRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityDepth = `-- name: GetEntityDepth :one
SELECT
  COALESCE(MAX(depth), 0) AS depth
FROM
  hierarchy_paths
WHERE
  tenant_id = current_tenant_id()
  AND ancestor_id = $1
`

func (q *Queries) GetEntityDepth(ctx context.Context, ancestorID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getEntityDepth, ancestorID)
	var depth interface{}
	err := row.Scan(&depth)
	return depth, err
}

const getEntityDescendants = `-- name: GetEntityDescendants :many
SELECT
  e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at,
  hp.depth
FROM
  entities e
  JOIN hierarchy_paths hp ON e.uuid = hp.descendant_id
WHERE
  hp.tenant_id = current_tenant_id()
  AND hp.ancestor_id = $1
  AND hp.depth > 0
  AND e.deleted_at IS NULL
ORDER BY
  hp.depth,
  e.name
`

type GetEntityDescendantsRow struct {
	Uuid              uuid.UUID    `json:"uuid"`
	TenantID          uuid.UUID    `json:"tenant_id"`
	ParentID          *uuid.UUID   `json:"parent_id"`
	Name              string       `json:"name"`
	Code              *string      `json:"code"`
	Type              string       `json:"type"`
	IsActive          bool         `json:"is_active"`
	Hidden            bool         `json:"hidden"`
	AccrualMethod     bool         `json:"accrual_method"`
	FyStartMonth      int32        `json:"fy_start_month"`
	Address           []byte       `json:"address"`
	Picture           *string      `json:"picture"`
	Settings          []byte       `json:"settings"`
	Metadata          []byte       `json:"metadata"`
	Version           int32        `json:"version"`
	LastValidationRun sql.NullTime `json:"last_validation_run"`
	ValidationStatus  *string      `json:"validation_status"`
	ValidationErrors  []byte       `json:"validation_errors"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
	Depth             int32        `json:"depth"`
}

func (q *Queries) GetEntityDescendants(ctx context.Context, ancestorID uuid.UUID) ([]*GetEntityDescendantsRow, error) {
	rows, err := q.db.Query(ctx, getEntityDescendants, ancestorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEntityDescendantsRow{}
	for rows.Next() {
		var i GetEntityDescendantsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityHealthCheck = `-- name: GetEntityHealthCheck :one
SELECT
  (
    SELECT
      COUNT(*)
    FROM
      entities
    WHERE
      tenant_id = current_tenant_id()
      AND deleted_at IS NULL
  ) AS active_entities,
  (
    SELECT
      COUNT(*)
    FROM
      hierarchy_paths
    WHERE
      tenant_id = current_tenant_id()
  ) AS hierarchy_paths,
  (
    SELECT
      COUNT(*)
    FROM
      entitystate es
      JOIN entities e ON es.entity_id = e.uuid
    WHERE
      e.tenant_id = current_tenant_id()
  ) AS entity_states,
  (
    SELECT
      COUNT(*)
    FROM
      entities e
      LEFT JOIN entities p ON e.parent_id = p.uuid
    WHERE
      e.tenant_id = current_tenant_id()
      AND e.parent_id IS NOT NULL
      AND p.uuid IS NULL
  ) AS orphaned_entities,
  (
    SELECT
      COUNT(*)
    FROM
      hierarchy_paths hp
      LEFT JOIN entities e1 ON hp.ancestor_id = e1.uuid
      LEFT JOIN entities e2 ON hp.descendant_id = e2.uuid
    WHERE
      hp.tenant_id = current_tenant_id()
      AND (
        e1.uuid IS NULL
        OR e2.uuid IS NULL
      )
  ) AS orphaned_paths
`

type GetEntityHealthCheckRow struct {
	ActiveEntities   int64 `json:"active_entities"`
	HierarchyPaths   int64 `json:"hierarchy_paths"`
	EntityStates     int64 `json:"entity_states"`
	OrphanedEntities int64 `json:"orphaned_entities"`
	OrphanedPaths    int64 `json:"orphaned_paths"`
}

func (q *Queries) GetEntityHealthCheck(ctx context.Context) (*GetEntityHealthCheckRow, error) {
	row := q.db.QueryRow(ctx, getEntityHealthCheck)
	var i GetEntityHealthCheckRow
	err := row.Scan(
		&i.ActiveEntities,
		&i.HierarchyPaths,
		&i.EntityStates,
		&i.OrphanedEntities,
		&i.OrphanedPaths,
	)
	return &i, err
}

const getEntityHierarchyStats = `-- name: GetEntityHierarchyStats :one
SELECT
  COUNT(*) AS total_entities,
  COUNT(*) FILTER (
    WHERE
      e.parent_id IS NULL
  ) AS root_entities,
  MAX(hp.depth) AS max_depth,
  AVG(hp.depth) AS avg_depth,
  COUNT(DISTINCT hp.ancestor_id) AS entities_with_children
FROM
  entities e
  LEFT JOIN hierarchy_paths hp ON e.uuid = hp.descendant_id
  AND hp.tenant_id = e.tenant_id
WHERE
  e.tenant_id = current_tenant_id()
  AND e.deleted_at IS NULL
`

type GetEntityHierarchyStatsRow struct {
	TotalEntities        int64       `json:"total_entities"`
	RootEntities         int64       `json:"root_entities"`
	MaxDepth             interface{} `json:"max_depth"`
	AvgDepth             float64     `json:"avg_depth"`
	EntitiesWithChildren int64       `json:"entities_with_children"`
}

func (q *Queries) GetEntityHierarchyStats(ctx context.Context) (*GetEntityHierarchyStatsRow, error) {
	row := q.db.QueryRow(ctx, getEntityHierarchyStats)
	var i GetEntityHierarchyStatsRow
	err := row.Scan(
		&i.TotalEntities,
		&i.RootEntities,
		&i.MaxDepth,
		&i.AvgDepth,
		&i.EntitiesWithChildren,
	)
	return &i, err
}

const getEntityLevel = `-- name: GetEntityLevel :one
SELECT
  COALESCE(MIN(hp.depth), 0) AS LEVEL
FROM
  hierarchy_paths hp
WHERE
  hp.tenant_id = current_tenant_id()
  AND hp.descendant_id = $1
`

func (q *Queries) GetEntityLevel(ctx context.Context, descendantID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getEntityLevel, descendantID)
	var level interface{}
	err := row.Scan(&level)
	return level, err
}

const getEntityParent = `-- name: GetEntityParent :one
SELECT
  e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at
FROM
  entities e
  JOIN hierarchy_paths hp ON e.uuid = hp.ancestor_id
WHERE
  hp.tenant_id = current_tenant_id()
  AND hp.descendant_id = $1
  AND hp.depth = 1
  AND e.deleted_at IS NULL
`

func (q *Queries) GetEntityParent(ctx context.Context, descendantID uuid.UUID) (*Entity, error) {
	row := q.db.QueryRow(ctx, getEntityParent, descendantID)
	var i Entity
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.IsActive,
		&i.Hidden,
		&i.AccrualMethod,
		&i.FyStartMonth,
		&i.Address,
		&i.Picture,
		&i.Settings,
		&i.Metadata,
		&i.Version,
		&i.LastValidationRun,
		&i.ValidationStatus,
		&i.ValidationErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getEntityPath = `-- name: GetEntityPath :many
SELECT
  e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at,
  hp.depth
FROM
  entities e
  JOIN hierarchy_paths hp ON e.uuid = hp.ancestor_id
WHERE
  hp.tenant_id = current_tenant_id()
  AND hp.descendant_id = $1
  AND e.deleted_at IS NULL
ORDER BY
  hp.depth DESC
`

type GetEntityPathRow struct {
	Uuid              uuid.UUID    `json:"uuid"`
	TenantID          uuid.UUID    `json:"tenant_id"`
	ParentID          *uuid.UUID   `json:"parent_id"`
	Name              string       `json:"name"`
	Code              *string      `json:"code"`
	Type              string       `json:"type"`
	IsActive          bool         `json:"is_active"`
	Hidden            bool         `json:"hidden"`
	AccrualMethod     bool         `json:"accrual_method"`
	FyStartMonth      int32        `json:"fy_start_month"`
	Address           []byte       `json:"address"`
	Picture           *string      `json:"picture"`
	Settings          []byte       `json:"settings"`
	Metadata          []byte       `json:"metadata"`
	Version           int32        `json:"version"`
	LastValidationRun sql.NullTime `json:"last_validation_run"`
	ValidationStatus  *string      `json:"validation_status"`
	ValidationErrors  []byte       `json:"validation_errors"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
	Depth             int32        `json:"depth"`
}

func (q *Queries) GetEntityPath(ctx context.Context, descendantID uuid.UUID) ([]*GetEntityPathRow, error) {
	rows, err := q.db.Query(ctx, getEntityPath, descendantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEntityPathRow{}
	for rows.Next() {
		var i GetEntityPathRow
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityRoots = `-- name: GetEntityRoots :many
SELECT
  e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at
FROM
  entities e
WHERE
  e.tenant_id = current_tenant_id()
  AND e.parent_id IS NULL
  AND e.deleted_at IS NULL
ORDER BY
  e.name
`

func (q *Queries) GetEntityRoots(ctx context.Context) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, getEntityRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitySequenceStats = `-- name: GetEntitySequenceStats :many
SELECT
  e.name AS entity_name,
  es.key,
  es.fiscal_year,
  es.sequence,
  es.sequence - 1 AS documents_created
FROM
  entitystate es
  JOIN entities e ON es.entity_id = e.uuid
WHERE
  e.tenant_id = current_tenant_id()
  AND (
    $1::UUID IS NULL
    OR es.entity_id = $1
  )
ORDER BY
  e.name,
  es.key,
  es.fiscal_year
`

type GetEntitySequenceStatsRow struct {
	EntityName       string `json:"entity_name"`
	Key              string `json:"key"`
	FiscalYear       *int16 `json:"fiscal_year"`
	Sequence         int64  `json:"sequence"`
	DocumentsCreated int32  `json:"documents_created"`
}

func (q *Queries) GetEntitySequenceStats(ctx context.Context, dollar_1 uuid.UUID) ([]*GetEntitySequenceStatsRow, error) {
	rows, err := q.db.Query(ctx, getEntitySequenceStats, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEntitySequenceStatsRow{}
	for rows.Next() {
		var i GetEntitySequenceStatsRow
		if err := rows.Scan(
			&i.EntityName,
			&i.Key,
			&i.FiscalYear,
			&i.Sequence,
			&i.DocumentsCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntitySiblings = `-- name: GetEntitySiblings :many
SELECT
  DISTINCT e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at
FROM
  entities e
  JOIN hierarchy_paths hp1 ON e.uuid = hp1.descendant_id
  JOIN hierarchy_paths hp2 ON hp1.ancestor_id = hp2.ancestor_id
WHERE
  hp2.tenant_id = current_tenant_id()
  AND hp2.descendant_id = $1
  AND hp1.depth = 1
  AND hp2.depth = 1
  AND e.uuid != $1
  AND e.deleted_at IS NULL
ORDER BY
  e.name
`

func (q *Queries) GetEntitySiblings(ctx context.Context, descendantID uuid.UUID) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, getEntitySiblings, descendantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityState = `-- name: GetEntityState :one
SELECT
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
FROM
  entitystate
WHERE
  uuid = $1::UUID
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

func (q *Queries) GetEntityState(ctx context.Context, argUuid uuid.UUID) (*Entitystate, error) {
	row := q.db.QueryRow(ctx, getEntityState, argUuid)
	var i Entitystate
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.FiscalYear,
		&i.Key,
		&i.Sequence,
		&i.EntityID,
		&i.EntityUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getEntityStateByEntityAndKey = `-- name: GetEntityStateByEntityAndKey :one
SELECT
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
FROM
  entitystate
WHERE
  entity_id = $1::UUID
  AND KEY = $2::VARCHAR(10)
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND (
    $3::SMALLINT IS NULL
    OR fiscal_year = $3::SMALLINT
  )
`

type GetEntityStateByEntityAndKeyParams struct {
	EntityID   uuid.UUID `json:"entity_id"`
	Key        string    `json:"key"`
	FiscalYear *int16    `json:"fiscal_year"`
}

func (q *Queries) GetEntityStateByEntityAndKey(ctx context.Context, arg GetEntityStateByEntityAndKeyParams) (*Entitystate, error) {
	row := q.db.QueryRow(ctx, getEntityStateByEntityAndKey, arg.EntityID, arg.Key, arg.FiscalYear)
	var i Entitystate
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.FiscalYear,
		&i.Key,
		&i.Sequence,
		&i.EntityID,
		&i.EntityUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getEntityStateByEntityKeyAndFiscalYear = `-- name: GetEntityStateByEntityKeyAndFiscalYear :one
SELECT
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
FROM
  entitystate
WHERE
  entity_id = $1::UUID
  AND KEY = $2::VARCHAR(10)
  AND fiscal_year = $3::SMALLINT
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

type GetEntityStateByEntityKeyAndFiscalYearParams struct {
	EntityID   uuid.UUID `json:"entity_id"`
	Key        string    `json:"key"`
	FiscalYear int16     `json:"fiscal_year"`
}

func (q *Queries) GetEntityStateByEntityKeyAndFiscalYear(ctx context.Context, arg GetEntityStateByEntityKeyAndFiscalYearParams) (*Entitystate, error) {
	row := q.db.QueryRow(ctx, getEntityStateByEntityKeyAndFiscalYear, arg.EntityID, arg.Key, arg.FiscalYear)
	var i Entitystate
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.FiscalYear,
		&i.Key,
		&i.Sequence,
		&i.EntityID,
		&i.EntityUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getEntityStatesWithPaging = `-- name: GetEntityStatesWithPaging :many
SELECT
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
FROM
  entitystate
WHERE
  tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND (
    $1 IS NULL
    OR entity_id = $1
  )
  AND (
    $2 IS NULL
    OR KEY = $2
  )
  AND (
    $3 IS NULL
    OR fiscal_year = $3
  )
ORDER BY
  created_at DESC
LIMIT
  $5 OFFSET $4
`

type GetEntityStatesWithPagingParams struct {
	EntityID   interface{} `json:"entity_id"`
	Key        interface{} `json:"key"`
	FiscalYear interface{} `json:"fiscal_year"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) GetEntityStatesWithPaging(ctx context.Context, arg GetEntityStatesWithPagingParams) ([]*Entitystate, error) {
	rows, err := q.db.Query(ctx, getEntityStatesWithPaging,
		arg.EntityID,
		arg.Key,
		arg.FiscalYear,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entitystate{}
	for rows.Next() {
		var i Entitystate
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.FiscalYear,
			&i.Key,
			&i.Sequence,
			&i.EntityID,
			&i.EntityUnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityStats = `-- name: GetEntityStats :one
SELECT
  COUNT(*) AS total_entities,
  SUM(
    CASE
      WHEN is_active = TRUE THEN 1
      ELSE 0
    END
  ) AS active_entities,
  SUM(
    CASE
      WHEN hidden = false THEN 1
      ELSE 0
    END
  ) AS visible_entities,
  COUNT(DISTINCT TYPE) AS entity_types,
  SUM(
    CASE
      WHEN parent_id IS NULL THEN 1
      ELSE 0
    END
  ) AS root_entities,
  SUM(
    CASE
      WHEN accrual_method = TRUE THEN 1
      ELSE 0
    END
  ) AS accrual_entities,
  SUM(
    CASE
      WHEN accrual_method = false THEN 1
      ELSE 0
    END
  ) AS cash_entities
FROM
  entities
`

type GetEntityStatsRow struct {
	TotalEntities   int64 `json:"total_entities"`
	ActiveEntities  int64 `json:"active_entities"`
	VisibleEntities int64 `json:"visible_entities"`
	EntityTypes     int64 `json:"entity_types"`
	RootEntities    int64 `json:"root_entities"`
	AccrualEntities int64 `json:"accrual_entities"`
	CashEntities    int64 `json:"cash_entities"`
}

func (q *Queries) GetEntityStats(ctx context.Context) (*GetEntityStatsRow, error) {
	row := q.db.QueryRow(ctx, getEntityStats)
	var i GetEntityStatsRow
	err := row.Scan(
		&i.TotalEntities,
		&i.ActiveEntities,
		&i.VisibleEntities,
		&i.EntityTypes,
		&i.RootEntities,
		&i.AccrualEntities,
		&i.CashEntities,
	)
	return &i, err
}

const getEntitySubtree = `-- name: GetEntitySubtree :many
SELECT
  e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at,
  hp.depth
FROM
  entities e
  JOIN hierarchy_paths hp ON e.uuid = hp.descendant_id
WHERE
  hp.tenant_id = current_tenant_id()
  AND hp.ancestor_id = $1
  AND e.deleted_at IS NULL
  AND (
    $2::INTEGER IS NULL
    OR hp.depth <= $2
  )
ORDER BY
  hp.depth,
  e.name
`

type GetEntitySubtreeParams struct {
	AncestorID uuid.UUID `json:"ancestor_id"`
	Column2    int32     `json:"column_2"`
}

type GetEntitySubtreeRow struct {
	Uuid              uuid.UUID    `json:"uuid"`
	TenantID          uuid.UUID    `json:"tenant_id"`
	ParentID          *uuid.UUID   `json:"parent_id"`
	Name              string       `json:"name"`
	Code              *string      `json:"code"`
	Type              string       `json:"type"`
	IsActive          bool         `json:"is_active"`
	Hidden            bool         `json:"hidden"`
	AccrualMethod     bool         `json:"accrual_method"`
	FyStartMonth      int32        `json:"fy_start_month"`
	Address           []byte       `json:"address"`
	Picture           *string      `json:"picture"`
	Settings          []byte       `json:"settings"`
	Metadata          []byte       `json:"metadata"`
	Version           int32        `json:"version"`
	LastValidationRun sql.NullTime `json:"last_validation_run"`
	ValidationStatus  *string      `json:"validation_status"`
	ValidationErrors  []byte       `json:"validation_errors"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
	Depth             int32        `json:"depth"`
}

func (q *Queries) GetEntitySubtree(ctx context.Context, arg GetEntitySubtreeParams) ([]*GetEntitySubtreeRow, error) {
	rows, err := q.db.Query(ctx, getEntitySubtree, arg.AncestorID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEntitySubtreeRow{}
	for rows.Next() {
		var i GetEntitySubtreeRow
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityTreeStructure = `-- name: GetEntityTreeStructure :many
WITH RECURSIVE entity_tree AS (
  SELECT
    e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at,
    0 AS LEVEL,
    CAST(e.name AS TEXT) AS path_text,
    CAST(e.name AS TEXT) AS sort_path
  FROM
    entities e
  WHERE
    e.tenant_id = current_tenant_id()
    AND e.parent_id IS NULL
    AND e.deleted_at IS NULL
  UNION
  ALL
  SELECT
    e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at,
    et.level + 1,
    CAST(et.path_text || ' > ' || e.name AS TEXT),
    CAST(et.sort_path || '/' || e.name AS TEXT)
  FROM
    entities e
    JOIN entity_tree et ON e.parent_id = et.uuid
  WHERE
    e.tenant_id = current_tenant_id()
    AND e.deleted_at IS NULL
    AND et.level < 10
)
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at, level, path_text, sort_path
FROM
  entity_tree
ORDER BY
  sort_path
`

type GetEntityTreeStructureRow struct {
	Uuid              uuid.UUID    `json:"uuid"`
	TenantID          uuid.UUID    `json:"tenant_id"`
	ParentID          *uuid.UUID   `json:"parent_id"`
	Name              string       `json:"name"`
	Code              *string      `json:"code"`
	Type              string       `json:"type"`
	IsActive          bool         `json:"is_active"`
	Hidden            bool         `json:"hidden"`
	AccrualMethod     bool         `json:"accrual_method"`
	FyStartMonth      int32        `json:"fy_start_month"`
	Address           []byte       `json:"address"`
	Picture           *string      `json:"picture"`
	Settings          []byte       `json:"settings"`
	Metadata          []byte       `json:"metadata"`
	Version           int32        `json:"version"`
	LastValidationRun sql.NullTime `json:"last_validation_run"`
	ValidationStatus  *string      `json:"validation_status"`
	ValidationErrors  []byte       `json:"validation_errors"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
	Level             int32        `json:"level"`
	PathText          string       `json:"path_text"`
	SortPath          string       `json:"sort_path"`
}

func (q *Queries) GetEntityTreeStructure(ctx context.Context) ([]*GetEntityTreeStructureRow, error) {
	rows, err := q.db.Query(ctx, getEntityTreeStructure)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEntityTreeStructureRow{}
	for rows.Next() {
		var i GetEntityTreeStructureRow
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Level,
			&i.PathText,
			&i.SortPath,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityWithHierarchyInfo = `-- name: GetEntityWithHierarchyInfo :one
SELECT
  e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at,
  COALESCE(MIN(hp.depth), 0) AS LEVEL,
  COUNT(children.uuid) AS child_count,
  parent_e.name AS parent_name
FROM
  entities e
  LEFT JOIN hierarchy_paths hp ON e.uuid = hp.descendant_id
  AND hp.tenant_id = e.tenant_id
  LEFT JOIN entities children ON children.parent_id = e.uuid
  AND children.tenant_id = e.tenant_id
  AND children.deleted_at IS NULL
  LEFT JOIN entities parent_e ON parent_e.uuid = e.parent_id
  AND parent_e.tenant_id = e.tenant_id
WHERE
  e.uuid = $1
  AND e.tenant_id = current_tenant_id()
  AND e.deleted_at IS NULL
GROUP BY
  e.uuid,
  parent_e.name
`

type GetEntityWithHierarchyInfoRow struct {
	Uuid              uuid.UUID    `json:"uuid"`
	TenantID          uuid.UUID    `json:"tenant_id"`
	ParentID          *uuid.UUID   `json:"parent_id"`
	Name              string       `json:"name"`
	Code              *string      `json:"code"`
	Type              string       `json:"type"`
	IsActive          bool         `json:"is_active"`
	Hidden            bool         `json:"hidden"`
	AccrualMethod     bool         `json:"accrual_method"`
	FyStartMonth      int32        `json:"fy_start_month"`
	Address           []byte       `json:"address"`
	Picture           *string      `json:"picture"`
	Settings          []byte       `json:"settings"`
	Metadata          []byte       `json:"metadata"`
	Version           int32        `json:"version"`
	LastValidationRun sql.NullTime `json:"last_validation_run"`
	ValidationStatus  *string      `json:"validation_status"`
	ValidationErrors  []byte       `json:"validation_errors"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
	Level             interface{}  `json:"level"`
	ChildCount        int64        `json:"child_count"`
	ParentName        *string      `json:"parent_name"`
}

// ===============================================
// Advanced Entity Queries
// ===============================================
func (q *Queries) GetEntityWithHierarchyInfo(ctx context.Context, argUuid uuid.UUID) (*GetEntityWithHierarchyInfoRow, error) {
	row := q.db.QueryRow(ctx, getEntityWithHierarchyInfo, argUuid)
	var i GetEntityWithHierarchyInfoRow
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.IsActive,
		&i.Hidden,
		&i.AccrualMethod,
		&i.FyStartMonth,
		&i.Address,
		&i.Picture,
		&i.Settings,
		&i.Metadata,
		&i.Version,
		&i.LastValidationRun,
		&i.ValidationStatus,
		&i.ValidationErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Level,
		&i.ChildCount,
		&i.ParentName,
	)
	return &i, err
}

const getInconsistentHierarchyPaths = `-- name: GetInconsistentHierarchyPaths :many
SELECT
  DISTINCT hp.ancestor_id,
  hp.descendant_id,
  hp.depth
FROM
  hierarchy_paths hp
  LEFT JOIN entities e1 ON hp.ancestor_id = e1.uuid
  AND e1.tenant_id = hp.tenant_id
  LEFT JOIN entities e2 ON hp.descendant_id = e2.uuid
  AND e2.tenant_id = hp.tenant_id
WHERE
  hp.tenant_id = current_tenant_id()
  AND (
    e1.uuid IS NULL
    OR e2.uuid IS NULL
    OR e1.deleted_at IS NOT NULL
    OR e2.deleted_at IS NOT NULL
  )
`

type GetInconsistentHierarchyPathsRow struct {
	AncestorID   uuid.UUID `json:"ancestor_id"`
	DescendantID uuid.UUID `json:"descendant_id"`
	Depth        int32     `json:"depth"`
}

func (q *Queries) GetInconsistentHierarchyPaths(ctx context.Context) ([]*GetInconsistentHierarchyPathsRow, error) {
	rows, err := q.db.Query(ctx, getInconsistentHierarchyPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetInconsistentHierarchyPathsRow{}
	for rows.Next() {
		var i GetInconsistentHierarchyPathsRow
		if err := rows.Scan(&i.AncestorID, &i.DescendantID, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxSequenceByEntityAndKey = `-- name: GetMaxSequenceByEntityAndKey :one
SELECT
  COALESCE(MAX(sequence), 0) AS max_sequence
FROM
  entitystate
WHERE
  entity_id = $1::UUID
  AND KEY = $2::VARCHAR(10)
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND (
    $3::SMALLINT IS NULL
    OR fiscal_year = $3::SMALLINT
  )
`

type GetMaxSequenceByEntityAndKeyParams struct {
	EntityID   uuid.UUID `json:"entity_id"`
	Key        string    `json:"key"`
	FiscalYear *int16    `json:"fiscal_year"`
}

func (q *Queries) GetMaxSequenceByEntityAndKey(ctx context.Context, arg GetMaxSequenceByEntityAndKeyParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxSequenceByEntityAndKey, arg.EntityID, arg.Key, arg.FiscalYear)
	var max_sequence interface{}
	err := row.Scan(&max_sequence)
	return max_sequence, err
}

const getNextSequenceAndIncrement = `-- name: GetNextSequenceAndIncrement :one
UPDATE
  entitystate
SET
  sequence = sequence + 1,
  updated_at = NOW()
WHERE
  entity_id = $1::UUID
  AND KEY = $2::VARCHAR(10)
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND (
    $3::SMALLINT IS NULL
    OR fiscal_year = $3::SMALLINT
  )
RETURNING
  sequence - 1 AS used_sequence,
  sequence AS next_sequence
`

type GetNextSequenceAndIncrementParams struct {
	EntityID   uuid.UUID `json:"entity_id"`
	Key        string    `json:"key"`
	FiscalYear *int16    `json:"fiscal_year"`
}

type GetNextSequenceAndIncrementRow struct {
	UsedSequence int32 `json:"used_sequence"`
	NextSequence int64 `json:"next_sequence"`
}

// -- name: GetOrCreateEntityState :one
// WITH existing AS (
//
//	SELECT *
//	FROM entitystate
//	WHERE entity_id = sqlc.arg(entity_id)::UUID
//	  AND key = sqlc.arg(key)::VARCHAR(10)
//	  AND tenant_id = current_tenant_id()
//	  AND deleted_at IS NULL
//	  AND (sqlc.narg(fiscal_year)::SMALLINT IS NULL OR fiscal_year = sqlc.narg(fiscal_year)::SMALLINT)
//
// ),
// new_record AS (
//
//	INSERT INTO entitystate (
//	    uuid,
//	    tenant_id,
//	    fiscal_year,
//	    key,
//	    sequence,
//	    entity_id,
//	    entity_unit_id,
//	    created_at,
//	    updated_at
//	)
//	SELECT
//	    sqlc.arg(uuid)::UUID,
//	    current_tenant_id(),
//	    sqlc.narg(fiscal_year)::SMALLINT,
//	    sqlc.arg(key)::VARCHAR(10),
//	    sqlc.arg(sequence)::BIGINT,
//	    sqlc.arg(entity_id)::UUID,
//	    sqlc.narg(entity_unit_id)::UUID,
//	    NOW(),
//	    NOW()
//	WHERE NOT EXISTS (SELECT 1 FROM existing)
//	RETURNING *
//
// )
// SELECT * FROM existing
// UNION ALL
// SELECT * FROM new_record;
func (q *Queries) GetNextSequenceAndIncrement(ctx context.Context, arg GetNextSequenceAndIncrementParams) (*GetNextSequenceAndIncrementRow, error) {
	row := q.db.QueryRow(ctx, getNextSequenceAndIncrement, arg.EntityID, arg.Key, arg.FiscalYear)
	var i GetNextSequenceAndIncrementRow
	err := row.Scan(&i.UsedSequence, &i.NextSequence)
	return &i, err
}

const getNextSequenceNumber = `-- name: GetNextSequenceNumber :one
SELECT
  sequence
FROM
  entitystate
WHERE
  entity_id = $1::UUID
  AND KEY = $2::VARCHAR(10)
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND (
    $3::SMALLINT IS NULL
    OR fiscal_year = $3::SMALLINT
  ) FOR
UPDATE
`

type GetNextSequenceNumberParams struct {
	EntityID   uuid.UUID `json:"entity_id"`
	Key        string    `json:"key"`
	FiscalYear *int16    `json:"fiscal_year"`
}

func (q *Queries) GetNextSequenceNumber(ctx context.Context, arg GetNextSequenceNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, getNextSequenceNumber, arg.EntityID, arg.Key, arg.FiscalYear)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const getOrphanedEntities = `-- name: GetOrphanedEntities :many
SELECT
  e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at
FROM
  entities e
  LEFT JOIN entities parent ON parent.uuid = e.parent_id
  AND parent.tenant_id = e.tenant_id
WHERE
  e.tenant_id = current_tenant_id()
  AND e.parent_id IS NOT NULL
  AND parent.uuid IS NULL
  AND e.deleted_at IS NULL
`

func (q *Queries) GetOrphanedEntities(ctx context.Context) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, getOrphanedEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyDeletedEntities = `-- name: GetRecentlyDeletedEntities :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND deleted_at >= $1
  AND deleted_at IS NOT NULL
ORDER BY
  deleted_at DESC
LIMIT
  $2
`

type GetRecentlyDeletedEntitiesParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	Limit     int32        `json:"limit"`
}

func (q *Queries) GetRecentlyDeletedEntities(ctx context.Context, arg GetRecentlyDeletedEntitiesParams) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, getRecentlyDeletedEntities, arg.DeletedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyModifiedEntities = `-- name: GetRecentlyModifiedEntities :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND updated_at >= $1
  AND deleted_at IS NULL
ORDER BY
  updated_at DESC
LIMIT
  $2
`

type GetRecentlyModifiedEntitiesParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

// =====================================================================
// 4. AUDIT AND MONITORING QUERIES
// =====================================================================
func (q *Queries) GetRecentlyModifiedEntities(ctx context.Context, arg GetRecentlyModifiedEntitiesParams) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, getRecentlyModifiedEntities, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnusedEntityCodes = `-- name: GetUnusedEntityCodes :many
SELECT
  DISTINCT code
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND code IS NOT NULL
  AND deleted_at IS NOT NULL
ORDER BY
  code
`

func (q *Queries) GetUnusedEntityCodes(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, getUnusedEntityCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var code *string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get_OrCreateEntityState = `-- name: Get_OrCreateEntityState :one
WITH ins AS (
  INSERT INTO
    entitystate (
      uuid,
      tenant_id,
      fiscal_year,
      KEY,
      sequence,
      entity_id,
      entity_unit_id,
      created_at,
      updated_at
    )
  VALUES
    (
      $1,  -- generate UUID in app layer
      current_tenant_id(),
      $2,
      $3,
      1,  -- start sequence at 1
      $4,
      $5,
      NOW(),
      NOW()
    ) ON CONFLICT (tenant_id, fiscal_year, KEY, entity_id) DO NOTHING
  RETURNING
    uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
)
SELECT
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
FROM
  ins
UNION
SELECT
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
FROM
  entitystate
WHERE
  tenant_id = current_tenant_id()
  AND fiscal_year = $2
  AND KEY = $3
  AND entity_id = $4
  AND deleted_at IS NULL
LIMIT
  1
`

type Get_OrCreateEntityStateParams struct {
	Uuid         uuid.UUID  `json:"uuid"`
	FiscalYear   *int16     `json:"fiscal_year"`
	Key          string     `json:"key"`
	EntityID     uuid.UUID  `json:"entity_id"`
	EntityUnitID *uuid.UUID `json:"entity_unit_id"`
}

type Get_OrCreateEntityStateRow struct {
	Uuid         uuid.UUID    `json:"uuid"`
	TenantID     uuid.UUID    `json:"tenant_id"`
	FiscalYear   *int16       `json:"fiscal_year"`
	Key          string       `json:"key"`
	Sequence     int64        `json:"sequence"`
	EntityID     uuid.UUID    `json:"entity_id"`
	EntityUnitID *uuid.UUID   `json:"entity_unit_id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

func (q *Queries) Get_OrCreateEntityState(ctx context.Context, arg Get_OrCreateEntityStateParams) (*Get_OrCreateEntityStateRow, error) {
	row := q.db.QueryRow(ctx, get_OrCreateEntityState,
		arg.Uuid,
		arg.FiscalYear,
		arg.Key,
		arg.EntityID,
		arg.EntityUnitID,
	)
	var i Get_OrCreateEntityStateRow
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.FiscalYear,
		&i.Key,
		&i.Sequence,
		&i.EntityID,
		&i.EntityUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const hardDeleteEntity = `-- name: HardDeleteEntity :exec
DELETE FROM
  entities
WHERE
  uuid = $1
  AND tenant_id = current_tenant_id()
`

func (q *Queries) HardDeleteEntity(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteEntity, argUuid)
	return err
}

const incrementSequenceNumber = `-- name: IncrementSequenceNumber :one
UPDATE
  entitystate
SET
  sequence = sequence + 1,
  updated_at = NOW()
WHERE
  uuid = $1::UUID
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
RETURNING
  sequence
`

func (q *Queries) IncrementSequenceNumber(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, incrementSequenceNumber, argUuid)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const isEntityAncestor = `-- name: IsEntityAncestor :one
SELECT
  EXISTS(
    SELECT
      1
    FROM
      hierarchy_paths
    WHERE
      tenant_id = current_tenant_id()
      AND ancestor_id = $1
      AND descendant_id = $2
      AND depth > 0
  ) AS is_ancestor
`

type IsEntityAncestorParams struct {
	AncestorID   uuid.UUID `json:"ancestor_id"`
	DescendantID uuid.UUID `json:"descendant_id"`
}

func (q *Queries) IsEntityAncestor(ctx context.Context, arg IsEntityAncestorParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEntityAncestor, arg.AncestorID, arg.DescendantID)
	var is_ancestor bool
	err := row.Scan(&is_ancestor)
	return is_ancestor, err
}

const listActiveEntities = `-- name: ListActiveEntities :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND is_active = TRUE
  AND deleted_at IS NULL
ORDER BY
  name
`

func (q *Queries) ListActiveEntities(ctx context.Context) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, listActiveEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntities = `-- name: ListEntities :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND deleted_at IS NULL
ORDER BY
  name
`

// Entity Listing and Filtering
func (q *Queries) ListEntities(ctx context.Context) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, listEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByType = `-- name: ListEntitiesByType :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND TYPE = $1
  AND deleted_at IS NULL
ORDER BY
  name
`

func (q *Queries) ListEntitiesByType(ctx context.Context, type_ string) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByTypes = `-- name: ListEntitiesByTypes :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND TYPE = ANY($1::VARCHAR [])
  AND deleted_at IS NULL
ORDER BY
  TYPE,
  name
`

func (q *Queries) ListEntitiesByTypes(ctx context.Context, dollar_1 []string) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesByTypes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesWithNochildren = `-- name: ListEntitiesWithNochildren :many
SELECT
  e.uuid, e.tenant_id, e.parent_id, e.name, e.code, e.type, e.is_active, e.hidden, e.accrual_method, e.fy_start_month, e.address, e.picture, e.settings, e.metadata, e.version, e.last_validation_run, e.validation_status, e.validation_errors, e.created_at, e.updated_at, e.deleted_at
FROM
  entities e
  LEFT JOIN entities children ON children.parent_id = e.uuid
  AND children.tenant_id = e.tenant_id
WHERE
  children.uuid IS NULL
  AND e.is_active = TRUE
`

// Find all leaf nodes (entities with no children)
func (q *Queries) ListEntitiesWithNochildren(ctx context.Context) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesWithNochildren)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesWithPagination = `-- name: ListEntitiesWithPagination :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND (
    $1 IS NULL
    OR TYPE = $1
  )
  AND (
    $2 IS NULL
    OR is_active = $2
  )
  AND (
    $3 IS NULL
    OR hidden = $3
  )
ORDER BY
  name
LIMIT
  $5 OFFSET $4
`

type ListEntitiesWithPaginationParams struct {
	Type     interface{} `json:"type"`
	IsActive interface{} `json:"is_active"`
	Hidden   interface{} `json:"hidden"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListEntitiesWithPagination(ctx context.Context, arg ListEntitiesWithPaginationParams) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesWithPagination,
		arg.Type,
		arg.IsActive,
		arg.Hidden,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityStatesByEntity = `-- name: ListEntityStatesByEntity :many
SELECT
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
FROM
  entitystate
WHERE
  entity_id = $1::UUID
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
ORDER BY
  KEY,
  fiscal_year
`

func (q *Queries) ListEntityStatesByEntity(ctx context.Context, entityID uuid.UUID) ([]*Entitystate, error) {
	rows, err := q.db.Query(ctx, listEntityStatesByEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entitystate{}
	for rows.Next() {
		var i Entitystate
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.FiscalYear,
			&i.Key,
			&i.Sequence,
			&i.EntityID,
			&i.EntityUnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityStatesByEntityAndKey = `-- name: ListEntityStatesByEntityAndKey :many
SELECT
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
FROM
  entitystate
WHERE
  entity_id = $1::UUID
  AND KEY = $2::VARCHAR(10)
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
ORDER BY
  fiscal_year
`

type ListEntityStatesByEntityAndKeyParams struct {
	EntityID uuid.UUID `json:"entity_id"`
	Key      string    `json:"key"`
}

func (q *Queries) ListEntityStatesByEntityAndKey(ctx context.Context, arg ListEntityStatesByEntityAndKeyParams) ([]*Entitystate, error) {
	rows, err := q.db.Query(ctx, listEntityStatesByEntityAndKey, arg.EntityID, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entitystate{}
	for rows.Next() {
		var i Entitystate
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.FiscalYear,
			&i.Key,
			&i.Sequence,
			&i.EntityID,
			&i.EntityUnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityStatesByEntityUnit = `-- name: ListEntityStatesByEntityUnit :many
SELECT
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
FROM
  entitystate
WHERE
  entity_unit_id = $1::UUID
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
ORDER BY
  entity_id,
  KEY,
  fiscal_year
`

func (q *Queries) ListEntityStatesByEntityUnit(ctx context.Context, entityUnitID uuid.UUID) ([]*Entitystate, error) {
	rows, err := q.db.Query(ctx, listEntityStatesByEntityUnit, entityUnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entitystate{}
	for rows.Next() {
		var i Entitystate
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.FiscalYear,
			&i.Key,
			&i.Sequence,
			&i.EntityID,
			&i.EntityUnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityStatesByFiscalYear = `-- name: ListEntityStatesByFiscalYear :many
SELECT
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
FROM
  entitystate
WHERE
  fiscal_year = $1::SMALLINT
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
ORDER BY
  entity_id,
  KEY
`

func (q *Queries) ListEntityStatesByFiscalYear(ctx context.Context, fiscalYear int16) ([]*Entitystate, error) {
	rows, err := q.db.Query(ctx, listEntityStatesByFiscalYear, fiscalYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entitystate{}
	for rows.Next() {
		var i Entitystate
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.FiscalYear,
			&i.Key,
			&i.Sequence,
			&i.EntityID,
			&i.EntityUnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleEntities = `-- name: ListVisibleEntities :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND hidden = false
  AND deleted_at IS NULL
ORDER BY
  name
`

func (q *Queries) ListVisibleEntities(ctx context.Context) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, listVisibleEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveEntityToNewParent = `-- name: MoveEntityToNewParent :exec
WITH RECURSIVE affected_entities AS (
  SELECT
    $1::UUID AS entity_id,
    0 AS depth
  UNION
  ALL
  SELECT
    hp.descendant_id,
    ae.depth + 1
  FROM
    affected_entities ae
    JOIN hierarchy_paths hp ON hp.ancestor_id = ae.entity_id
  WHERE
    ae.depth < 10
),
delete_paths AS (
  DELETE FROM
    hierarchy_paths
  WHERE
    descendant_id IN (
      SELECT
        entity_id
      FROM
        affected_entities
    )
),
insert_new_paths AS (
  INSERT INTO
    hierarchy_paths (tenant_id, ancestor_id, descendant_id, depth)
  SELECT
    current_tenant_id(),
    ancestor_paths.ancestor_id,
    ae.entity_id,
    ancestor_paths.depth + descendant_paths.depth + 1
  FROM
    affected_entities ae
    CROSS JOIN (
      SELECT
        ancestor_id,
        depth
      FROM
        hierarchy_paths
      WHERE
        descendant_id = $2
      UNION
      ALL
      SELECT
        $2::UUID,
        0
    ) ancestor_paths
    CROSS JOIN (
      SELECT
        descendant_id,
        depth
      FROM
        hierarchy_paths
      WHERE
        ancestor_id = $1
      UNION
      ALL
      SELECT
        $1::UUID,
        0
    ) descendant_paths
  WHERE
    ae.entity_id = descendant_paths.descendant_id
)
UPDATE
  entities
SET
  parent_id = $2,
  updated_at = NOW()
WHERE
  uuid = $1
`

type MoveEntityToNewParentParams struct {
	Uuid     uuid.UUID  `json:"uuid"`
	ParentID *uuid.UUID `json:"parent_id"`
}

// =====================================================================
// 3. HIERARCHY BULK OPERATIONS
// =====================================================================
func (q *Queries) MoveEntityToNewParent(ctx context.Context, arg MoveEntityToNewParentParams) error {
	_, err := q.db.Exec(ctx, moveEntityToNewParent, arg.Uuid, arg.ParentID)
	return err
}

const rebuildHierarchyPaths = `-- name: RebuildHierarchyPaths :exec
WITH RECURSIVE entity_hierarchy AS (
  SELECT
    uuid AS ancestor_id,
    uuid AS descendant_id,
    0 AS depth,
    tenant_id
  FROM
    entities
  WHERE
    tenant_id = current_tenant_id()
    AND deleted_at IS NULL
  UNION
  ALL
  SELECT
    eh.ancestor_id,
    e.uuid,
    eh.depth + 1,
    e.tenant_id
  FROM
    entity_hierarchy eh
    JOIN entities e ON e.parent_id = eh.descendant_id
  WHERE
    e.tenant_id = current_tenant_id()
    AND e.deleted_at IS NULL
    AND eh.depth < 10
),
cleanup AS (
  DELETE FROM
    hierarchy_paths
  WHERE
    tenant_id = current_tenant_id()
)
INSERT INTO
  hierarchy_paths (tenant_id, ancestor_id, descendant_id, depth)
SELECT
  tenant_id,
  ancestor_id,
  descendant_id,
  depth
FROM
  entity_hierarchy
`

func (q *Queries) RebuildHierarchyPaths(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildHierarchyPaths)
	return err
}

const resetSequenceNumber = `-- name: ResetSequenceNumber :one
UPDATE
  entitystate
SET
  sequence = $1::BIGINT,
  updated_at = NOW()
WHERE
  uuid = $2::UUID
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
RETURNING
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
`

type ResetSequenceNumberParams struct {
	Sequence int64     `json:"sequence"`
	Uuid     uuid.UUID `json:"uuid"`
}

func (q *Queries) ResetSequenceNumber(ctx context.Context, arg ResetSequenceNumberParams) (*Entitystate, error) {
	row := q.db.QueryRow(ctx, resetSequenceNumber, arg.Sequence, arg.Uuid)
	var i Entitystate
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.FiscalYear,
		&i.Key,
		&i.Sequence,
		&i.EntityID,
		&i.EntityUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const restoreEntity = `-- name: RestoreEntity :exec
UPDATE
  entities
SET
  deleted_at = NULL,
  updated_at = NOW()
WHERE
  uuid = $1
  AND tenant_id = current_tenant_id()
`

func (q *Queries) RestoreEntity(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreEntity, argUuid)
	return err
}

const searchEntitiesByCodeAndName = `-- name: SearchEntitiesByCodeAndName :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND (
    code ILIKE '%' || $1 || '%'
    OR name ILIKE '%' || $1 || '%'
  )
  AND deleted_at IS NULL
ORDER BY
  CASE
    WHEN code ILIKE $1 || '%' THEN 1
    WHEN name ILIKE $1 || '%' THEN 2
    ELSE 3
  END,
  name
LIMIT
  $2
`

type SearchEntitiesByCodeAndNameParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
}

// =====================================================================
// 2. ENTITY SEARCH AND FILTERING ENHANCEMENTS
// =====================================================================
func (q *Queries) SearchEntitiesByCodeAndName(ctx context.Context, arg SearchEntitiesByCodeAndNameParams) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, searchEntitiesByCodeAndName, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEntitiesByName = `-- name: SearchEntitiesByName :many
SELECT
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
FROM
  entities
WHERE
  tenant_id = current_tenant_id()
  AND name ILIKE '%' || $1 || '%'
  AND deleted_at IS NULL
ORDER BY
  name
LIMIT
  $2
`

type SearchEntitiesByNameParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
}

func (q *Queries) SearchEntitiesByName(ctx context.Context, arg SearchEntitiesByNameParams) ([]*Entity, error) {
	rows, err := q.db.Query(ctx, searchEntitiesByName, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.Uuid,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
			&i.Hidden,
			&i.AccrualMethod,
			&i.FyStartMonth,
			&i.Address,
			&i.Picture,
			&i.Settings,
			&i.Metadata,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSequenceNumber = `-- name: SetSequenceNumber :one
UPDATE
  entitystate
SET
  sequence = $1::BIGINT,
  updated_at = NOW()
WHERE
  entity_id = $2::UUID
  AND KEY = $3::VARCHAR(10)
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND (
    $4::SMALLINT IS NULL
    OR fiscal_year = $4::SMALLINT
  )
RETURNING
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
`

type SetSequenceNumberParams struct {
	Sequence   int64     `json:"sequence"`
	EntityID   uuid.UUID `json:"entity_id"`
	Key        string    `json:"key"`
	FiscalYear *int16    `json:"fiscal_year"`
}

func (q *Queries) SetSequenceNumber(ctx context.Context, arg SetSequenceNumberParams) (*Entitystate, error) {
	row := q.db.QueryRow(ctx, setSequenceNumber,
		arg.Sequence,
		arg.EntityID,
		arg.Key,
		arg.FiscalYear,
	)
	var i Entitystate
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.FiscalYear,
		&i.Key,
		&i.Sequence,
		&i.EntityID,
		&i.EntityUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const softDeleteEntity = `-- name: SoftDeleteEntity :exec
UPDATE
  entities
SET
  deleted_at = NOW(),
  updated_at = NOW()
WHERE
  uuid = $1
  AND tenant_id = current_tenant_id()
`

func (q *Queries) SoftDeleteEntity(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteEntity, argUuid)
	return err
}

const softDeleteEntityState = `-- name: SoftDeleteEntityState :exec
UPDATE
  entitystate
SET
  deleted_at = NOW(),
  updated_at = NOW()
WHERE
  uuid = $1::UUID
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteEntityState(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteEntityState, argUuid)
	return err
}

const updateEntity = `-- name: UpdateEntity :one
UPDATE
  entities
SET
  name = COALESCE($2, name),
  code = COALESCE($3, code),
  TYPE = COALESCE($4, TYPE),
  is_active = COALESCE($5, is_active),
  hidden = COALESCE($6, hidden),
  accrual_method = COALESCE($7, accrual_method),
  fy_start_month = COALESCE($8, fy_start_month),
  address = COALESCE($9, address),
  picture = COALESCE($10, picture),
  settings = COALESCE($11, settings),
  updated_at = NOW()
WHERE
  uuid = $1
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
RETURNING
  uuid, tenant_id, parent_id, name, code, type, is_active, hidden, accrual_method, fy_start_month, address, picture, settings, metadata, version, last_validation_run, validation_status, validation_errors, created_at, updated_at, deleted_at
`

type UpdateEntityParams struct {
	Uuid          uuid.UUID `json:"uuid"`
	Name          string    `json:"name"`
	Code          *string   `json:"code"`
	Type          string    `json:"type"`
	IsActive      bool      `json:"is_active"`
	Hidden        bool      `json:"hidden"`
	AccrualMethod bool      `json:"accrual_method"`
	FyStartMonth  int32     `json:"fy_start_month"`
	Address       []byte    `json:"address"`
	Picture       *string   `json:"picture"`
	Settings      []byte    `json:"settings"`
}

func (q *Queries) UpdateEntity(ctx context.Context, arg UpdateEntityParams) (*Entity, error) {
	row := q.db.QueryRow(ctx, updateEntity,
		arg.Uuid,
		arg.Name,
		arg.Code,
		arg.Type,
		arg.IsActive,
		arg.Hidden,
		arg.AccrualMethod,
		arg.FyStartMonth,
		arg.Address,
		arg.Picture,
		arg.Settings,
	)
	var i Entity
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.IsActive,
		&i.Hidden,
		&i.AccrualMethod,
		&i.FyStartMonth,
		&i.Address,
		&i.Picture,
		&i.Settings,
		&i.Metadata,
		&i.Version,
		&i.LastValidationRun,
		&i.ValidationStatus,
		&i.ValidationErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateEntityState = `-- name: UpdateEntityState :one
UPDATE
  entitystate
SET
  fiscal_year = COALESCE($1::SMALLINT, fiscal_year),
  KEY = COALESCE($2::VARCHAR(10), KEY),
  sequence = COALESCE($3::BIGINT, sequence),
  entity_id = COALESCE($4::UUID, entity_id),
  entity_unit_id = COALESCE($5::UUID, entity_unit_id),
  updated_at = NOW()
WHERE
  uuid = $6::UUID
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
RETURNING
  uuid, tenant_id, fiscal_year, key, sequence, entity_id, entity_unit_id, created_at, updated_at, deleted_at
`

type UpdateEntityStateParams struct {
	FiscalYear   *int16     `json:"fiscal_year"`
	Key          *string    `json:"key"`
	Sequence     *int64     `json:"sequence"`
	EntityID     *uuid.UUID `json:"entity_id"`
	EntityUnitID *uuid.UUID `json:"entity_unit_id"`
	Uuid         uuid.UUID  `json:"uuid"`
}

func (q *Queries) UpdateEntityState(ctx context.Context, arg UpdateEntityStateParams) (*Entitystate, error) {
	row := q.db.QueryRow(ctx, updateEntityState,
		arg.FiscalYear,
		arg.Key,
		arg.Sequence,
		arg.EntityID,
		arg.EntityUnitID,
		arg.Uuid,
	)
	var i Entitystate
	err := row.Scan(
		&i.Uuid,
		&i.TenantID,
		&i.FiscalYear,
		&i.Key,
		&i.Sequence,
		&i.EntityID,
		&i.EntityUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateHierarchyPaths = `-- name: UpdateHierarchyPaths :exec
WITH RECURSIVE hierarchy_cte AS (
  -- Base case: self-reference
  SELECT
    current_tenant_id() AS tenant_id,
    $1::UUID AS ancestor_id,
    $1::UUID AS descendant_id,
    0 AS depth
  UNION
  ALL
  -- Recursive case: add ancestors
  SELECT
    h.tenant_id,
    hp.ancestor_id,
    h.descendant_id,
    h.depth + 1
  FROM
    hierarchy_cte h
    JOIN hierarchy_paths hp ON hp.descendant_id = h.ancestor_id
    AND hp.tenant_id = h.tenant_id
  WHERE
    h.depth < 5 -- Prevent infinite recursion
)
INSERT INTO
  hierarchy_paths (tenant_id, ancestor_id, descendant_id, depth)
SELECT
  DISTINCT tenant_id,
  ancestor_id,
  descendant_id,
  depth
FROM
  hierarchy_cte ON CONFLICT (tenant_id, ancestor_id, descendant_id) DO NOTHING
`

func (q *Queries) UpdateHierarchyPaths(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateHierarchyPaths, dollar_1)
	return err
}

const validateEntityCode = `-- name: ValidateEntityCode :one
SELECT
  EXISTS(
    SELECT
      1
    FROM
      entities
    WHERE
      code = $1
      AND tenant_id = current_tenant_id()
      AND uuid != $2
      AND deleted_at IS NULL
  )::BOOLEAN AS EXISTS
`

type ValidateEntityCodeParams struct {
	Code *string   `json:"code"`
	Uuid uuid.UUID `json:"uuid"`
}

// =====================================================================
// 1. ENTITY VALIDATION AND INTEGRITY CHECKS
// =====================================================================
func (q *Queries) ValidateEntityCode(ctx context.Context, arg ValidateEntityCodeParams) (bool, error) {
	row := q.db.QueryRow(ctx, validateEntityCode, arg.Code, arg.Uuid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const validateEntityHierarchy = `-- name: ValidateEntityHierarchy :one
SELECT
  CASE
    WHEN COUNT(*) = 0 THEN TRUE
    ELSE false
  END AS is_valid
FROM
  hierarchy_paths hp1
  JOIN hierarchy_paths hp2 ON hp1.descendant_id = hp2.ancestor_id
WHERE
  hp1.ancestor_id = hp2.descendant_id
  AND hp1.depth > 0
  AND hp2.depth > 0
`

func (q *Queries) ValidateEntityHierarchy(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, validateEntityHierarchy)
	var is_valid bool
	err := row.Scan(&is_valid)
	return is_valid, err
}

const validateEntityName = `-- name: ValidateEntityName :one
SELECT
  EXISTS(
    SELECT
      1
    FROM
      entities
    WHERE
      name = $1
      AND tenant_id = current_tenant_id()
      AND uuid != $2
      AND deleted_at IS NULL
  ) AS EXISTS
`

type ValidateEntityNameParams struct {
	Name string    `json:"name"`
	Uuid uuid.UUID `json:"uuid"`
}

func (q *Queries) ValidateEntityName(ctx context.Context, arg ValidateEntityNameParams) (bool, error) {
	row := q.db.QueryRow(ctx, validateEntityName, arg.Name, arg.Uuid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const validateEntityParent = `-- name: ValidateEntityParent :one
SELECT
  (
    CASE
      WHEN $1 IS NULL THEN TRUE
      WHEN NOT EXISTS(
        SELECT
          1
        FROM
          entities
        WHERE
          uuid = $1
          AND tenant_id = current_tenant_id()
          AND deleted_at IS NULL
      ) THEN false
      WHEN EXISTS(
        SELECT
          1
        FROM
          hierarchy_paths
        WHERE
          tenant_id = current_tenant_id()
          AND ancestor_id = $2
          AND descendant_id = $1
      ) THEN false
      ELSE TRUE
    END
  )::BOOLEAN AS valid
`

type ValidateEntityParentParams struct {
	Column1    bool      `json:"column_1"`
	AncestorID uuid.UUID `json:"ancestor_id"`
}

func (q *Queries) ValidateEntityParent(ctx context.Context, arg ValidateEntityParentParams) (bool, error) {
	row := q.db.QueryRow(ctx, validateEntityParent, arg.Column1, arg.AncestorID)
	var valid bool
	err := row.Scan(&valid)
	return valid, err
}
