// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: finance_accounts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) 
FROM finance_accounts
WHERE tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND ($1::uuid IS NULL OR entity_id = $1::uuid)
  AND ($2::account_type_enum IS NULL OR account_type = $2::account_type_enum)
  AND ($3::root_type_enum IS NULL OR root_type = $3::root_type_enum)
  AND ($4::bool IS NULL OR is_active = $4::bool)
`

type CountAccountsParams struct {
	EntityID    *uuid.UUID  `json:"entity_id"`
	AccountType interface{} `json:"account_type"`
	RootType    interface{} `json:"root_type"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) CountAccounts(ctx context.Context, arg CountAccountsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts,
		arg.EntityID,
		arg.AccountType,
		arg.RootType,
		arg.IsActive,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one

INSERT INTO finance_accounts (
    tenant_id,
    entity_id,
    account_code,
    account_name,
    account_description,
    account_group_id,
    account_header_id,
    parent_account_id,
    account_level,
    account_path,
    account_category,
    sub_category,
    display_order,
    show_in_reports,
    consolidation_account,
    cash_flow_type,
    root_type,
    account_type,
    account_subtype,
    normal_balance,
    is_control_account,
    control_account_id,
    currency_code,
    is_multi_currency,
    currency_revaluation_required,
    is_active,
    is_system_account,
    allow_manual_entries,
    require_reference,
    current_balance,
    ytd_balance,
    last_transaction_date,
    financial_statement_line,
    report_order,
    is_budgetable,
    budget_variance_threshold,
    version,
    last_validation_run,
    validation_status,
    validation_errors,
    account_attributes,
    has_children,
    is_leaf_account,
    created_by
) VALUES (
    current_tenant_id(),
    $1, 
    $2, 
    $3, 
    $4, 
    $5,
    $6,
    $7, 
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16, 
    $17, 
    $18, 
    $19, 
    $20, 
    $21, 
    $22, 
    $23, 
    $24, 
    $25, 
    $26, 
    $27, 
    $28, 
    $29,
    $30,
    $31,
    $32, 
    $33, 
    $34, 
    $35, 
    $36,
    $37,
    $38,
    $39,
    $40, 
    $41,
    $42,
    $43
) RETURNING id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account
`

type CreateAccountParams struct {
	EntityID                    *uuid.UUID     `json:"entity_id"`
	AccountCode                 string         `json:"account_code"`
	AccountName                 string         `json:"account_name"`
	AccountDescription          string         `json:"account_description"`
	AccountGroupID              *uuid.UUID     `json:"account_group_id"`
	AccountHeaderID             *uuid.UUID     `json:"account_header_id"`
	ParentAccountID             *uuid.UUID     `json:"parent_account_id"`
	AccountLevel                *int32         `json:"account_level"`
	AccountPath                 *string        `json:"account_path"`
	AccountCategory             *string        `json:"account_category"`
	SubCategory                 *string        `json:"sub_category"`
	DisplayOrder                *int32         `json:"display_order"`
	ShowInReports               *bool          `json:"show_in_reports"`
	ConsolidationAccount        *string        `json:"consolidation_account"`
	CashFlowType                *string        `json:"cash_flow_type"`
	RootType                    string         `json:"root_type"`
	AccountType                 string         `json:"account_type"`
	AccountSubtype              *string        `json:"account_subtype"`
	NormalBalance               string         `json:"normal_balance"`
	IsControlAccount            *bool          `json:"is_control_account"`
	ControlAccountID            *uuid.UUID     `json:"control_account_id"`
	CurrencyCode                *string        `json:"currency_code"`
	IsMultiCurrency             *bool          `json:"is_multi_currency"`
	CurrencyRevaluationRequired *bool          `json:"currency_revaluation_required"`
	IsActive                    *bool          `json:"is_active"`
	IsSystemAccount             *bool          `json:"is_system_account"`
	AllowManualEntries          *bool          `json:"allow_manual_entries"`
	RequireReference            *bool          `json:"require_reference"`
	CurrentBalance              pgtype.Numeric `json:"current_balance"`
	YtdBalance                  pgtype.Numeric `json:"ytd_balance"`
	LastTransactionDate         time.Time      `json:"last_transaction_date"`
	FinancialStatementLine      *string        `json:"financial_statement_line"`
	ReportOrder                 *int32         `json:"report_order"`
	IsBudgetable                *bool          `json:"is_budgetable"`
	BudgetVarianceThreshold     pgtype.Numeric `json:"budget_variance_threshold"`
	Version                     *int32         `json:"version"`
	LastValidationRun           sql.NullTime   `json:"last_validation_run"`
	ValidationStatus            *string        `json:"validation_status"`
	ValidationErrors            []byte         `json:"validation_errors"`
	AccountAttributes           []byte         `json:"account_attributes"`
	HasChildren                 *bool          `json:"has_children"`
	IsLeafAccount               *bool          `json:"is_leaf_account"`
	CreatedBy                   *uuid.UUID     `json:"created_by"`
}

// =====================================================================
// FINANCE MODULE - CHART OF ACCOUNTS QUERIES
// SQLC queries for chart of accounts with proper tenant isolation
// Updated with proper sqlc.narg and sqlc.arg usage
// =====================================================================
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (*FinanceAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.EntityID,
		arg.AccountCode,
		arg.AccountName,
		arg.AccountDescription,
		arg.AccountGroupID,
		arg.AccountHeaderID,
		arg.ParentAccountID,
		arg.AccountLevel,
		arg.AccountPath,
		arg.AccountCategory,
		arg.SubCategory,
		arg.DisplayOrder,
		arg.ShowInReports,
		arg.ConsolidationAccount,
		arg.CashFlowType,
		arg.RootType,
		arg.AccountType,
		arg.AccountSubtype,
		arg.NormalBalance,
		arg.IsControlAccount,
		arg.ControlAccountID,
		arg.CurrencyCode,
		arg.IsMultiCurrency,
		arg.CurrencyRevaluationRequired,
		arg.IsActive,
		arg.IsSystemAccount,
		arg.AllowManualEntries,
		arg.RequireReference,
		arg.CurrentBalance,
		arg.YtdBalance,
		arg.LastTransactionDate,
		arg.FinancialStatementLine,
		arg.ReportOrder,
		arg.IsBudgetable,
		arg.BudgetVarianceThreshold,
		arg.Version,
		arg.LastValidationRun,
		arg.ValidationStatus,
		arg.ValidationErrors,
		arg.AccountAttributes,
		arg.HasChildren,
		arg.IsLeafAccount,
		arg.CreatedBy,
	)
	var i FinanceAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityID,
		&i.AccountCode,
		&i.AccountName,
		&i.AccountDescription,
		&i.AccountGroupID,
		&i.AccountHeaderID,
		&i.ParentAccountID,
		&i.AccountLevel,
		&i.AccountPath,
		&i.AccountCategory,
		&i.SubCategory,
		&i.DisplayOrder,
		&i.ShowInReports,
		&i.ConsolidationAccount,
		&i.CashFlowType,
		&i.RootType,
		&i.AccountType,
		&i.AccountSubtype,
		&i.NormalBalance,
		&i.IsControlAccount,
		&i.ControlAccountID,
		&i.CurrencyCode,
		&i.IsMultiCurrency,
		&i.CurrencyRevaluationRequired,
		&i.IsActive,
		&i.IsSystemAccount,
		&i.AllowManualEntries,
		&i.RequireReference,
		&i.CurrentBalance,
		&i.YtdBalance,
		&i.LastTransactionDate,
		&i.FinancialStatementLine,
		&i.ReportOrder,
		&i.IsBudgetable,
		&i.BudgetVarianceThreshold,
		&i.Version,
		&i.LastValidationRun,
		&i.ValidationStatus,
		&i.ValidationErrors,
		&i.AccountAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.HasChildren,
		&i.IsLeafAccount,
	)
	return &i, err
}

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account FROM finance_accounts
WHERE account_code = $1 
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

func (q *Queries) GetAccountByCode(ctx context.Context, accountCode string) (*FinanceAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByCode, accountCode)
	var i FinanceAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityID,
		&i.AccountCode,
		&i.AccountName,
		&i.AccountDescription,
		&i.AccountGroupID,
		&i.AccountHeaderID,
		&i.ParentAccountID,
		&i.AccountLevel,
		&i.AccountPath,
		&i.AccountCategory,
		&i.SubCategory,
		&i.DisplayOrder,
		&i.ShowInReports,
		&i.ConsolidationAccount,
		&i.CashFlowType,
		&i.RootType,
		&i.AccountType,
		&i.AccountSubtype,
		&i.NormalBalance,
		&i.IsControlAccount,
		&i.ControlAccountID,
		&i.CurrencyCode,
		&i.IsMultiCurrency,
		&i.CurrencyRevaluationRequired,
		&i.IsActive,
		&i.IsSystemAccount,
		&i.AllowManualEntries,
		&i.RequireReference,
		&i.CurrentBalance,
		&i.YtdBalance,
		&i.LastTransactionDate,
		&i.FinancialStatementLine,
		&i.ReportOrder,
		&i.IsBudgetable,
		&i.BudgetVarianceThreshold,
		&i.Version,
		&i.LastValidationRun,
		&i.ValidationStatus,
		&i.ValidationErrors,
		&i.AccountAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.HasChildren,
		&i.IsLeafAccount,
	)
	return &i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account FROM finance_accounts
WHERE id = $1 
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, accountID uuid.UUID) (*FinanceAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, accountID)
	var i FinanceAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityID,
		&i.AccountCode,
		&i.AccountName,
		&i.AccountDescription,
		&i.AccountGroupID,
		&i.AccountHeaderID,
		&i.ParentAccountID,
		&i.AccountLevel,
		&i.AccountPath,
		&i.AccountCategory,
		&i.SubCategory,
		&i.DisplayOrder,
		&i.ShowInReports,
		&i.ConsolidationAccount,
		&i.CashFlowType,
		&i.RootType,
		&i.AccountType,
		&i.AccountSubtype,
		&i.NormalBalance,
		&i.IsControlAccount,
		&i.ControlAccountID,
		&i.CurrencyCode,
		&i.IsMultiCurrency,
		&i.CurrencyRevaluationRequired,
		&i.IsActive,
		&i.IsSystemAccount,
		&i.AllowManualEntries,
		&i.RequireReference,
		&i.CurrentBalance,
		&i.YtdBalance,
		&i.LastTransactionDate,
		&i.FinancialStatementLine,
		&i.ReportOrder,
		&i.IsBudgetable,
		&i.BudgetVarianceThreshold,
		&i.Version,
		&i.LastValidationRun,
		&i.ValidationStatus,
		&i.ValidationErrors,
		&i.AccountAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.HasChildren,
		&i.IsLeafAccount,
	)
	return &i, err
}

const getAccountHierarchy = `-- name: GetAccountHierarchy :many
SELECT id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account FROM finance_accounts
WHERE tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND account_path LIKE $1 || '%'
ORDER BY account_path ASC
`

func (q *Queries) GetAccountHierarchy(ctx context.Context, accountPathPrefix string) ([]*FinanceAccount, error) {
	rows, err := q.db.Query(ctx, getAccountHierarchy, accountPathPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FinanceAccount{}
	for rows.Next() {
		var i FinanceAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityID,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountDescription,
			&i.AccountGroupID,
			&i.AccountHeaderID,
			&i.ParentAccountID,
			&i.AccountLevel,
			&i.AccountPath,
			&i.AccountCategory,
			&i.SubCategory,
			&i.DisplayOrder,
			&i.ShowInReports,
			&i.ConsolidationAccount,
			&i.CashFlowType,
			&i.RootType,
			&i.AccountType,
			&i.AccountSubtype,
			&i.NormalBalance,
			&i.IsControlAccount,
			&i.ControlAccountID,
			&i.CurrencyCode,
			&i.IsMultiCurrency,
			&i.CurrencyRevaluationRequired,
			&i.IsActive,
			&i.IsSystemAccount,
			&i.AllowManualEntries,
			&i.RequireReference,
			&i.CurrentBalance,
			&i.YtdBalance,
			&i.LastTransactionDate,
			&i.FinancialStatementLine,
			&i.ReportOrder,
			&i.IsBudgetable,
			&i.BudgetVarianceThreshold,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.AccountAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.HasChildren,
			&i.IsLeafAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountsByEntity = `-- name: GetAccountsByEntity :many
SELECT id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account FROM finance_accounts
WHERE entity_id = $1
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
ORDER BY account_code ASC
`

func (q *Queries) GetAccountsByEntity(ctx context.Context, entityID *uuid.UUID) ([]*FinanceAccount, error) {
	rows, err := q.db.Query(ctx, getAccountsByEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FinanceAccount{}
	for rows.Next() {
		var i FinanceAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityID,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountDescription,
			&i.AccountGroupID,
			&i.AccountHeaderID,
			&i.ParentAccountID,
			&i.AccountLevel,
			&i.AccountPath,
			&i.AccountCategory,
			&i.SubCategory,
			&i.DisplayOrder,
			&i.ShowInReports,
			&i.ConsolidationAccount,
			&i.CashFlowType,
			&i.RootType,
			&i.AccountType,
			&i.AccountSubtype,
			&i.NormalBalance,
			&i.IsControlAccount,
			&i.ControlAccountID,
			&i.CurrencyCode,
			&i.IsMultiCurrency,
			&i.CurrencyRevaluationRequired,
			&i.IsActive,
			&i.IsSystemAccount,
			&i.AllowManualEntries,
			&i.RequireReference,
			&i.CurrentBalance,
			&i.YtdBalance,
			&i.LastTransactionDate,
			&i.FinancialStatementLine,
			&i.ReportOrder,
			&i.IsBudgetable,
			&i.BudgetVarianceThreshold,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.AccountAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.HasChildren,
			&i.IsLeafAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountsForFinancialStatements = `-- name: GetAccountsForFinancialStatements :many
SELECT 
    a.id, a.tenant_id, a.entity_id, a.account_code, a.account_name, a.account_description, a.account_group_id, a.account_header_id, a.parent_account_id, a.account_level, a.account_path, a.account_category, a.sub_category, a.display_order, a.show_in_reports, a.consolidation_account, a.cash_flow_type, a.root_type, a.account_type, a.account_subtype, a.normal_balance, a.is_control_account, a.control_account_id, a.currency_code, a.is_multi_currency, a.currency_revaluation_required, a.is_active, a.is_system_account, a.allow_manual_entries, a.require_reference, a.current_balance, a.ytd_balance, a.last_transaction_date, a.financial_statement_line, a.report_order, a.is_budgetable, a.budget_variance_threshold, a.version, a.last_validation_run, a.validation_status, a.validation_errors, a.account_attributes, a.created_at, a.updated_at, a.deleted_at, a.created_by, a.updated_by, a.has_children, a.is_leaf_account,
    COALESCE(SUM(CASE WHEN te.debit_amount > 0 THEN te.debit_amount ELSE -te.credit_amount END), 0) as calculated_balance
FROM finance_accounts a
LEFT JOIN finance_transaction_entries te ON a.id = te.account_id
LEFT JOIN finance_transactions t ON te.transaction_id = t.id
WHERE a.tenant_id = current_tenant_id()
  AND a.deleted_at IS NULL
  AND a.is_active = true
  AND ($1::uuid IS NULL OR a.entity_id = $1::uuid)
  AND ($2::text IS NULL OR a.financial_statement_line = $2)
  AND (t.transaction_status = 'POSTED' OR t.id IS NULL)
  AND (t.posting_date <= $3 OR t.posting_date IS NULL)
GROUP BY a.id
ORDER BY a.report_order ASC, a.account_code ASC
`

type GetAccountsForFinancialStatementsParams struct {
	EntityID               *uuid.UUID `json:"entity_id"`
	FinancialStatementLine string     `json:"financial_statement_line"`
	PostingDate            time.Time  `json:"posting_date"`
}

type GetAccountsForFinancialStatementsRow struct {
	ID                          uuid.UUID      `json:"id"`
	TenantID                    uuid.UUID      `json:"tenant_id"`
	EntityID                    *uuid.UUID     `json:"entity_id"`
	AccountCode                 string         `json:"account_code"`
	AccountName                 string         `json:"account_name"`
	AccountDescription          string         `json:"account_description"`
	AccountGroupID              *uuid.UUID     `json:"account_group_id"`
	AccountHeaderID             *uuid.UUID     `json:"account_header_id"`
	ParentAccountID             *uuid.UUID     `json:"parent_account_id"`
	AccountLevel                int32          `json:"account_level"`
	AccountPath                 *string        `json:"account_path"`
	AccountCategory             *string        `json:"account_category"`
	SubCategory                 *string        `json:"sub_category"`
	DisplayOrder                *int32         `json:"display_order"`
	ShowInReports               *bool          `json:"show_in_reports"`
	ConsolidationAccount        *string        `json:"consolidation_account"`
	CashFlowType                *string        `json:"cash_flow_type"`
	RootType                    string         `json:"root_type"`
	AccountType                 string         `json:"account_type"`
	AccountSubtype              *string        `json:"account_subtype"`
	NormalBalance               string         `json:"normal_balance"`
	IsControlAccount            bool           `json:"is_control_account"`
	ControlAccountID            *uuid.UUID     `json:"control_account_id"`
	CurrencyCode                *string        `json:"currency_code"`
	IsMultiCurrency             *bool          `json:"is_multi_currency"`
	CurrencyRevaluationRequired *bool          `json:"currency_revaluation_required"`
	IsActive                    bool           `json:"is_active"`
	IsSystemAccount             bool           `json:"is_system_account"`
	AllowManualEntries          bool           `json:"allow_manual_entries"`
	RequireReference            bool           `json:"require_reference"`
	CurrentBalance              pgtype.Numeric `json:"current_balance"`
	YtdBalance                  pgtype.Numeric `json:"ytd_balance"`
	LastTransactionDate         time.Time      `json:"last_transaction_date"`
	FinancialStatementLine      *string        `json:"financial_statement_line"`
	ReportOrder                 *int32         `json:"report_order"`
	IsBudgetable                *bool          `json:"is_budgetable"`
	BudgetVarianceThreshold     pgtype.Numeric `json:"budget_variance_threshold"`
	Version                     int32          `json:"version"`
	LastValidationRun           sql.NullTime   `json:"last_validation_run"`
	ValidationStatus            *string        `json:"validation_status"`
	ValidationErrors            []byte         `json:"validation_errors"`
	AccountAttributes           []byte         `json:"account_attributes"`
	CreatedAt                   time.Time      `json:"created_at"`
	UpdatedAt                   time.Time      `json:"updated_at"`
	DeletedAt                   sql.NullTime   `json:"deleted_at"`
	CreatedBy                   *uuid.UUID     `json:"created_by"`
	UpdatedBy                   *uuid.UUID     `json:"updated_by"`
	HasChildren                 *bool          `json:"has_children"`
	IsLeafAccount               *bool          `json:"is_leaf_account"`
	CalculatedBalance           interface{}    `json:"calculated_balance"`
}

func (q *Queries) GetAccountsForFinancialStatements(ctx context.Context, arg GetAccountsForFinancialStatementsParams) ([]*GetAccountsForFinancialStatementsRow, error) {
	rows, err := q.db.Query(ctx, getAccountsForFinancialStatements, arg.EntityID, arg.FinancialStatementLine, arg.PostingDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAccountsForFinancialStatementsRow{}
	for rows.Next() {
		var i GetAccountsForFinancialStatementsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityID,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountDescription,
			&i.AccountGroupID,
			&i.AccountHeaderID,
			&i.ParentAccountID,
			&i.AccountLevel,
			&i.AccountPath,
			&i.AccountCategory,
			&i.SubCategory,
			&i.DisplayOrder,
			&i.ShowInReports,
			&i.ConsolidationAccount,
			&i.CashFlowType,
			&i.RootType,
			&i.AccountType,
			&i.AccountSubtype,
			&i.NormalBalance,
			&i.IsControlAccount,
			&i.ControlAccountID,
			&i.CurrencyCode,
			&i.IsMultiCurrency,
			&i.CurrencyRevaluationRequired,
			&i.IsActive,
			&i.IsSystemAccount,
			&i.AllowManualEntries,
			&i.RequireReference,
			&i.CurrentBalance,
			&i.YtdBalance,
			&i.LastTransactionDate,
			&i.FinancialStatementLine,
			&i.ReportOrder,
			&i.IsBudgetable,
			&i.BudgetVarianceThreshold,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.AccountAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.HasChildren,
			&i.IsLeafAccount,
			&i.CalculatedBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountsWithNonZeroBalance = `-- name: GetAccountsWithNonZeroBalance :many
SELECT id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account FROM finance_accounts
WHERE tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND ($1::uuid IS NULL OR entity_id = $1::uuid)
  AND current_balance != 0
ORDER BY ABS(current_balance) DESC
`

func (q *Queries) GetAccountsWithNonZeroBalance(ctx context.Context, entityID *uuid.UUID) ([]*FinanceAccount, error) {
	rows, err := q.db.Query(ctx, getAccountsWithNonZeroBalance, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FinanceAccount{}
	for rows.Next() {
		var i FinanceAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityID,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountDescription,
			&i.AccountGroupID,
			&i.AccountHeaderID,
			&i.ParentAccountID,
			&i.AccountLevel,
			&i.AccountPath,
			&i.AccountCategory,
			&i.SubCategory,
			&i.DisplayOrder,
			&i.ShowInReports,
			&i.ConsolidationAccount,
			&i.CashFlowType,
			&i.RootType,
			&i.AccountType,
			&i.AccountSubtype,
			&i.NormalBalance,
			&i.IsControlAccount,
			&i.ControlAccountID,
			&i.CurrencyCode,
			&i.IsMultiCurrency,
			&i.CurrencyRevaluationRequired,
			&i.IsActive,
			&i.IsSystemAccount,
			&i.AllowManualEntries,
			&i.RequireReference,
			&i.CurrentBalance,
			&i.YtdBalance,
			&i.LastTransactionDate,
			&i.FinancialStatementLine,
			&i.ReportOrder,
			&i.IsBudgetable,
			&i.BudgetVarianceThreshold,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.AccountAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.HasChildren,
			&i.IsLeafAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getControlAccounts = `-- name: GetControlAccounts :many
SELECT id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account FROM finance_accounts
WHERE tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND ($1::uuid IS NULL OR entity_id = $1::uuid)
  AND is_control_account = true
ORDER BY account_code ASC
`

func (q *Queries) GetControlAccounts(ctx context.Context, entityID *uuid.UUID) ([]*FinanceAccount, error) {
	rows, err := q.db.Query(ctx, getControlAccounts, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FinanceAccount{}
	for rows.Next() {
		var i FinanceAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityID,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountDescription,
			&i.AccountGroupID,
			&i.AccountHeaderID,
			&i.ParentAccountID,
			&i.AccountLevel,
			&i.AccountPath,
			&i.AccountCategory,
			&i.SubCategory,
			&i.DisplayOrder,
			&i.ShowInReports,
			&i.ConsolidationAccount,
			&i.CashFlowType,
			&i.RootType,
			&i.AccountType,
			&i.AccountSubtype,
			&i.NormalBalance,
			&i.IsControlAccount,
			&i.ControlAccountID,
			&i.CurrencyCode,
			&i.IsMultiCurrency,
			&i.CurrencyRevaluationRequired,
			&i.IsActive,
			&i.IsSystemAccount,
			&i.AllowManualEntries,
			&i.RequireReference,
			&i.CurrentBalance,
			&i.YtdBalance,
			&i.LastTransactionDate,
			&i.FinancialStatementLine,
			&i.ReportOrder,
			&i.IsBudgetable,
			&i.BudgetVarianceThreshold,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.AccountAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.HasChildren,
			&i.IsLeafAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootAccounts = `-- name: GetRootAccounts :many
SELECT id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account FROM finance_accounts
WHERE parent_account_id IS NULL
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
ORDER BY account_code ASC
`

func (q *Queries) GetRootAccounts(ctx context.Context) ([]*FinanceAccount, error) {
	rows, err := q.db.Query(ctx, getRootAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FinanceAccount{}
	for rows.Next() {
		var i FinanceAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityID,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountDescription,
			&i.AccountGroupID,
			&i.AccountHeaderID,
			&i.ParentAccountID,
			&i.AccountLevel,
			&i.AccountPath,
			&i.AccountCategory,
			&i.SubCategory,
			&i.DisplayOrder,
			&i.ShowInReports,
			&i.ConsolidationAccount,
			&i.CashFlowType,
			&i.RootType,
			&i.AccountType,
			&i.AccountSubtype,
			&i.NormalBalance,
			&i.IsControlAccount,
			&i.ControlAccountID,
			&i.CurrencyCode,
			&i.IsMultiCurrency,
			&i.CurrencyRevaluationRequired,
			&i.IsActive,
			&i.IsSystemAccount,
			&i.AllowManualEntries,
			&i.RequireReference,
			&i.CurrentBalance,
			&i.YtdBalance,
			&i.LastTransactionDate,
			&i.FinancialStatementLine,
			&i.ReportOrder,
			&i.IsBudgetable,
			&i.BudgetVarianceThreshold,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.AccountAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.HasChildren,
			&i.IsLeafAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account 
FROM finance_accounts
WHERE tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND ($1::uuid IS NULL OR entity_id = $1::uuid)
  AND ($2::account_type_enum IS NULL OR account_type = $2::account_type_enum)
  AND ($3::root_type_enum IS NULL OR root_type = $3::root_type_enum)
  AND ($4::bool IS NULL OR is_active = $4::bool)
ORDER BY account_code ASC
LIMIT $6 OFFSET $5
`

type ListAccountsParams struct {
	EntityID    *uuid.UUID  `json:"entity_id"`
	AccountType interface{} `json:"account_type"`
	RootType    interface{} `json:"root_type"`
	IsActive    bool        `json:"is_active"`
	Offset      int32       `json:"offset"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]*FinanceAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.EntityID,
		arg.AccountType,
		arg.RootType,
		arg.IsActive,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FinanceAccount{}
	for rows.Next() {
		var i FinanceAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityID,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountDescription,
			&i.AccountGroupID,
			&i.AccountHeaderID,
			&i.ParentAccountID,
			&i.AccountLevel,
			&i.AccountPath,
			&i.AccountCategory,
			&i.SubCategory,
			&i.DisplayOrder,
			&i.ShowInReports,
			&i.ConsolidationAccount,
			&i.CashFlowType,
			&i.RootType,
			&i.AccountType,
			&i.AccountSubtype,
			&i.NormalBalance,
			&i.IsControlAccount,
			&i.ControlAccountID,
			&i.CurrencyCode,
			&i.IsMultiCurrency,
			&i.CurrencyRevaluationRequired,
			&i.IsActive,
			&i.IsSystemAccount,
			&i.AllowManualEntries,
			&i.RequireReference,
			&i.CurrentBalance,
			&i.YtdBalance,
			&i.LastTransactionDate,
			&i.FinancialStatementLine,
			&i.ReportOrder,
			&i.IsBudgetable,
			&i.BudgetVarianceThreshold,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.AccountAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.HasChildren,
			&i.IsLeafAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByParent = `-- name: ListAccountsByParent :many
SELECT id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account FROM finance_accounts
WHERE parent_account_id = $1
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
ORDER BY account_code ASC
`

func (q *Queries) ListAccountsByParent(ctx context.Context, parentAccountID *uuid.UUID) ([]*FinanceAccount, error) {
	rows, err := q.db.Query(ctx, listAccountsByParent, parentAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FinanceAccount{}
	for rows.Next() {
		var i FinanceAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityID,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountDescription,
			&i.AccountGroupID,
			&i.AccountHeaderID,
			&i.ParentAccountID,
			&i.AccountLevel,
			&i.AccountPath,
			&i.AccountCategory,
			&i.SubCategory,
			&i.DisplayOrder,
			&i.ShowInReports,
			&i.ConsolidationAccount,
			&i.CashFlowType,
			&i.RootType,
			&i.AccountType,
			&i.AccountSubtype,
			&i.NormalBalance,
			&i.IsControlAccount,
			&i.ControlAccountID,
			&i.CurrencyCode,
			&i.IsMultiCurrency,
			&i.CurrencyRevaluationRequired,
			&i.IsActive,
			&i.IsSystemAccount,
			&i.AllowManualEntries,
			&i.RequireReference,
			&i.CurrentBalance,
			&i.YtdBalance,
			&i.LastTransactionDate,
			&i.FinancialStatementLine,
			&i.ReportOrder,
			&i.IsBudgetable,
			&i.BudgetVarianceThreshold,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.AccountAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.HasChildren,
			&i.IsLeafAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAccount = `-- name: RestoreAccount :exec
UPDATE finance_accounts
SET 
    deleted_at = NULL,
    updated_at = NOW(),
    updated_by = $1
WHERE id = $2 
  AND tenant_id = current_tenant_id()
`

type RestoreAccountParams struct {
	UpdatedBy *uuid.UUID `json:"updated_by"`
	AccountID uuid.UUID  `json:"account_id"`
}

func (q *Queries) RestoreAccount(ctx context.Context, arg RestoreAccountParams) error {
	_, err := q.db.Exec(ctx, restoreAccount, arg.UpdatedBy, arg.AccountID)
	return err
}

const searchAccounts = `-- name: SearchAccounts :many
SELECT id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account FROM finance_accounts
WHERE tenant_id = current_tenant_id()
  AND deleted_at IS NULL
  AND ($1::uuid IS NULL OR entity_id = $1::uuid)
  AND (
    account_code ILIKE '%' || $2 || '%' OR
    account_name ILIKE '%' || $2 || '%' OR
    account_description ILIKE '%' || $2 || '%'
  )
ORDER BY 
  CASE WHEN account_code ILIKE $2 || '%' THEN 1 ELSE 2 END,
  account_code ASC
LIMIT $4 OFFSET $3
`

type SearchAccountsParams struct {
	EntityID   *uuid.UUID `json:"entity_id"`
	SearchTerm string     `json:"search_term"`
	Offset     int32      `json:"offset"`
	Limit      int32      `json:"limit"`
}

func (q *Queries) SearchAccounts(ctx context.Context, arg SearchAccountsParams) ([]*FinanceAccount, error) {
	rows, err := q.db.Query(ctx, searchAccounts,
		arg.EntityID,
		arg.SearchTerm,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FinanceAccount{}
	for rows.Next() {
		var i FinanceAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityID,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountDescription,
			&i.AccountGroupID,
			&i.AccountHeaderID,
			&i.ParentAccountID,
			&i.AccountLevel,
			&i.AccountPath,
			&i.AccountCategory,
			&i.SubCategory,
			&i.DisplayOrder,
			&i.ShowInReports,
			&i.ConsolidationAccount,
			&i.CashFlowType,
			&i.RootType,
			&i.AccountType,
			&i.AccountSubtype,
			&i.NormalBalance,
			&i.IsControlAccount,
			&i.ControlAccountID,
			&i.CurrencyCode,
			&i.IsMultiCurrency,
			&i.CurrencyRevaluationRequired,
			&i.IsActive,
			&i.IsSystemAccount,
			&i.AllowManualEntries,
			&i.RequireReference,
			&i.CurrentBalance,
			&i.YtdBalance,
			&i.LastTransactionDate,
			&i.FinancialStatementLine,
			&i.ReportOrder,
			&i.IsBudgetable,
			&i.BudgetVarianceThreshold,
			&i.Version,
			&i.LastValidationRun,
			&i.ValidationStatus,
			&i.ValidationErrors,
			&i.AccountAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.HasChildren,
			&i.IsLeafAccount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccount = `-- name: SoftDeleteAccount :exec
UPDATE finance_accounts
SET 
    deleted_at = NOW(),
    updated_at = NOW(),
    updated_by = $1
WHERE id = $2 
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

type SoftDeleteAccountParams struct {
	UpdatedBy *uuid.UUID `json:"updated_by"`
	AccountID uuid.UUID  `json:"account_id"`
}

func (q *Queries) SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) error {
	_, err := q.db.Exec(ctx, softDeleteAccount, arg.UpdatedBy, arg.AccountID)
	return err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE finance_accounts
SET 
    account_name = COALESCE($1, account_name),
    account_description = COALESCE($2, account_description),
    account_group_id = COALESCE($3, account_group_id),
    account_header_id = COALESCE($4, account_header_id),
    account_level = COALESCE($5, account_level),
    account_path = COALESCE($6, account_path),
    account_category = COALESCE($7, account_category),
    sub_category = COALESCE($8, sub_category),
    display_order = COALESCE($9, display_order),
    show_in_reports = COALESCE($10, show_in_reports),
    consolidation_account = COALESCE($11, consolidation_account),
    cash_flow_type = COALESCE($12, cash_flow_type),
    account_type = COALESCE($13, account_type),
    account_subtype = COALESCE($14, account_subtype),
    is_active = COALESCE($15, is_active),
    allow_manual_entries = COALESCE($16, allow_manual_entries),
    require_reference = COALESCE($17, require_reference),
    financial_statement_line = COALESCE($18, financial_statement_line),
    report_order = COALESCE($19, report_order),
    is_budgetable = COALESCE($20, is_budgetable),
    budget_variance_threshold = COALESCE($21, budget_variance_threshold),
    validation_status = COALESCE($22, validation_status),
    validation_errors = COALESCE($23, validation_errors),
    account_attributes = COALESCE($24, account_attributes),
    has_children = COALESCE($25, has_children),
    is_leaf_account = COALESCE($26, is_leaf_account),
    updated_at = NOW(),
    updated_by = $27
WHERE id = $28 
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
RETURNING id, tenant_id, entity_id, account_code, account_name, account_description, account_group_id, account_header_id, parent_account_id, account_level, account_path, account_category, sub_category, display_order, show_in_reports, consolidation_account, cash_flow_type, root_type, account_type, account_subtype, normal_balance, is_control_account, control_account_id, currency_code, is_multi_currency, currency_revaluation_required, is_active, is_system_account, allow_manual_entries, require_reference, current_balance, ytd_balance, last_transaction_date, financial_statement_line, report_order, is_budgetable, budget_variance_threshold, version, last_validation_run, validation_status, validation_errors, account_attributes, created_at, updated_at, deleted_at, created_by, updated_by, has_children, is_leaf_account
`

type UpdateAccountParams struct {
	AccountName             *string        `json:"account_name"`
	AccountDescription      string         `json:"account_description"`
	AccountGroupID          *uuid.UUID     `json:"account_group_id"`
	AccountHeaderID         *uuid.UUID     `json:"account_header_id"`
	AccountLevel            *int32         `json:"account_level"`
	AccountPath             *string        `json:"account_path"`
	AccountCategory         *string        `json:"account_category"`
	SubCategory             *string        `json:"sub_category"`
	DisplayOrder            *int32         `json:"display_order"`
	ShowInReports           *bool          `json:"show_in_reports"`
	ConsolidationAccount    *string        `json:"consolidation_account"`
	CashFlowType            *string        `json:"cash_flow_type"`
	AccountType             *string        `json:"account_type"`
	AccountSubtype          *string        `json:"account_subtype"`
	IsActive                *bool          `json:"is_active"`
	AllowManualEntries      *bool          `json:"allow_manual_entries"`
	RequireReference        *bool          `json:"require_reference"`
	FinancialStatementLine  *string        `json:"financial_statement_line"`
	ReportOrder             *int32         `json:"report_order"`
	IsBudgetable            *bool          `json:"is_budgetable"`
	BudgetVarianceThreshold pgtype.Numeric `json:"budget_variance_threshold"`
	ValidationStatus        *string        `json:"validation_status"`
	ValidationErrors        []byte         `json:"validation_errors"`
	AccountAttributes       []byte         `json:"account_attributes"`
	HasChildren             *bool          `json:"has_children"`
	IsLeafAccount           *bool          `json:"is_leaf_account"`
	UpdatedBy               *uuid.UUID     `json:"updated_by"`
	AccountID               uuid.UUID      `json:"account_id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (*FinanceAccount, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.AccountName,
		arg.AccountDescription,
		arg.AccountGroupID,
		arg.AccountHeaderID,
		arg.AccountLevel,
		arg.AccountPath,
		arg.AccountCategory,
		arg.SubCategory,
		arg.DisplayOrder,
		arg.ShowInReports,
		arg.ConsolidationAccount,
		arg.CashFlowType,
		arg.AccountType,
		arg.AccountSubtype,
		arg.IsActive,
		arg.AllowManualEntries,
		arg.RequireReference,
		arg.FinancialStatementLine,
		arg.ReportOrder,
		arg.IsBudgetable,
		arg.BudgetVarianceThreshold,
		arg.ValidationStatus,
		arg.ValidationErrors,
		arg.AccountAttributes,
		arg.HasChildren,
		arg.IsLeafAccount,
		arg.UpdatedBy,
		arg.AccountID,
	)
	var i FinanceAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityID,
		&i.AccountCode,
		&i.AccountName,
		&i.AccountDescription,
		&i.AccountGroupID,
		&i.AccountHeaderID,
		&i.ParentAccountID,
		&i.AccountLevel,
		&i.AccountPath,
		&i.AccountCategory,
		&i.SubCategory,
		&i.DisplayOrder,
		&i.ShowInReports,
		&i.ConsolidationAccount,
		&i.CashFlowType,
		&i.RootType,
		&i.AccountType,
		&i.AccountSubtype,
		&i.NormalBalance,
		&i.IsControlAccount,
		&i.ControlAccountID,
		&i.CurrencyCode,
		&i.IsMultiCurrency,
		&i.CurrencyRevaluationRequired,
		&i.IsActive,
		&i.IsSystemAccount,
		&i.AllowManualEntries,
		&i.RequireReference,
		&i.CurrentBalance,
		&i.YtdBalance,
		&i.LastTransactionDate,
		&i.FinancialStatementLine,
		&i.ReportOrder,
		&i.IsBudgetable,
		&i.BudgetVarianceThreshold,
		&i.Version,
		&i.LastValidationRun,
		&i.ValidationStatus,
		&i.ValidationErrors,
		&i.AccountAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.HasChildren,
		&i.IsLeafAccount,
	)
	return &i, err
}

const updateAccountCurrentBalance = `-- name: UpdateAccountCurrentBalance :exec
UPDATE finance_accounts
SET 
    current_balance = $1,
    ytd_balance = $2,
    last_transaction_date = $3,
    updated_at = NOW()
WHERE id = $4 
  AND tenant_id = current_tenant_id()
  AND deleted_at IS NULL
`

type UpdateAccountCurrentBalanceParams struct {
	CurrentBalance      pgtype.Numeric `json:"current_balance"`
	YtdBalance          pgtype.Numeric `json:"ytd_balance"`
	LastTransactionDate time.Time      `json:"last_transaction_date"`
	AccountID           uuid.UUID      `json:"account_id"`
}

func (q *Queries) UpdateAccountCurrentBalance(ctx context.Context, arg UpdateAccountCurrentBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountCurrentBalance,
		arg.CurrentBalance,
		arg.YtdBalance,
		arg.LastTransactionDate,
		arg.AccountID,
	)
	return err
}

const validateAccountHierarchy = `-- name: ValidateAccountHierarchy :one
SELECT 
    CASE 
        WHEN EXISTS(
            SELECT 1 FROM finance_accounts 
            WHERE parent_account_id = $1 AND id = $1
        ) THEN false -- Self reference check
        ELSE true
    END as is_valid_hierarchy
`

func (q *Queries) ValidateAccountHierarchy(ctx context.Context, parentAccountID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, validateAccountHierarchy, parentAccountID)
	var is_valid_hierarchy bool
	err := row.Scan(&is_valid_hierarchy)
	return is_valid_hierarchy, err
}
