// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Access request approval workflow with business justification, lifecycle management, and automatic revocation for governance and compliance.
type AccessRequest struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	RequesterID uuid.UUID `json:"requester_id"`
	// User receiving the access (if different from requester)
	TargetUserID *uuid.UUID `json:"target_user_id"`
	EntityID     uuid.UUID  `json:"entity_id"`
	// Type of access request: ROLE_ASSIGNMENT, PERMISSION_GRANT, RESOURCE_ACCESS, ELEVATION
	RequestType    string     `json:"request_type"`
	RoleID         *uuid.UUID `json:"role_id"`
	PermissionID   *uuid.UUID `json:"permission_id"`
	ResourceID     *uuid.UUID `json:"resource_id"`
	Justification  string     `json:"justification"`
	BusinessReason *string    `json:"business_reason"`
	// Requested access duration in hours for temporary access
	DurationHours    *int32       `json:"duration_hours"`
	ApprovalStatus   *string      `json:"approval_status"`
	ApprovedBy       *uuid.UUID   `json:"approved_by"`
	ApprovedAt       sql.NullTime `json:"approved_at"`
	ApprovalComments *string      `json:"approval_comments"`
	ExpiresAt        sql.NullTime `json:"expires_at"`
	// Whether to automatically revoke access when it expires
	AutoRevoke *bool        `json:"auto_revoke"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

// Defines actions that can be performed on resources with risk assessment and approval workflow requirements.
type Action struct {
	ID uuid.UUID `json:"id"`
	// Resource this action belongs to. Null for standalone/global actions.
	ResourceID *uuid.UUID `json:"resource_id"`
	// NULL for SYSTEM-scope actions. Set for custom TENANT-scope actions. FK enforced in 000062.
	TenantID *uuid.UUID `json:"tenant_id"`
	// SYSTEM = platform-wide standard action. TENANT = custom action for one tenant.
	Scope string `json:"scope"`
	// Machine-readable key segment within its resource. Forms the third segment of permission keys: {module}.{resource}.{slug}. e.g. 'read', 'create', 'approve'. Do not change after seeding.
	Slug        string  `json:"slug"`
	Name        string  `json:"name"`
	DisplayName *string `json:"display_name"`
	Description *string `json:"description"`
	// HTTP verb this action maps to. e.g. 'GET', 'POST', 'PATCH', 'DELETE'. Used for route documentation.
	HttpMethod *string `json:"http_method"`
	// Standard action type: CREATE, READ, UPDATE, DELETE, EXECUTE, APPROVE, REJECT, EXPORT, IMPORT
	ActionType string `json:"action_type"`
	// Risk category: STANDARD, ADMINISTRATIVE, SENSITIVE, BULK, SYSTEM
	ActionCategory *string `json:"action_category"`
	// Risk level for audit and approval routing: LOW, MEDIUM, HIGH, CRITICAL
	RiskLevel *string `json:"risk_level"`
	// Whether this action requires explicit approval. If TRUE, approver_role_id MUST be set.
	RequiresApproval *bool `json:"requires_approval"`
	// Role whose members can approve this action. Required when requires_approval=TRUE. FK enforced in 000062.
	ApproverRoleID *uuid.UUID   `json:"approver_role_id"`
	IsActive       *bool        `json:"is_active"`
	CreatedAt      sql.NullTime `json:"created_at"`
	// Updated by trigger on every row change — use for cache invalidation.
	UpdatedAt sql.NullTime `json:"updated_at"`
}

// Third-party / integration API keys. Key is hashed (SHA-256) — raw key returned once at creation and never stored.
type ApiKey struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	// SHA-256 hex of the raw bearer token. Raw token returned once at creation, never stored.
	KeyHash string `json:"key_hash"`
	// Allowed permission keys for this key. Acts as a ceiling — cannot exceed the creating user's own permissions.
	Scopes []string `json:"scopes"`
	// User who created this key. Key inherits at most the creator's permissions at time of creation.
	CreatedBy uuid.UUID    `json:"created_by"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	// Set to revoke the key immediately. Checked on every request before permission evaluation.
	RevokedAt  sql.NullTime `json:"revoked_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

// Defines attributes used in ABAC policies with data types, validation rules, and security controls for consistent attribute management.
type AttributeDefinition struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	DisplayName *string   `json:"display_name"`
	Description *string   `json:"description"`
	// Attribute data type: STRING, NUMBER, BOOLEAN, DATE, TIME, JSON, ARRAY, ENUM
	DataType string `json:"data_type"`
	// Attribute category: USER (user attributes), RESOURCE (resource attributes), ENVIRONMENT (context), ACTION (action attributes), ENTITY (entity attributes), SESSION (session context)
	Category   string `json:"category"`
	IsRequired *bool  `json:"is_required"`
	// Whether attribute contains PII or sensitive data requiring special handling
	IsSensitive  *bool   `json:"is_sensitive"`
	DefaultValue *string `json:"default_value"`
	// JSONB array of allowed values for ENUM data type
	AllowedValues []byte `json:"allowed_values"`
	// JSONB containing custom validation rules (regex, ranges, etc.)
	ValidationRules []byte `json:"validation_rules"`
	// Whether attribute values must be encrypted at rest
	EncryptionRequired *bool        `json:"encryption_required"`
	IsActive           *bool        `json:"is_active"`
	CreatedAt          sql.NullTime `json:"created_at"`
}

// Defines external sources for attribute collection with configuration, authentication, and caching controls.
type AttributeSource struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	DisplayName *string   `json:"display_name"`
	Description *string   `json:"description"`
	// Type of attribute source: LDAP, DATABASE, REST_API, GRAPHQL, FILE, MANUAL
	SourceType string `json:"source_type"`
	// JSONB containing source-specific configuration (URLs, queries, etc.)
	Configuration []byte `json:"configuration"`
	// JSONB containing authentication details (should be encrypted)
	Authentication  []byte `json:"authentication"`
	CacheTtlMinutes *int32 `json:"cache_ttl_minutes"`
	IsActive        *bool  `json:"is_active"`
	// Source priority for attribute resolution (higher numbers processed first)
	Priority  *int32       `json:"priority"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

// Stores actual attribute values for entities with versioning, encryption, and temporal support for ABAC policy evaluation.
type AttributeValue struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	DefinitionID uuid.UUID `json:"definition_id"`
	// The UUID of the entity this attribute belongs to (user, resource, document, etc.)
	EntityID uuid.UUID `json:"entity_id"`
	// The actual attribute value in string format
	Value string `json:"value"`
	// Encrypted version of the value when encryption is required
	EncryptedValue []byte `json:"encrypted_value"`
	IsEncrypted    *bool  `json:"is_encrypted"`
	Version        *int32 `json:"version"`
	// When this attribute value becomes effective (for temporal policies)
	EffectiveFrom sql.NullTime `json:"effective_from"`
	// When this attribute value expires (null for current values)
	EffectiveTo sql.NullTime `json:"effective_to"`
	CreatedAt   sql.NullTime `json:"created_at"`
	CreatedBy   *uuid.UUID   `json:"created_by"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	UpdatedBy   *uuid.UUID   `json:"updated_by"`
}

// Immutable audit log with compliance tracking, risk scoring, and detailed context for security monitoring and regulatory compliance.
type AuditLog struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	EventType string    `json:"event_type"`
	// Event category: ACCESS (authorization), ADMIN (administrative), DATA (data access), AUTH (authentication), SYSTEM (system events), COMPLIANCE (regulatory)
	EventCategory *string `json:"event_category"`
	// Event severity level: LOW, INFO, WARN, HIGH, CRITICAL
	Severity *string    `json:"severity"`
	UserID   *uuid.UUID `json:"user_id"`
	// Target user for administrative actions (e.g., admin modifying another user)
	TargetUserID *uuid.UUID `json:"target_user_id"`
	EntityID     *uuid.UUID `json:"entity_id"`
	ResourceID   *uuid.UUID `json:"resource_id"`
	ActionID     *uuid.UUID `json:"action_id"`
	RoleID       *uuid.UUID `json:"role_id"`
	PermissionID *uuid.UUID `json:"permission_id"`
	Decision     *string    `json:"decision"`
	Reason       *string    `json:"reason"`
	// Calculated risk score from 0-100 based on action, context, and user behavior
	RiskScore *int32      `json:"risk_score"`
	Context   []byte      `json:"context"`
	IpAddress *netip.Addr `json:"ip_address"`
	UserAgent *string     `json:"user_agent"`
	SessionID *uuid.UUID  `json:"session_id"`
	// JSONB containing compliance-related flags (GDPR, SOX, HIPAA, PCI, etc.)
	ComplianceFlags []byte       `json:"compliance_flags"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type CasbinRule struct {
	ID    uuid.UUID `json:"id"`
	Ptype string    `json:"ptype"`
	V0    string    `json:"v0"`
	V1    string    `json:"v1"`
	V2    string    `json:"v2"`
	V3    string    `json:"v3"`
	V4    string    `json:"v4"`
	V5    string    `json:"v5"`
}

// Schema registry for all available configuration keys across modules. Owned exclusively by the Settings module — do not write from other modules directly. Defines what keys exist, their types, defaults, validation rules, and access control.
type ConfigDefinition struct {
	ID uuid.UUID `json:"id"`
	// Module that owns this key (e.g. finance, hr, inventory). Lowercase snake_case.
	ModuleName string `json:"module_name"`
	// Configuration key within the module. Lowercase snake_case. Unique within module.
	ConfigKey string `json:"config_key"`
	// Value data type used by ConfigurationService for casting and validation.
	ConfigType string `json:"config_type"`
	// System-level default (Level 1 in hierarchy). NULL means tenant/entity must configure it explicitly.
	DefaultValue []byte `json:"default_value"`
	// Whether tenant admins may override the system default.
	IsTenantOverridable bool `json:"is_tenant_overridable"`
	// Whether entity managers may override the tenant value.
	IsEntityOverridable bool `json:"is_entity_overridable"`
	// JSON validation rules evaluated by ConfigurationService. Supports min/max/pattern/enum/required.
	ValidationRules []byte `json:"validation_rules"`
	// FeatureFlag service key required for this config to be available. NULL = always available. ADR-026.
	RequiredFeatureFlag *string `json:"required_feature_flag"`
	// IAM service permission key required to read/write this config. NULL = any authenticated user. ADR-027.
	RequiredIamPermission *string `json:"required_iam_permission"`
	// Human-readable label shown in the Settings UI.
	DisplayName string `json:"display_name"`
	// Full explanation of what this setting controls. Shown as help text.
	Description string `json:"description"`
	// Optional unit label for numeric values (days, %, USD). Shown next to input field.
	UnitLabel *string `json:"unit_label"`
	// Inactive definitions are hidden from UI but preserved for backward compatibility with stored values.
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Complete audit trail of all configuration changes for compliance and troubleshooting
type ConfigurationAudit struct {
	// UUID primary key for the audit record
	ID uuid.UUID `json:"id"`
	// Foreign key to tenants table for multi-tenant isolation
	TenantID uuid.UUID `json:"tenant_id"`
	// Optional FK to entities — set when the change is entity-level
	EntityID *uuid.UUID `json:"entity_id"`
	// Module owning this config key (e.g. finance, hr, inventory)
	ModuleName string `json:"module_name"`
	// Config key within the module (e.g. invoice_prefix, valuation_method)
	ConfigKeyName string `json:"config_key_name"`
	// Previous configuration value (JSONB)
	OldValue []byte `json:"old_value"`
	// New configuration value (JSONB)
	NewValue []byte `json:"new_value"`
	// Level where change occurred: SYSTEM, TENANT, ENTITY, TEMPLATE
	Source string `json:"source"`
	// Operation type: CREATE, UPDATE, DELETE, RESET, TEMPLATE_APPLY
	Operation string `json:"operation"`
	// UUID of user who made the change
	UserID    uuid.UUID `json:"user_id"`
	AppliedAt time.Time `json:"applied_at"`
	// Session identifier for grouping related changes
	SessionID *string `json:"session_id"`
	// Correlation ID for tracking bulk/template operations
	CorrelationID *string `json:"correlation_id"`
}

// Reusable configuration templates for bulk deployment across tenants and entities
type ConfigurationTemplate struct {
	// UUID primary key for the configuration template
	ID uuid.UUID `json:"id"`
	// Owning tenant for TENANT-scoped templates; NULL for SYSTEM-scoped templates
	TenantID *uuid.UUID `json:"tenant_id"`
	EntityID *uuid.UUID `json:"entity_id"`
	// SYSTEM = platform-wide, readable by all. TENANT = private to owner tenant.
	Scope string `json:"scope"`
	// Template display name
	Name string `json:"name"`
	// Template category: INDUSTRY, FUNCTIONAL, or REGIONAL
	Category    string  `json:"category"`
	Description *string `json:"description"`
	// Semantic version string for template versioning
	Version string `json:"version"`
	// JSONB object of module.key → value pairs applied by this template
	Configurations []byte `json:"configurations"`
	// Tenant types this template is designed for
	ApplicableTenantTypes []string `json:"applicable_tenant_types"`
	// Feature flags that must be enabled for this template to be applicable
	RequiredFeatureFlags []string `json:"required_feature_flags"`
	// How to handle key conflicts on apply: MERGE, REPLACE, or PRESERVE
	ConflictResolution *string `json:"conflict_resolution"`
	// Active templates appear in the UI. Deactivate instead of deleting applied templates.
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	// UUID of user who created this template
	CreatedBy uuid.UUID `json:"created_by"`
}

// Employee records extending persons with employment-specific data, organizational hierarchy, and security levels for access control.
type Employee struct {
	// UUID primary key for the employee record.
	ID uuid.UUID `json:"id"`
	// Foreign key to tenants table for multi-tenant isolation.
	TenantID uuid.UUID `json:"tenant_id"`
	// Foreign key to persons table linking to personal information.
	PersonID uuid.UUID `json:"person_id"`
	// Unique employee identifier within tenant.
	EmployeeNumber string `json:"employee_number"`
	// Foreign key to entities table for organizational assignment.
	EntityID uuid.UUID `json:"entity_id"`
	// Employee's job title or position.
	PositionTitle *string `json:"position_title"`
	// Foreign key to entities table representing department.
	DepartmentID *uuid.UUID `json:"department_id"`
	// Self-referential foreign key for organizational hierarchy.
	ManagerID *uuid.UUID `json:"manager_id"`
	// Date when employee was hired.
	HireDate time.Time `json:"hire_date"`
	// Date when employee was terminated (if applicable).
	TerminationDate time.Time `json:"termination_date"`
	// JSONB containing encrypted/sensitive salary and compensation data.
	SalaryInfo []byte `json:"salary_info"`
	// Current employment status: ACTIVE, INACTIVE, TERMINATED, ON_LEAVE, SUSPENDED.
	EmploymentStatus *string `json:"employment_status"`
	// JSONB containing flexible work schedule definition.
	WorkSchedule []byte `json:"work_schedule"`
	// Numeric security clearance level (0 = lowest; higher numbers = higher clearance).
	SecurityLevel *int32 `json:"security_level"`
	// JSONB containing employment-specific ABAC attributes for access control.
	AccessAttributes []byte    `json:"access_attributes"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	// Soft delete timestamp — NULL means record is active.
	DeletedAt sql.NullTime `json:"deleted_at"`
}

// Master table for business entities and organisational units. Supports hierarchical structures for companies, subsidiaries, departments, and other divisions. Each entity can maintain its own accounting books, customers, vendors, and fiscal year settings.
type Entity struct {
	// Primary key — unique identifier for the entity.
	Uuid uuid.UUID `json:"uuid"`
	// FK to tenants — associates entity with a specific tenant for multi-tenancy.
	TenantID uuid.UUID `json:"tenant_id"`
	// Self-referencing FK — creates hierarchical relationship between entities (e.g., subsidiary under parent company).
	ParentID *uuid.UUID `json:"parent_id"`
	// Business name or title of the entity — must be unique within tenant.
	Name string `json:"name"`
	// Optional internal reference code — used for abbreviated identification and reporting.
	Code *string `json:"code"`
	// Classification of entity type — defines the organisational level and purpose.
	Type string `json:"type"`
	// Active status flag — indicates whether the entity is currently operational.
	IsActive bool `json:"is_active"`
	// Visibility flag — controls whether entity appears in UIs and reports.
	Hidden bool `json:"hidden"`
	// Accounting method: TRUE = accrual, FALSE = cash.
	AccrualMethod bool `json:"accrual_method"`
	// Fiscal year start month — numeric month (1–12) when fiscal year begins for this entity.
	FyStartMonth int32 `json:"fy_start_month"`
	// Physical address stored as a JSON object with flexible address components.
	Address []byte `json:"address"`
	// Entity logo or image reference — file path or URL.
	Picture *string `json:"picture"`
	// Materialized path: /uuid1/uuid2/this_uuid/. Enables subtree queries via LIKE '/root/%'. Populated by app layer on create/reparent. Root entities: /uuid/.
	EntityPath *string `json:"entity_path"`
	// Hierarchy depth: 1 = root COMPANY, increments per level (max 8). Used to determine EntityScope: level 1 = all, leaf = entity, else = subtree.
	EntityLevel int32 `json:"entity_level"`
	// Entity-specific configuration — JSON object storing customisable settings and preferences.
	Settings          []byte       `json:"settings"`
	Metadata          []byte       `json:"metadata"`
	Version           int32        `json:"version"`
	LastValidationRun sql.NullTime `json:"last_validation_run"`
	ValidationStatus  *string      `json:"validation_status"`
	ValidationErrors  []byte       `json:"validation_errors"`
	// Record creation timestamp — automatically set when entity is first created.
	CreatedAt time.Time `json:"created_at"`
	// Last modification timestamp — automatically updated on every row change.
	UpdatedAt time.Time `json:"updated_at"`
	// Soft deletion timestamp — NULL for active records, set when logically deleted.
	DeletedAt sql.NullTime `json:"deleted_at"`
}

// Manages sequential numbering for business documents within entities. Tracks next available sequence numbers for different document types (invoices, purchase orders, estimates, etc.) by fiscal year and entity.
type Entitystate struct {
	// Primary key — unique identifier for the entity state record.
	Uuid uuid.UUID `json:"uuid"`
	// Foreign key to tenants table for multi-tenant isolation.
	TenantID uuid.UUID `json:"tenant_id"`
	// Fiscal year for sequence tracking — allows separate numbering sequences per year.
	FiscalYear *int16 `json:"fiscal_year"`
	// Document type identifier — specifies the type of document being numbered (invoice, po, estimate, bill, receipt, etc.).
	Key string `json:"key"`
	// Next sequence number — the next available sequential number for this document type.
	Sequence int64 `json:"sequence"`
	// Primary entity reference — the main entity that owns this sequence numbering.
	EntityID uuid.UUID `json:"entity_id"`
	// Sub-entity reference — optional reference to a subsidiary or department within the main entity for more granular numbering.
	EntityUnitID *uuid.UUID `json:"entity_unit_id"`
	// Document sequence formatting config for this entity+doctype combination. Keys: prefix, suffix, pad_length (INT), reset_frequency (yearly|monthly|never), format_template (STRING). Overrides tenant_configurations.settings for sequences on this entity. Example: {"prefix":"NORTH-INV-","pad_length":6,"reset_frequency":"yearly"}
	Config    []byte       `json:"config"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

// Master feature flags configuration table with tenant isolation
type FeatureFlag struct {
	ID           uuid.UUID  `json:"id"`
	TenantID     uuid.UUID  `json:"tenant_id"`
	EntityID     *uuid.UUID `json:"entity_id"`
	Name         string     `json:"name"`
	Description  *string    `json:"description"`
	FlagType     string     `json:"flag_type"`
	DefaultValue bool       `json:"default_value"`
	// Percentage of tenants that should have this feature enabled (0-100)
	RolloutPercentage *int32 `json:"rollout_percentage"`
	// Advanced targeting rules (company_size, industry, etc.)
	TargetAudience []byte `json:"target_audience"`
	// Additional metadata like expiration dates, dependencies, etc.
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	// Soft delete timestamp - NULL means active
	DeletedAt sql.NullTime `json:"deleted_at"`
}

// System-wide feature flag catalogue. No tenant_id — shared across all tenants. Auto-seeded by triggers on modules and resources. Tenant overrides live in tenant_feature_flags.
type FeatureFlagDefinition struct {
	ID         uuid.UUID  `json:"id"`
	ModuleID   *uuid.UUID `json:"module_id"`
	ResourceID *uuid.UUID `json:"resource_id"`
	// Dot-notation key derived from MRA slugs: module.slug or module.slug.resource.slug. e.g. 'finance', 'finance.transactions'. Never write free-form strings — always derive from slugs.
	FlagKey     string  `json:"flag_key"`
	Label       string  `json:"label"`
	Description *string `json:"description"`
	// Value tenants get without any configuration. Modules default false (off); resources default true (on once module is on).
	DefaultValue bool `json:"default_value"`
	// When true, only platform operators (admin_role) can toggle. Tenant admins cannot see or change these.
	IsSystem  bool      `json:"is_system"`
	CreatedAt time.Time `json:"created_at"`
}

// Master chart of accounts for all financial transactions. Supports hierarchical account structures, multi-currency operations, and financial reporting requirements.
type FinanceAccount struct {
	ID       uuid.UUID  `json:"id"`
	TenantID uuid.UUID  `json:"tenant_id"`
	EntityID *uuid.UUID `json:"entity_id"`
	// Unique account code within tenant — used for transaction posting and reporting.
	AccountCode        string  `json:"account_code"`
	AccountName        string  `json:"account_name"`
	AccountDescription *string `json:"account_description"`
	// Link to account group for organizational structure and reporting.
	AccountGroupID *uuid.UUID `json:"account_group_id"`
	// Link to account header for financial statement presentation.
	AccountHeaderID *uuid.UUID `json:"account_header_id"`
	ParentAccountID *uuid.UUID `json:"parent_account_id"`
	AccountLevel    int32      `json:"account_level"`
	// Materialized path for efficient hierarchy queries — format: /root/parent/child/.
	AccountPath *string `json:"account_path"`
	// Detailed category within account type (e.g., CURRENT_ASSETS, FIXED_ASSETS).
	AccountCategory      *string `json:"account_category"`
	SubCategory          *string `json:"sub_category"`
	DisplayOrder         *int32  `json:"display_order"`
	ShowInReports        *bool   `json:"show_in_reports"`
	ConsolidationAccount *string `json:"consolidation_account"`
	// Cash flow statement classification for proper statement presentation.
	CashFlowType *string `json:"cash_flow_type"`
	// High-level account classification for balance sheet and income statement categorization.
	RootType       string  `json:"root_type"`
	AccountType    string  `json:"account_type"`
	AccountSubtype *string `json:"account_subtype"`
	// Normal balance type — DEBIT for assets/expenses, CREDIT for liabilities/equity/revenue.
	NormalBalance               string         `json:"normal_balance"`
	IsControlAccount            bool           `json:"is_control_account"`
	ControlAccountID            *uuid.UUID     `json:"control_account_id"`
	CurrencyCode                *string        `json:"currency_code"`
	IsMultiCurrency             *bool          `json:"is_multi_currency"`
	CurrencyRevaluationRequired *bool          `json:"currency_revaluation_required"`
	IsActive                    bool           `json:"is_active"`
	IsSystemAccount             bool           `json:"is_system_account"`
	AllowManualEntries          bool           `json:"allow_manual_entries"`
	RequireReference            bool           `json:"require_reference"`
	CurrentBalance              pgtype.Numeric `json:"current_balance"`
	YtdBalance                  pgtype.Numeric `json:"ytd_balance"`
	LastTransactionDate         time.Time      `json:"last_transaction_date"`
	FinancialStatementLine      *string        `json:"financial_statement_line"`
	ReportOrder                 *int32         `json:"report_order"`
	IsBudgetable                *bool          `json:"is_budgetable"`
	BudgetVarianceThreshold     pgtype.Numeric `json:"budget_variance_threshold"`
	Version                     int32          `json:"version"`
	LastValidationRun           sql.NullTime   `json:"last_validation_run"`
	ValidationStatus            *string        `json:"validation_status"`
	ValidationErrors            []byte         `json:"validation_errors"`
	AccountAttributes           []byte         `json:"account_attributes"`
	CreatedAt                   time.Time      `json:"created_at"`
	UpdatedAt                   time.Time      `json:"updated_at"`
	DeletedAt                   sql.NullTime   `json:"deleted_at"`
	CreatedBy                   *uuid.UUID     `json:"created_by"`
	UpdatedBy                   *uuid.UUID     `json:"updated_by"`
	HasChildren                 *bool          `json:"has_children"`
	IsLeafAccount               *bool          `json:"is_leaf_account"`
}

// Historical account balance tracking for audit and reporting purposes
type FinanceAccountBalance struct {
	ID             uuid.UUID      `json:"id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	EntityID       *uuid.UUID     `json:"entity_id"`
	BalanceDate    time.Time      `json:"balance_date"`
	OpeningBalance pgtype.Numeric `json:"opening_balance"`
	ClosingBalance pgtype.Numeric `json:"closing_balance"`
	PeriodDebits   pgtype.Numeric `json:"period_debits"`
	PeriodCredits  pgtype.Numeric `json:"period_credits"`
	FiscalYear     int32          `json:"fiscal_year"`
	FiscalPeriod   int32          `json:"fiscal_period"`
	CreatedAt      time.Time      `json:"created_at"`
	CreatedBy      *uuid.UUID     `json:"created_by"`
}

// Account groups and headers for organizing chart of accounts into logical reporting structures.
type FinanceAccountGroup struct {
	ID               uuid.UUID  `json:"id"`
	TenantID         uuid.UUID  `json:"tenant_id"`
	EntityID         *uuid.UUID `json:"entity_id"`
	GroupCode        string     `json:"group_code"`
	GroupName        string     `json:"group_name"`
	GroupDescription *string    `json:"group_description"`
	ParentGroupID    *uuid.UUID `json:"parent_group_id"`
	GroupLevel       int32      `json:"group_level"`
	// Materialized path for efficient hierarchy queries — maintained by trigger in 000906.
	GroupPath *string `json:"group_path"`
	// High-level classification: ASSET, LIABILITY, EQUITY, REVENUE, or EXPENSE.
	RootType      string  `json:"root_type"`
	GroupCategory *string `json:"group_category"`
	// Target financial statement: Balance Sheet, Income Statement, or Cash Flow.
	FinancialStatementSection *string `json:"financial_statement_section"`
	StatementOrder            *int32  `json:"statement_order"`
	ShowInSummary             *bool   `json:"show_in_summary"`
	// How child balances are rolled up: SUM (default), AVERAGE, MAX, MIN, or CUSTOM.
	ConsolidationMethod *string `json:"consolidation_method"`
	DisplayFormat       *string `json:"display_format"`
	IndentLevel         *int32  `json:"indent_level"`
	ShowTotals          *bool   `json:"show_totals"`
	BoldDisplay         *bool   `json:"bold_display"`
	IsActive            bool    `json:"is_active"`
	// TRUE for platform-seeded groups that cannot be deleted by tenants.
	IsSystemGroup         bool         `json:"is_system_group"`
	AllowDirectPosting    *bool        `json:"allow_direct_posting"`
	BudgetCategory        *string      `json:"budget_category"`
	VarianceAnalysisGroup *string      `json:"variance_analysis_group"`
	CashFlowCategory      *string      `json:"cash_flow_category"`
	GroupAttributes       []byte       `json:"group_attributes"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
	DeletedAt             sql.NullTime `json:"deleted_at"`
	CreatedBy             *uuid.UUID   `json:"created_by"`
	UpdatedBy             *uuid.UUID   `json:"updated_by"`
}

// Configurable validation rules for accounts and transactions - enables business rule enforcement
type FinanceAccountValidationRule struct {
	ID                       uuid.UUID      `json:"id"`
	TenantID                 uuid.UUID      `json:"tenant_id"`
	RuleName                 string         `json:"rule_name"`
	RuleDescription          *string        `json:"rule_description"`
	AccountType              *string        `json:"account_type"`
	RootType                 *string        `json:"root_type"`
	AccountPattern           *string        `json:"account_pattern"`
	MinAmount                pgtype.Numeric `json:"min_amount"`
	MaxAmount                pgtype.Numeric `json:"max_amount"`
	RequiredReference        *bool          `json:"required_reference"`
	AllowedTransactionTypes  []string       `json:"allowed_transaction_types"`
	RequiredCostCenter       *bool          `json:"required_cost_center"`
	IsActive                 *bool          `json:"is_active"`
	RuleSeverity             *string        `json:"rule_severity"`
	CustomValidationFunction *string        `json:"custom_validation_function"`
	ValidationParameters     []byte         `json:"validation_parameters"`
	CreatedAt                time.Time      `json:"created_at"`
	UpdatedAt                time.Time      `json:"updated_at"`
	CreatedBy                *uuid.UUID     `json:"created_by"`
	UpdatedBy                *uuid.UUID     `json:"updated_by"`
}

// Header table for all financial transactions. Contains transaction metadata, approval workflow, and summary amounts.
type FinanceTransaction struct {
	ID       uuid.UUID  `json:"id"`
	TenantID uuid.UUID  `json:"tenant_id"`
	EntityID *uuid.UUID `json:"entity_id"`
	// Unique transaction number within tenant — auto-generated or user-provided.
	TransactionNumber string `json:"transaction_number"`
	// Type of transaction — determines behavior and validation rules.
	TransactionType string `json:"transaction_type"`
	// Current status in transaction lifecycle — controls what operations are allowed.
	TransactionStatus string `json:"transaction_status"`
	// Date when the transaction occurred — business date for accounting purposes.
	TransactionDate time.Time `json:"transaction_date"`
	// Date when transaction was posted to the general ledger — required when status is POSTED.
	PostingDate time.Time `json:"posting_date"`
	// Due date for payment transactions — used for AP/AR and cash management.
	DueDate           time.Time `json:"due_date"`
	Description       string    `json:"description"`
	ReferenceNumber   *string   `json:"reference_number"`
	ExternalReference *string   `json:"external_reference"`
	Memo              *string   `json:"memo"`
	// ISO 4217 currency code — defaults to USD but supports multi-currency.
	CurrencyCode string `json:"currency_code"`
	// Exchange rate from transaction currency to functional currency — defaults to 1.0 for same currency.
	ExchangeRate pgtype.Numeric `json:"exchange_rate"`
	// Sum of all debit entries — must equal total_credit_amount for balanced transactions.
	TotalDebitAmount pgtype.Numeric `json:"total_debit_amount"`
	// Sum of all credit entries — must equal total_debit_amount for balanced transactions.
	TotalCreditAmount pgtype.Numeric `json:"total_credit_amount"`
	// Source module that created this transaction: AP, AR, GL, PAYROLL, etc.
	SourceModule *string `json:"source_module"`
	// Type of source document: INVOICE, PAYMENT, JOURNAL_ENTRY, etc.
	SourceDocumentType *string `json:"source_document_type"`
	// ID of the source document that generated this transaction.
	SourceDocumentID *uuid.UUID `json:"source_document_id"`
	// Batch ID for grouping related transactions — useful for imports and bulk operations.
	BatchID                 *uuid.UUID   `json:"batch_id"`
	ApprovalRequired        *bool        `json:"approval_required"`
	ApprovalStatus          *string      `json:"approval_status"`
	ApprovedBy              *uuid.UUID   `json:"approved_by"`
	ApprovedAt              sql.NullTime `json:"approved_at"`
	ApprovalNotes           *string      `json:"approval_notes"`
	IsRecurring             *bool        `json:"is_recurring"`
	RecurringFrequency      *string      `json:"recurring_frequency"`
	NextRecurringDate       time.Time    `json:"next_recurring_date"`
	IsReversed              *bool        `json:"is_reversed"`
	ReversedByTransactionID *uuid.UUID   `json:"reversed_by_transaction_id"`
	ReversalReason          *string      `json:"reversal_reason"`
	// Version number for optimistic locking — prevents concurrent modifications.
	Version          int32   `json:"version"`
	ValidationStatus *string `json:"validation_status"`
	// JSON array of validation errors and warnings — helps with troubleshooting.
	ValidationErrors      []byte `json:"validation_errors"`
	TransactionAttributes []byte `json:"transaction_attributes"`
	// Array of attachment/document IDs — links to supporting documents.
	AttachmentIds []string `json:"attachment_ids"`
	// Array of tags for categorization and filtering — max 25 chars each.
	Tags      []string     `json:"tags"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedBy uuid.UUID    `json:"created_by"`
	UpdatedBy *uuid.UUID   `json:"updated_by"`
	PostedBy  *uuid.UUID   `json:"posted_by"`
	// Timestamp when transaction was posted — required when status is POSTED.
	PostedAt sql.NullTime `json:"posted_at"`
}

// Individual journal entries that make up financial transactions. Implements double-entry bookkeeping with debit and credit amounts.
type FinanceTransactionEntry struct {
	ID            uuid.UUID  `json:"id"`
	TenantID      uuid.UUID  `json:"tenant_id"`
	EntityID      *uuid.UUID `json:"entity_id"`
	TransactionID uuid.UUID  `json:"transaction_id"`
	// Sequential entry number within transaction — used for ordering and reference.
	EntryNumber int32     `json:"entry_number"`
	AccountID   uuid.UUID `json:"account_id"`
	// Debit amount in functional currency — must be 0 if credit_amount > 0.
	DebitAmount pgtype.Numeric `json:"debit_amount"`
	// Credit amount in functional currency — must be 0 if debit_amount > 0.
	CreditAmount     pgtype.Numeric `json:"credit_amount"`
	Description      string         `json:"description"`
	Reference        *string        `json:"reference"`
	CostCenter       *string        `json:"cost_center"`
	Department       *string        `json:"department"`
	ProjectID        *uuid.UUID     `json:"project_id"`
	OriginalCurrency *string        `json:"original_currency"`
	// Original transaction amount in original currency before conversion.
	OriginalAmount          pgtype.Numeric `json:"original_amount"`
	ExchangeRate            pgtype.Numeric `json:"exchange_rate"`
	TaxCode                 *string        `json:"tax_code"`
	TaxRate                 pgtype.Numeric `json:"tax_rate"`
	TaxAmount               pgtype.Numeric `json:"tax_amount"`
	Reconciled              *bool          `json:"reconciled"`
	ReconciledDate          time.Time      `json:"reconciled_date"`
	ReconciliationReference *string        `json:"reconciliation_reference"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
	DeletedAt               sql.NullTime   `json:"deleted_at"`
}

// Closure table for efficient entity hierarchy queries. Stores all ancestor-descendant relationships with depth information. Enables fast retrieval of entity trees, subtrees, and hierarchy levels without recursive queries.
type HierarchyPath struct {
	// Tenant identifier — partitions hierarchy data by tenant for multi-tenancy.
	TenantID uuid.UUID `json:"tenant_id"`
	// Ancestor entity in the relationship — references entities.uuid.
	AncestorID uuid.UUID `json:"ancestor_id"`
	// Descendant entity in the relationship — references entities.uuid.
	DescendantID uuid.UUID `json:"descendant_id"`
	// Hierarchical distance: 0 = self-reference, 1 = direct parent-child, 2+ = deeper.
	Depth     int32     `json:"depth"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// System modules for organising permissions and features. Enables modular permission management and feature toggles.
type Module struct {
	ID uuid.UUID `json:"id"`
	// NULL for SYSTEM-scope modules. Set for custom TENANT-scope modules. FK enforced in 000062.
	TenantID *uuid.UUID `json:"tenant_id"`
	// SYSTEM = platform-wide, readable by all. TENANT = private custom module.
	Scope string `json:"scope"`
	// Machine-readable key segment used in dot-notation: {slug}.{resource}.{action}. e.g. 'finance', 'selling'. Do not change after seeding — all permission/flag keys depend on it.
	Slug        string  `json:"slug"`
	Name        string  `json:"name"`
	DisplayName *string `json:"display_name"`
	Description *string `json:"description"`
	// Icon class for sidebar nav. e.g. 'fa fa-calculator'.
	Icon *string `json:"icon"`
	// Sidebar display order. Lower = higher. Default 999.
	NavOrder int32 `json:"nav_order"`
	// Module category: CORE, HR, FINANCE, SALES, INVENTORY, etc.
	Category *string `json:"category"`
	// Helps categorise industry-specific apps: CORE, INDUSTRY, EXTENSION, INTERNAL.
	ModuleType *string `json:"module_type"`
	// Module version for tracking feature updates and compatibility.
	Version   *string      `json:"version"`
	IsActive  *bool        `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
	// Updated by trigger on every row change — use for cache invalidation.
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type MvTenantFeatureFlagsCache struct {
	TenantID          uuid.UUID   `json:"tenant_id"`
	FeatureFlagID     uuid.UUID   `json:"feature_flag_id"`
	FeatureFlagName   string      `json:"feature_flag_name"`
	FlagType          string      `json:"flag_type"`
	Enabled           interface{} `json:"enabled"`
	Value             []byte      `json:"value"`
	EvaluationSource  string      `json:"evaluation_source"`
	DefaultValue      bool        `json:"default_value"`
	RolloutPercentage *int32      `json:"rollout_percentage"`
	TargetAudience    []byte      `json:"target_audience"`
	Metadata          []byte      `json:"metadata"`
	OverrideEnabled   *bool       `json:"override_enabled"`
	OverrideValue     []byte      `json:"override_value"`
	OverrideReason    *string     `json:"override_reason"`
	CacheTimestamp    interface{} `json:"cache_timestamp"`
	CacheCreatedAt    interface{} `json:"cache_created_at"`
}

type MvUserEffectivePermission struct {
	UserID              uuid.UUID   `json:"user_id"`
	TenantID            uuid.UUID   `json:"tenant_id"`
	ResourceID          uuid.UUID   `json:"resource_id"`
	ActionID            uuid.UUID   `json:"action_id"`
	AllowFlag           interface{} `json:"allow_flag"`
	RolePermissionIds   interface{} `json:"role_permission_ids"`
	DirectPermissionIds interface{} `json:"direct_permission_ids"`
}

// Stores user notification preferences.
type NotificationPreference struct {
	ID                 uuid.UUID `json:"id"`
	TenantID           uuid.UUID `json:"tenant_id"`
	UserID             uuid.UUID `json:"user_id"`
	EmailNotifications bool      `json:"email_notifications"`
	InAppNotifications bool      `json:"in_app_notifications"`
	SlackNotifications bool      `json:"slack_notifications"`
	// JSONB object with notification types as keys and booleans as values.
	NotificationTypes []byte `json:"notification_types"`
	// JSONB array of preferred notification channels.
	PreferredChannels []byte `json:"preferred_channels"`
	// JSONB object with quiet hours settings.
	QuietHours []byte    `json:"quiet_hours"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// Single-use tokens for the forgot-password email flow. token_hash is SHA-256 of the raw token. used_at IS NOT NULL means the token has been consumed.
type PasswordResetToken struct {
	ID        uuid.UUID    `json:"id"`
	TenantID  uuid.UUID    `json:"tenant_id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

// Granular permissions combining resources and actions with ABAC conditions, data filters, and field restrictions for fine-grained access control.
type Permission struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	ResourceID  uuid.UUID `json:"resource_id"`
	ActionID    uuid.UUID `json:"action_id"`
	Name        string    `json:"name"`
	DisplayName *string   `json:"display_name"`
	Description *string   `json:"description"`
	// Permission effect: ALLOW (grant access) or DENY (explicitly deny access)
	Effect *string `json:"effect"`
	// JSONB containing ABAC evaluation conditions (time, location, attributes, etc.)
	Conditions []byte `json:"conditions"`
	// JSONB containing row-level security filters to limit data access
	DataFilters []byte `json:"data_filters"`
	// JSONB containing column-level restrictions to limit field access
	FieldRestrictions []byte       `json:"field_restrictions"`
	IsActive          *bool        `json:"is_active"`
	CreatedAt         sql.NullTime `json:"created_at"`
}

// Stores person entities with ABAC security attributes. Supports multiple person types including employees, customers, vendors, and contractors. Implements soft delete and tenant isolation.
type Person struct {
	// UUID primary key for the person record.
	ID uuid.UUID `json:"id"`
	// Foreign key to tenants table for multi-tenant isolation.
	TenantID uuid.UUID `json:"tenant_id"`
	// Foreign key to entities table for hierarchical organization.
	EntityID uuid.UUID `json:"entity_id"`
	// Classification of person: INDIVIDUAL, EMPLOYEE, CONTACT, CUSTOMER, VENDOR, CONTRACTOR.
	PersonType string `json:"person_type"`
	// Person's first/given name.
	FirstName string `json:"first_name"`
	// Person's last/family name.
	LastName string `json:"last_name"`
	// Person's middle name or initial (optional).
	MiddleName *string `json:"middle_name"`
	// Person's email address (must be unique per tenant when not deleted).
	Email *string `json:"email"`
	// Person's primary phone number.
	Phone *string `json:"phone"`
	// Person's date of birth.
	BirthDate time.Time `json:"birth_date"`
	// Government-issued national ID number (unique per tenant).
	NationalID *string `json:"national_id"`
	// Tax identification number.
	TaxID *string `json:"tax_id"`
	// Person's address stored as JSONB for flexible structure.
	Address []byte `json:"address"`
	// JSONB containing ABAC attributes like clearance level, department, location for access control.
	SecurityAttributes []byte `json:"security_attributes"`
	// Flexible JSONB storage for additional person-related data.
	Metadata []byte `json:"metadata"`
	// Whether the person record is currently active.
	IsActive          bool         `json:"is_active"`
	Version           int32        `json:"version"`
	LastValidationRun sql.NullTime `json:"last_validation_run"`
	ValidationStatus  *string      `json:"validation_status"`
	ValidationErrors  []byte       `json:"validation_errors"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	// Soft delete timestamp — NULL means record is active.
	DeletedAt sql.NullTime `json:"deleted_at"`
}

// ABAC policies with advanced rule engine supporting multiple policy types, priorities, obligations, and compliance tracking.
type Policy struct {
	ID          uuid.UUID  `json:"id"`
	TenantID    uuid.UUID  `json:"tenant_id"`
	EntityID    *uuid.UUID `json:"entity_id"`
	Name        string     `json:"name"`
	DisplayName *string    `json:"display_name"`
	Description *string    `json:"description"`
	// Policy type: ABAC (attribute-based), RBAC (role-based), HYBRID (combined), TIME_BASED (temporal), LOCATION_BASED (geographic)
	PolicyType *string `json:"policy_type"`
	Effect     *string `json:"effect"`
	// Policy priority for conflict resolution (higher numbers processed first)
	Priority *int32 `json:"priority"`
	// Policy category: ACCESS (authorization), DATA_FILTER (row-level), FIELD_MASK (column-level), AUDIT (logging), COMPLIANCE (regulatory)
	Category *string `json:"category"`
	// JSONB defining when policy applies (subjects, resources, actions, conditions)
	Target []byte `json:"target"`
	// JSONB containing policy evaluation logic and conditions
	Rule []byte `json:"rule"`
	// JSONB defining required actions when policy fires (logging, notifications, etc.)
	Obligations []byte `json:"obligations"`
	// JSONB defining optional actions and recommendations
	Advice    []byte       `json:"advice"`
	IsActive  *bool        `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	CreatedBy *uuid.UUID   `json:"created_by"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

// Stores individual policy decisions made during a policy evaluation.
type PolicyDecision struct {
	ID                 uuid.UUID `json:"id"`
	PolicyEvaluationID uuid.UUID `json:"policy_evaluation_id"`
	PolicyID           uuid.UUID `json:"policy_id"`
	Decision           string    `json:"decision"`
	Reason             *string   `json:"reason"`
	MatchedRule        *string   `json:"matched_rule"`
	EvaluationMs       *int64    `json:"evaluation_ms"`
	TargetMatched      *bool     `json:"target_matched"`
	CreatedAt          time.Time `json:"created_at"`
}

// Caches ABAC policy evaluation results with flexible resource types and detailed decision tracking for performance optimization.
type PolicyEvaluation struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	// Type of resource being accessed (user, document, report, system, etc.)
	ResourceType string `json:"resource_type"`
	// Optional specific resource identifier
	ResourceID *uuid.UUID `json:"resource_id"`
	// Action being performed (read, write, delete, execute, etc.)
	Action   string     `json:"action"`
	EntityID *uuid.UUID `json:"entity_id"`
	// SHA-256 hash of evaluation context for cache key uniqueness
	ContextHash string `json:"context_hash"`
	Decision    string `json:"decision"`
	// Array of policy UUIDs that were evaluated and contributed to the decision
	ApplicablePolicies []uuid.UUID `json:"applicable_policies"`
	// JSONB array containing detailed policy decision information
	PolicyDecisions []byte `json:"policy_decisions"`
	// Policy evaluation time in milliseconds for performance monitoring
	EvaluationTimeMs *int32       `json:"evaluation_time_ms"`
	CacheKey         *string      `json:"cache_key"`
	EvaluatedAt      sql.NullTime `json:"evaluated_at"`
	ExpiresAt        sql.NullTime `json:"expires_at"`
}

// Subdomains tenants may not register. Enforcement is via trigger on the tenants table (migration 000057). Ops can add rows here without a schema migration.
type ReservedSubdomain struct {
	// DNS label — lowercase alphanumeric plus hyphens, max 63 chars.
	Subdomain string `json:"subdomain"`
	// Why this subdomain is reserved — required for audit clarity.
	Reason string `json:"reason"`
	// When this reservation was added.
	CreatedAt time.Time `json:"created_at"`
}

// System resources that can be protected by permissions including APIs, UI components, data objects, files, reports, and workflows.
type Resource struct {
	ID       uuid.UUID `json:"id"`
	ModuleID uuid.UUID `json:"module_id"`
	// Machine-readable key segment within its module. Forms the second segment of dot-notation keys: {module.slug}.{slug}. e.g. 'transactions', 'accounts'. Unique per module. Do not change after seeding.
	Slug        string  `json:"slug"`
	Name        string  `json:"name"`
	DisplayName *string `json:"display_name"`
	Description *string `json:"description"`
	Icon        *string `json:"icon"`
	// Browser navigation URL. e.g. '/finance/transactions'. Used by BootService to build sidebar links.
	NavUrl *string `json:"nav_url"`
	// Display order within the module section. Lower = higher. Default 999.
	NavOrder int32 `json:"nav_order"`
	// Type of resource: API, UI, DATA, FILE, REPORT, WORKFLOW, FUNCTION
	ResourceType string `json:"resource_type"`
	// Self-referential for resource hierarchy (e.g., API endpoints under API group)
	ParentResourceID *uuid.UUID `json:"parent_resource_id"`
	// Resource path convention: use dot-notation for logical resources (e.g. finance.invoice.create) and slash-notation for HTTP endpoints (e.g. /api/v1/invoices). Be consistent within a module. Consuming services must agree on the convention they parse.
	Path *string `json:"path"`
	// JSONB containing ABAC attributes like classification level, sensitivity, department ownership
	ResourceAttributes []byte       `json:"resource_attributes"`
	IsActive           *bool        `json:"is_active"`
	CreatedAt          sql.NullTime `json:"created_at"`
	// Updated by trigger on every row change — use for cache invalidation.
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

// Roles with module association, entity scoping, and hierarchical structure. Supports both RBAC and ABAC with conditional access rules.
type Role struct {
	ID          uuid.UUID  `json:"id"`
	TenantID    uuid.UUID  `json:"tenant_id"`
	EntityID    uuid.UUID  `json:"entity_id"`
	Name        string     `json:"name"`
	DisplayName *string    `json:"display_name"`
	Description *string    `json:"description"`
	ModuleID    *uuid.UUID `json:"module_id"`
	// Role classification: SYSTEM (built-in), TENANT (tenant-wide), ENTITY (entity-scoped), CUSTOM (user-defined), FUNCTIONAL (job-based)
	RoleType *string `json:"role_type"`
	// Parent role for inheritance hierarchy
	ParentRoleID *uuid.UUID `json:"parent_role_id"`
	// Calculated hierarchy level (0=root, higher=deeper)
	Level *int32 `json:"level"`
	// Cached permissions JSONB for performance optimization
	Permissions []byte `json:"permissions"`
	// JSONB defining which entities this role can access
	EntityScope []byte `json:"entity_scope"`
	// JSONB containing time, location, device, and other conditional access rules
	Conditions   []byte       `json:"conditions"`
	IsSystemRole *bool        `json:"is_system_role"`
	IsActive     *bool        `json:"is_active"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

// Role assignment metadata: who holds which role in which domain, with expiry and revocation tracking. Paired with casbin_rule rows written atomically in AssignRole.
type RoleAssignment struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Subject  string    `json:"subject"`
	RoleName string    `json:"role_name"`
	// Denormalized role slug for display in audit logs and UI without a roles JOIN.
	RoleSlug   *string `json:"role_slug"`
	Domain     string  `json:"domain"`
	AssignedBy *string `json:"assigned_by"`
	// UUID FK to the user who granted this assignment. Used for delegation chain audit.
	GrantedBy   *uuid.UUID `json:"granted_by"`
	DelegatedBy *string    `json:"delegated_by"`
	// When the assignment lapses automatically. NULL = permanent. Lazy expiry — checked on first request after expiry.
	ExpiresAt sql.NullTime `json:"expires_at"`
	// Explicit revocation timestamp. Set alongside is_active=false. Distinguishes revocation from expiry.
	RevokedAt sql.NullTime `json:"revoked_at"`
	// Human-readable revocation reason. e.g. 'termination', 'role restructure'.
	RevokeReason *string      `json:"revoke_reason"`
	IsActive     *bool        `json:"is_active"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

// Maps permissions to roles with optional entity-specific scoping and additional conditions for flexible authorization.
type RolePermission struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	// Optional entity restriction - if specified, permission only applies within this entity
	EntityScope *uuid.UUID `json:"entity_scope"`
	// User who granted this permission assignment
	GrantedBy *uuid.UUID   `json:"granted_by"`
	GrantedAt sql.NullTime `json:"granted_at"`
	// Additional JSONB conditions beyond those in the permission itself
	Conditions []byte `json:"conditions"`
	IsActive   *bool  `json:"is_active"`
}

type SecurityNotification struct {
	ID               uuid.UUID    `json:"id"`
	TenantID         uuid.UUID    `json:"tenant_id"`
	UserID           *uuid.UUID   `json:"user_id"`
	NotificationType string       `json:"notification_type"`
	Title            string       `json:"title"`
	Message          string       `json:"message"`
	Metadata         []byte       `json:"metadata"`
	Acknowledged     *bool        `json:"acknowledged"`
	CreatedAt        sql.NullTime `json:"created_at"`
	ExpiresAt        sql.NullTime `json:"expires_at"`
}

// System-wide setting catalogue. No tenant_id — shared across all tenants. Developer-seeded (unlike feature_flag_definitions which are trigger-seeded). Tenant values in tenant_settings.
type SettingDefinition struct {
	ID         uuid.UUID  `json:"id"`
	ModuleID   *uuid.UUID `json:"module_id"`
	ResourceID *uuid.UUID `json:"resource_id"`
	ActionID   *uuid.UUID `json:"action_id"`
	// Dot-notation key: {module}.{resource?}.{name}. e.g. 'finance.transactions.approval_threshold'. Never free-form — always derived from module/resource slugs.
	SettingKey  string  `json:"setting_key"`
	Label       string  `json:"label"`
	Description *string `json:"description"`
	// Value type: bool | int | decimal | text | enum. Determines which typed session accessor to use.
	ValueType    string  `json:"value_type"`
	DefaultValue *string `json:"default_value"`
	// For enum type: [{value, label}] array. e.g. [{"value":"soft","label":"Warn only"},{"value":"hard","label":"Block"}]
	EnumOptions []byte  `json:"enum_options"`
	MinValue    *string `json:"min_value"`
	MaxValue    *string `json:"max_value"`
	// When true, only platform operators can change. Shown as read-only/disabled in tenant admin UI.
	IsSystem  bool      `json:"is_system"`
	CreatedAt time.Time `json:"created_at"`
}

// Per-tenant OAuth/OIDC SSO provider configurations. client_secret_enc is AES-256-GCM encrypted. extra_params holds provider-specific config (e.g. Azure AD tenant for Microsoft). auto_provision=true enables just-in-time user creation on first SSO login.
type SsoProvider struct {
	ID              uuid.UUID  `json:"id"`
	TenantID        uuid.UUID  `json:"tenant_id"`
	Provider        string     `json:"provider"`
	ClientID        string     `json:"client_id"`
	ClientSecretEnc string     `json:"client_secret_enc"`
	Scopes          []string   `json:"scopes"`
	RedirectUri     string     `json:"redirect_uri"`
	ExtraParams     []byte     `json:"extra_params"`
	AutoProvision   bool       `json:"auto_provision"`
	DefaultEntityID *uuid.UUID `json:"default_entity_id"`
	IsActive        bool       `json:"is_active"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

// History of template applications with detailed results and statistics
type TemplateApplication struct {
	// UUID primary key for the template application record
	ID uuid.UUID `json:"id"`
	// Foreign key to configuration_templates table
	TemplateID uuid.UUID `json:"template_id"`
	// Foreign key to tenants table
	TenantID uuid.UUID `json:"tenant_id"`
	// Optional foreign key to entities table for entity-level applications
	EntityID *uuid.UUID `json:"entity_id"`
	// Target type: tenant or entity
	TargetType string `json:"target_type"`
	// Number of configurations successfully applied
	AppliedConfigs int32 `json:"applied_configs"`
	// Number of configurations skipped due to conflicts or policies
	SkippedConfigs int32 `json:"skipped_configs"`
	// Number of configuration conflicts encountered
	ConflictCount int32 `json:"conflict_count"`
	// Detailed JSON summary of the application results
	ApplicationSummary []byte    `json:"application_summary"`
	AppliedAt          time.Time `json:"applied_at"`
	// UUID of user who applied the template
	AppliedBy uuid.UUID `json:"applied_by"`
	// Correlation ID for tracking related operations
	CorrelationID *string `json:"correlation_id"`
}

// Core tenant registry for the multi-tenant ERP. One row per customer organisation. The Settings module reads/writes the settings JSONB column via its ConfigurationService — other services must not write directly to it. Soft-delete only: set deleted_at + deleted_by; never hard-DELETE.
type Tenant struct {
	// Immutable UUID — used in all external API references and foreign keys.
	ID uuid.UUID `json:"id"`
	// URL-safe identifier. Auto-generated from name on INSERT. IMMUTABLE after creation (trigger-enforced in migration 000057).
	Slug string `json:"slug"`
	// Human-readable display name. Must be globally unique.
	Name string `json:"name"`
	// Primary account email — used for auth and account notifications.
	Email string `json:"email"`
	// Billing contact email — receives invoices and payment alerts. Falls back to email when NULL.
	BillingEmail *string `json:"billing_email"`
	// Billing contact name printed on invoices. Optional.
	BillingContactName *string `json:"billing_contact_name"`
	// Vanity subdomain for tenant routing. NULL = use path-based routing. Reserved names blocked by trigger (000057).
	Subdomain *string `json:"subdomain"`
	// Lifecycle state. New tenants start PENDING until email verification + payment setup complete.
	Status string `json:"Status"`
	// Denormalized subscription tier for FeatureFlag and Settings services. Billing module is source of truth; writes back here via event.
	PlanTier string `json:"plan_tier"`
	// Last meaningful interaction (login, API call, row change). Updated by trigger unless application already set it in this transaction.
	LastActivityAt time.Time `json:"last_activity_at"`
	// IANA timezone string (e.g. America/New_York). Used for date-relative operations in the ERP.
	Timezone string `json:"timezone"`
	// ISO 4217 three-letter currency code. Default is USD.
	CurrencyCode string `json:"currency_code"`
	// Integration metadata owned by ops/third-party systems: Stripe IDs, webhook URLs, external system refs. NOT managed by Settings module.
	Metadata []byte `json:"metadata"`
	// Application-owned config managed exclusively by the Settings module (ConfigurationService). Other services must use GetEffectiveConfiguration() — do not write here directly.
	Settings []byte `json:"settings"`
	// Industry vertical for analytics and template selection (e.g. Manufacturing, Retail, Services).
	Industry *string `json:"industry"`
	// Approximate headcount band. Used for template selection and capacity planning.
	CompanySize *string `json:"company_size"`
	// Government tax identifier (VAT, EIN, GST etc.). Migrate to Compliance module when built.
	TaxID *string `json:"tax_id"`
	// Company registry number. Migrate to Compliance module when built.
	RegistrationNumber *string `json:"registration_number"`
	// Legal structure (LLC, Ltd, PLC, GmbH etc.). Migrate to Compliance module when built.
	LegalEntityType *string `json:"legal_entity_type"`
	// Self-reference for enterprise org trees and reseller chains. NULL = root tenant. Max depth 5 (DB-enforced), 3 recommended (UI). Circular refs blocked by trigger (000057).
	ParentTenantID *uuid.UUID `json:"parent_tenant_id"`
	// UUID of the actor (user or service account) that created this tenant. NULL if seeded by migration.
	CreatedBy *uuid.UUID `json:"created_by"`
	// UUID of the actor that issued the soft-delete. Set alongside deleted_at. NULL when not deleted.
	DeletedBy *uuid.UUID `json:"deleted_by"`
	// Row creation timestamp.
	CreatedAt time.Time `json:"created_at"`
	// Last row modification timestamp. Maintained by trigger (migration 000057).
	UpdatedAt time.Time `json:"updated_at"`
	// Soft-delete timestamp. NULL = tenant is active. Never hard-DELETE a tenant row.
	DeletedAt sql.NullTime `json:"deleted_at"`
}

// Master table tracking bulk tenant management operations with progress monitoring and audit trail.
type TenantBulkOperation struct {
	ID uuid.UUID `json:"id"`
	// Type of bulk operation: SUSPEND, REACTIVATE, ARCHIVE, UPDATE_LIMITS, UPDATE_FEATURES.
	OperationType string `json:"operation_type"`
	// UUID of the administrator who initiated the bulk operation.
	ActorID         uuid.UUID    `json:"actor_id"`
	ActorName       *string      `json:"actor_name"`
	TotalTenants    int32        `json:"total_tenants"`
	SuccessfulCount int32        `json:"successful_count"`
	FailedCount     int32        `json:"failed_count"`
	Status          string       `json:"status"`
	StartedAt       time.Time    `json:"started_at"`
	CompletedAt     sql.NullTime `json:"completed_at"`
	// JSON parameters specific to operation type (reason, limits, features, retention policies, etc.).
	Parameters []byte `json:"parameters"`
	// High-level summary of errors if the operation had failures.
	ErrorSummary *string   `json:"error_summary"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// Individual operation results for each tenant within a bulk operation.
type TenantBulkOperationResult struct {
	OperationID uuid.UUID `json:"operation_id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	// Individual tenant operation status: PENDING, PROCESSING, COMPLETED, FAILED, SKIPPED.
	Status string `json:"status"`
	// Success message or additional context for this tenant operation.
	Message *string `json:"message"`
	// Detailed error information specific to this tenant if the operation failed.
	ErrorDetails *string      `json:"error_details"`
	StartedAt    sql.NullTime `json:"started_at"`
	CompletedAt  sql.NullTime `json:"completed_at"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

// Tenant-specific configuration settings, feature flags, and resource limits
type TenantConfiguration struct {
	TenantID                uuid.UUID `json:"tenant_id"`
	MaxUsers                int32     `json:"max_users"`
	MaxEntities             int32     `json:"max_entities"`
	MaxTransactionsPerMonth int32     `json:"max_transactions_per_month"`
	StorageQuota            int64     `json:"storage_quota"`
	AccountingMethod        string    `json:"accounting_method"`
	FiscalYearStartMonth    int32     `json:"fiscal_year_start_month"`
	DefaultCurrency         string    `json:"default_currency"`
	DateFormat              string    `json:"date_format"`
	NumberFormat            string    `json:"number_format"`
	LanguageCode            string    `json:"language_code"`
	// Password complexity requirements
	PasswordPolicy   []byte `json:"password_policy"`
	Settings         []byte `json:"settings"`
	WebhookEndpoints []byte `json:"webhook_endpoints"`
	// API rate limiting configuration
	ApiRateLimits []byte    `json:"api_rate_limits"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	// Version counter for optimistic locking of tenant settings
	SettingsVersion *int32 `json:"settings_version"`
	// Reference to last template applied to this tenant
	LastTemplateApplied *uuid.UUID `json:"last_template_applied"`
	// Timestamp when template was last applied
	TemplateAppliedAt sql.NullTime `json:"template_applied_at"`
}

// Per-tenant feature flag overrides. Rows exist only for flags explicitly configured. Missing rows resolve to feature_flag_definitions.default_value.
type TenantFeatureFlag struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	FlagID   uuid.UUID `json:"flag_id"`
	// Denormalized flag_key from feature_flag_definitions for fast single-table lookups.
	FlagKey string `json:"flag_key"`
	Enabled bool   `json:"enabled"`
	// User who last set this override. NULL if set by system/migration.
	SetBy *uuid.UUID `json:"set_by"`
	SetAt time.Time  `json:"set_at"`
}

// Tenant-specific feature flag overrides with audit trail
type TenantFeatureOverride struct {
	ID            uuid.UUID  `json:"id"`
	TenantID      uuid.UUID  `json:"tenant_id"`
	EntityID      *uuid.UUID `json:"entity_id"`
	FeatureFlagID uuid.UUID  `json:"feature_flag_id"`
	// Denormalized feature flag name for faster lookups
	FeatureFlagName string `json:"feature_flag_name"`
	Enabled         bool   `json:"enabled"`
	// Complex feature values for non-boolean flags (JSON format)
	Value []byte `json:"value"`
	// Business justification for the override
	Reason    *string   `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Per-tenant setting values. Rows exist only for explicitly configured settings. Missing rows resolve to setting_definitions.default_value.
type TenantSetting struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	SettingID uuid.UUID `json:"setting_id"`
	// Denormalized from setting_definitions for fast single-table lookups in SettingService.
	SettingKey string `json:"setting_key"`
	// Stored as text. Parsed by typed session helpers: SettingBool/Int/Decimal/String.
	Value string     `json:"value"`
	SetBy *uuid.UUID `json:"set_by"`
	SetAt time.Time  `json:"set_at"`
}

// Tracks tenant resource usage and performance metrics over time
type TenantUsageStat struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	PeriodStart       time.Time `json:"period_start"`
	PeriodEnd         time.Time `json:"period_end"`
	ActiveUsers       int32     `json:"active_users"`
	TotalEntities     int32     `json:"total_entities"`
	TotalTransactions int32     `json:"total_transactions"`
	// Storage used in bytes
	StorageUsed int64 `json:"storage_used"`
	ApiCalls    int32 `json:"api_calls"`
	// Average response time in milliseconds
	AvgResponseTime pgtype.Numeric `json:"avg_response_time"`
	// Error rate as decimal (0.0001 = 0.01%)
	ErrorRate      pgtype.Numeric `json:"error_rate"`
	MonthlyRevenue pgtype.Numeric `json:"monthly_revenue"`
	CreatedAt      time.Time      `json:"created_at"`
}

// System user accounts with authentication, authorization, and session management. Can be linked to persons/employees or exist independently for service accounts.
type User struct {
	// UUID primary key for the user record.
	ID uuid.UUID `json:"id"`
	// Foreign key to tenants table for multi-tenant isolation.
	TenantID uuid.UUID `json:"tenant_id"`
	// Foreign key to entities table for organizational assignment.
	EntityID uuid.UUID `json:"entity_id"`
	// Optional foreign key to persons table (NULL for service accounts).
	PersonID *uuid.UUID `json:"person_id"`
	// Optional foreign key to employees table (NULL for non-employee users).
	EmployeeID *uuid.UUID `json:"employee_id"`
	// Email address for login and communication (must be unique per tenant).
	Email string `json:"email"`
	// Unique username for login (optional, email can be used instead).
	Username string `json:"username"`
	// Human-readable name shown in UI and stored in ResolvedSession.DisplayName at login. Falls back to username if not set.
	DisplayName *string `json:"display_name"`
	// For portal users (CUSTOMER/VENDOR/PARTNER): UUID of the business record they represent. Always read from session — never from request params. NULL for INTERNAL/SYSADMIN accounts.
	PrincipalID *uuid.UUID `json:"principal_id"`
	// Hashed password for authentication.
	PasswordHash *string `json:"password_hash"`
	// Classification of user account: INTERNAL, CUSTOMER, VENDOR, PARTNER, API, SERVICE, SYSADMIN.
	UserType string `json:"user_type"`
	// Current account status affecting login ability.
	AccountStatus *string `json:"account_status"`
	// Whether the user account is currently active.
	IsActive bool `json:"is_active"`
	// Timestamp of last successful login.
	LastLoginAt sql.NullTime `json:"last_login_at"`
	// Timestamp of last password change.
	PasswordChangedAt sql.NullTime `json:"password_changed_at"`
	// Counter for failed login attempts for security monitoring.
	FailedLoginAttempts *int32 `json:"failed_login_attempts"`
	// Timestamp until which account is locked due to failed attempts.
	LockoutUntil sql.NullTime `json:"lockout_until"`
	// Session timeout in minutes (default 480 = 8 hours).
	SessionTimeoutMinutes *int32 `json:"session_timeout_minutes"`
	// Whether multi-factor authentication is enabled.
	MfaEnabled *bool `json:"mfa_enabled"`
	// Secret key for MFA token generation.
	MfaSecret *string `json:"mfa_secret"`
	// JSONB containing ABAC attributes for fine-grained access control.
	UserAttributes []byte `json:"user_attributes"`
	// JSONB containing user preferences and application settings.
	Settings []byte `json:"settings"`
	// Password strength score (0-100) based on complexity.
	PasswordStrength *int32 `json:"password_strength"`
	// Flag if password found in breach databases.
	Compromised *bool `json:"compromised"`
	// Forces password change on next login.
	RotationRequired *bool     `json:"rotation_required"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	// Soft delete timestamp — NULL means record is active.
	DeletedAt sql.NullTime `json:"deleted_at"`
	// JSON array of the last 5 bcrypt hashes. Used to prevent password re-use. Capped at 5 entries.
	PasswordHistory []byte `json:"password_history"`
}

// Partitioned table for user activity tracking and behavioral analytics supporting ABAC evaluation
type UserActivity struct {
	// Unique identifier for the activity record
	ID uuid.UUID `json:"id"`
	// Reference to the user who performed the activity
	UserID uuid.UUID `json:"user_id"`
	// Tenant isolation for multi-tenant architecture
	TenantID uuid.UUID  `json:"tenant_id"`
	EntityID *uuid.UUID `json:"entity_id"`
	// Reference to the user session when activity occurred
	SessionID *uuid.UUID `json:"session_id"`
	// Classification of the activity (login, access, modification, etc.)
	ActivityType      string      `json:"activity_type"`
	Module            *string     `json:"module"`
	ResourceType      *string     `json:"resource_type"`
	ResourceID        *uuid.UUID  `json:"resource_id"`
	ActionPerformed   *string     `json:"action_performed"`
	IpAddress         *netip.Addr `json:"ip_address"`
	UserAgent         *string     `json:"user_agent"`
	DeviceFingerprint *string     `json:"device_fingerprint"`
	// JSONB containing geographic and network location information
	LocationData   []byte  `json:"location_data"`
	RequestMethod  *string `json:"request_method"`
	RequestPath    *string `json:"request_path"`
	RequestParams  []byte  `json:"request_params"`
	ResponseStatus *int32  `json:"response_status"`
	ResponseTimeMs *int32  `json:"response_time_ms"`
	// JSONB containing calculated risk factors for the activity
	RiskIndicators []byte `json:"risk_indicators"`
	// Calculated anomaly score from 0.00 to 100.00 for behavioral analysis
	AnomalyScore pgtype.Numeric `json:"anomaly_score"`
	Timestamp    time.Time      `json:"timestamp"`
	// Flexible JSONB storage for activity-specific metadata
	AdditionalData []byte `json:"additional_data"`
}

// Direct permission grants to users bypassing roles. Used for exceptional access, denials, and temporary permissions.
type UserPermission struct {
	ID           uuid.UUID  `json:"id"`
	TenantID     uuid.UUID  `json:"tenant_id"`
	UserID       uuid.UUID  `json:"user_id"`
	PermissionID uuid.UUID  `json:"permission_id"`
	EntityID     *uuid.UUID `json:"entity_id"`
	// Permission effect: ALLOW (grant access) or DENY (explicitly deny - overrides role permissions)
	Effect *string `json:"effect"`
	// Business justification for this direct permission assignment
	Reason *string `json:"reason"`
	// User who granted this direct permission
	GrantedBy  *uuid.UUID   `json:"granted_by"`
	GrantedAt  sql.NullTime `json:"granted_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	Conditions []byte       `json:"conditions"`
	IsActive   *bool        `json:"is_active"`
}

// Per-user UI/display preferences. Stored in session configuration.prefs at login. Not business logic.
type UserPreference struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	// Preference key namespaced by module. e.g. 'finance.entry_mode', 'finance.show_account_codes'.
	PrefKey string    `json:"pref_key"`
	Value   string    `json:"value"`
	SetAt   time.Time `json:"set_at"`
}

// Assigns roles to users with entity context, delegation support, and temporal controls for dynamic authorization.
type UserRole struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	RoleID   uuid.UUID `json:"role_id"`
	EntityID uuid.UUID `json:"entity_id"`
	// Type of assignment: DIRECT (explicitly assigned), INHERITED (from hierarchy), DELEGATED (from another user), TEMPORARY (time-limited)
	AssignmentType *string `json:"assignment_type"`
	// User who delegated this role assignment (for DELEGATED type)
	DelegatedBy *uuid.UUID `json:"delegated_by"`
	AssignedAt  time.Time  `json:"assigned_at"`
	AssignedBy  *uuid.UUID `json:"assigned_by"`
	// Expiration timestamp for temporary role assignments
	ExpiresAt sql.NullTime `json:"expires_at"`
	// JSONB containing conditional access rules (time, location, device, etc.)
	Conditions []byte `json:"conditions"`
	IsActive   *bool  `json:"is_active"`
}

// Active user sessions with security context including device, location, and access patterns for ABAC evaluation and security monitoring.
type UserSession struct {
	// UUID primary key for the session record
	ID uuid.UUID `json:"id"`
	// Foreign key to tenants table for multi-tenant isolation
	TenantID uuid.UUID `json:"tenant_id"`
	// Foreign key to users table identifying the session owner
	UserID uuid.UUID `json:"user_id"`
	// Unique session token for authentication
	SessionToken string `json:"session_token"`
	// Token used for session renewal
	RefreshToken *string `json:"refresh_token"`
	// IP address of the client
	IpAddress *netip.Addr `json:"ip_address"`
	// Browser/client user agent string
	UserAgent *string `json:"user_agent"`
	// JSONB containing device fingerprinting data for security analysis
	DeviceInfo []byte `json:"device_info"`
	// JSONB containing geographic and network location data for location-based access control
	LocationInfo []byte `json:"location_info"`
	// Session expiration timestamp
	ExpiresAt time.Time `json:"expires_at"`
	// Calculated risk score (0-100) based on action, context, and user behavior
	RiskScore *int32 `json:"risk_score"`
	// Copied from users.user_type at login. Used by SetDBPool middleware to select the right connection pool without a DB roundtrip.
	UserType *string `json:"user_type"`
	// Pre-computed session config: {"flags":{"finance":true,...},"settings":{"finance.approval_threshold":"100000",...},"prefs":{"finance.entry_mode":"spreadsheet",...}}. Built at login from 5 concurrent queries. Read-only — refresh requires re-login.
	Configuration []byte `json:"configuration"`
	// Pre-computed entity access scope: {"type":"all"|"subtree"|"entity","entity_id":"uuid","path_prefix":"/root/parent/"}. Built at login. Used by repos for subtree WHERE clauses without extra joins.
	EntityScope []byte `json:"entity_scope"`
	// Session creation timestamp
	CreatedAt sql.NullTime `json:"created_at"`
	// Last activity timestamp for session timeout tracking
	LastAccessedAt sql.NullTime `json:"last_accessed_at"`
	// Whether the session is currently active
	IsActive *bool `json:"is_active"`
	// Pre-computed permission map {"finance.invoices.read": true, ...} stored at login; used for O(1) authz on every request.
	Permissions []byte `json:"permissions"`
	// For portal users: the contact/employee UUID they act as. NULL for platform and tenant users.
	PrincipalID *uuid.UUID `json:"principal_id"`
}

type VActiveEntity struct {
	TenantName     string    `json:"tenant_name"`
	EntityID       uuid.UUID `json:"entity_id"`
	EntityName     string    `json:"entity_name"`
	EntityType     string    `json:"entity_type"`
	EntityCode     *string   `json:"entity_code"`
	CompanyName    *string   `json:"company_name"`
	RegionalName   *string   `json:"regional_name"`
	DepartmentName *string   `json:"department_name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// Hourly audit event summary for the last 7 days with risk metrics and access decision counts for security monitoring dashboards.
type VAuditSummaryView struct {
	TenantID        uuid.UUID       `json:"tenant_id"`
	EventCategory   *string         `json:"event_category"`
	Severity        *string         `json:"severity"`
	HourBucket      pgtype.Interval `json:"hour_bucket"`
	EventCount      int64           `json:"event_count"`
	UniqueUsers     int64           `json:"unique_users"`
	AvgRiskScore    float64         `json:"avg_risk_score"`
	MaxRiskScore    interface{}     `json:"max_risk_score"`
	DeniedAttempts  int64           `json:"denied_attempts"`
	AllowedAttempts int64           `json:"allowed_attempts"`
}

// Complete chart of accounts with full group and header hierarchy for reporting
type VChartOfAccountsComplete struct {
	AccountID                 uuid.UUID      `json:"account_id"`
	TenantID                  uuid.UUID      `json:"tenant_id"`
	AccountCode               string         `json:"account_code"`
	AccountName               string         `json:"account_name"`
	AccountDescription        *string        `json:"account_description"`
	RootType                  string         `json:"root_type"`
	AccountType               string         `json:"account_type"`
	AccountSubtype            *string        `json:"account_subtype"`
	AccountCategory           *string        `json:"account_category"`
	NormalBalance             string         `json:"normal_balance"`
	CurrentBalance            pgtype.Numeric `json:"current_balance"`
	IsActive                  bool           `json:"is_active"`
	IsLeafAccount             bool           `json:"is_leaf_account"`
	ParentAccountID           *uuid.UUID     `json:"parent_account_id"`
	AccountLevel              int32          `json:"account_level"`
	AccountPath               *string        `json:"account_path"`
	GroupID                   *uuid.UUID     `json:"group_id"`
	GroupCode                 *string        `json:"group_code"`
	GroupName                 *string        `json:"group_name"`
	GroupCategory             *string        `json:"group_category"`
	GroupPath                 *string        `json:"group_path"`
	HeaderID                  *uuid.UUID     `json:"header_id"`
	HeaderCode                *string        `json:"header_code"`
	HeaderName                *string        `json:"header_name"`
	FinancialStatementSection *string        `json:"financial_statement_section"`
	HeaderOrder               *int32         `json:"header_order"`
	DisplayOrder              int32          `json:"display_order"`
	StatementSection          *string        `json:"statement_section"`
	CashFlowClassification    *string        `json:"cash_flow_classification"`
	IncludeInReports          *bool          `json:"include_in_reports"`
}

type VCompanyStructure struct {
	TenantName        string    `json:"tenant_name"`
	CompanyID         uuid.UUID `json:"company_id"`
	CompanyName       string    `json:"company_name"`
	CompanyCode       *string   `json:"company_code"`
	EntityID          uuid.UUID `json:"entity_id"`
	EntityName        string    `json:"entity_name"`
	EntityType        string    `json:"entity_type"`
	EntityCode        *string   `json:"entity_code"`
	LevelsFromCompany int32     `json:"levels_from_company"`
}

type VCostCenterInfo struct {
	TenantName        string    `json:"tenant_name"`
	CostCenterID      uuid.UUID `json:"cost_center_id"`
	CostCenter        string    `json:"cost_center"`
	CostCenterCode    *string   `json:"cost_center_code"`
	DepartmentID      uuid.UUID `json:"department_id"`
	Department        string    `json:"department"`
	RegionalID        uuid.UUID `json:"regional_id"`
	Regional          string    `json:"regional"`
	CompanyID         uuid.UUID `json:"company_id"`
	Company           string    `json:"company"`
	CostCenterActive  bool      `json:"cost_center_active"`
	CostCenterCreated time.Time `json:"cost_center_created"`
}

type VDepartmentSummary struct {
	TenantName        string    `json:"tenant_name"`
	DepartmentID      uuid.UUID `json:"department_id"`
	DepartmentName    string    `json:"department_name"`
	DepartmentCode    *string   `json:"department_code"`
	RegionalID        uuid.UUID `json:"regional_id"`
	RegionalName      string    `json:"regional_name"`
	CompanyID         uuid.UUID `json:"company_id"`
	CompanyName       string    `json:"company_name"`
	CostCenterCount   int64     `json:"cost_center_count"`
	DepartmentActive  bool      `json:"department_active"`
	DepartmentCreated time.Time `json:"department_created"`
}

type VEntityChange struct {
	TenantName       string       `json:"tenant_name"`
	EntityID         uuid.UUID    `json:"entity_id"`
	EntityName       string       `json:"entity_name"`
	EntityType       string       `json:"entity_type"`
	ValidationStatus *string      `json:"validation_status"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
	ChangeType       string       `json:"change_type"`
}

type VEntityPath struct {
	TenantName     string    `json:"tenant_name"`
	AncestorID     uuid.UUID `json:"ancestor_id"`
	AncestorName   string    `json:"ancestor_name"`
	AncestorType   string    `json:"ancestor_type"`
	DescendantID   uuid.UUID `json:"descendant_id"`
	DescendantName string    `json:"descendant_name"`
	DescendantType string    `json:"descendant_type"`
	Depth          int32     `json:"depth"`
}

type VEntityStructure struct {
	TenantName   string    `json:"tenant_name"`
	CostCenterID uuid.UUID `json:"cost_center_id"`
	CostCenter   string    `json:"cost_center"`
	DepartmentID uuid.UUID `json:"department_id"`
	Department   string    `json:"department"`
	RegionalID   uuid.UUID `json:"regional_id"`
	Regional     string    `json:"regional"`
	CompanyID    uuid.UUID `json:"company_id"`
	Company      string    `json:"company"`
}

// Account activity summary for monitoring and analysis
type VFinanceAccountActivity struct {
	TenantID            uuid.UUID      `json:"tenant_id"`
	AccountID           uuid.UUID      `json:"account_id"`
	AccountCode         string         `json:"account_code"`
	AccountName         string         `json:"account_name"`
	CurrentBalance      pgtype.Numeric `json:"current_balance"`
	LastTransactionDate time.Time      `json:"last_transaction_date"`
	TotalEntries        int64          `json:"total_entries"`
	EntriesLast30Days   int64          `json:"entries_last_30_days"`
	DebitsLast30Days    int64          `json:"debits_last_30_days"`
	CreditsLast30Days   int64          `json:"credits_last_30_days"`
}

// Hierarchical view of chart of accounts with computed paths and levels
type VFinanceAccountsHierarchy struct {
	ID              uuid.UUID      `json:"id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	AccountCode     string         `json:"account_code"`
	AccountName     string         `json:"account_name"`
	ParentAccountID *uuid.UUID     `json:"parent_account_id"`
	RootType        string         `json:"root_type"`
	AccountType     string         `json:"account_type"`
	NormalBalance   string         `json:"normal_balance"`
	CurrentBalance  pgtype.Numeric `json:"current_balance"`
	Level           int32          `json:"level"`
	FullPath        string         `json:"full_path"`
	FullName        string         `json:"full_name"`
	ChildCount      int64          `json:"child_count"`
}

// Complete account view with group and header information for reporting
type VFinanceAccountsWithGroup struct {
	ID                        uuid.UUID      `json:"id"`
	TenantID                  uuid.UUID      `json:"tenant_id"`
	AccountCode               string         `json:"account_code"`
	AccountName               string         `json:"account_name"`
	AccountDescription        *string        `json:"account_description"`
	RootType                  string         `json:"root_type"`
	AccountType               string         `json:"account_type"`
	AccountCategory           *string        `json:"account_category"`
	NormalBalance             string         `json:"normal_balance"`
	CurrentBalance            pgtype.Numeric `json:"current_balance"`
	IsActive                  bool           `json:"is_active"`
	GroupCode                 *string        `json:"group_code"`
	GroupName                 *string        `json:"group_name"`
	GroupCategory             *string        `json:"group_category"`
	HeaderCode                *string        `json:"header_code"`
	HeaderName                *string        `json:"header_name"`
	FinancialStatementSection *string        `json:"financial_statement_section"`
	ParentAccountID           *uuid.UUID     `json:"parent_account_id"`
	AccountLevel              int32          `json:"account_level"`
	HasChildren               bool           `json:"has_children"`
	IsLeafAccount             bool           `json:"is_leaf_account"`
	EffectiveDisplayOrder     int32          `json:"effective_display_order"`
	CashFlowType              *string        `json:"cash_flow_type"`
	ShowInReports             *bool          `json:"show_in_reports"`
}

// Summary view of transactions with entry counts and reconciliation status
type VFinanceTransactionSummary struct {
	ID                   uuid.UUID      `json:"id"`
	TenantID             uuid.UUID      `json:"tenant_id"`
	TransactionNumber    string         `json:"transaction_number"`
	TransactionDate      time.Time      `json:"transaction_date"`
	Description          string         `json:"description"`
	TransactionStatus    string         `json:"transaction_status"`
	CurrencyCode         string         `json:"currency_code"`
	TotalDebitAmount     pgtype.Numeric `json:"total_debit_amount"`
	TotalCreditAmount    pgtype.Numeric `json:"total_credit_amount"`
	EntryCount           int64          `json:"entry_count"`
	UniqueAccounts       int64          `json:"unique_accounts"`
	AllEntriesReconciled bool           `json:"all_entries_reconciled"`
	AccountCodes         []byte         `json:"account_codes"`
}

// Pre-aggregated data for building financial statements with grouping and totals
type VFinancialStatementBuilder struct {
	TenantID            uuid.UUID      `json:"tenant_id"`
	StatementSection    *string        `json:"statement_section"`
	HeaderCode          *string        `json:"header_code"`
	HeaderName          *string        `json:"header_name"`
	HeaderOrder         *int32         `json:"header_order"`
	GroupCode           *string        `json:"group_code"`
	GroupName           *string        `json:"group_name"`
	GroupCategory       *string        `json:"group_category"`
	AccountCount        int64          `json:"account_count"`
	GroupBalance        int64          `json:"group_balance"`
	ActiveBalance       int64          `json:"active_balance"`
	RunningTotal        int64          `json:"running_total"`
	PercentageOfSection pgtype.Numeric `json:"percentage_of_section"`
}

// Financial statement structure with account groups, hierarchies, and balances
type VFinancialStatementStructure struct {
	ID                        uuid.UUID   `json:"id"`
	TenantID                  uuid.UUID   `json:"tenant_id"`
	GroupCode                 string      `json:"group_code"`
	GroupName                 string      `json:"group_name"`
	RootType                  string      `json:"root_type"`
	FinancialStatementSection *string     `json:"financial_statement_section"`
	StatementOrder            *int32      `json:"statement_order"`
	GroupLevel                int32       `json:"group_level"`
	ParentGroupID             *uuid.UUID  `json:"parent_group_id"`
	ShowInSummary             *bool       `json:"show_in_summary"`
	GroupPath                 *string     `json:"group_path"`
	AccountCount              int64       `json:"account_count"`
	ActiveAccountCount        int64       `json:"active_account_count"`
	GroupBalance              interface{} `json:"group_balance"`
}

// Summary view of roles with their permissions, resources, actions, and user assignment counts for role management and analysis.
type VRolePermissionsSummary struct {
	TenantID          uuid.UUID   `json:"tenant_id"`
	RoleID            uuid.UUID   `json:"role_id"`
	RoleName          string      `json:"role_name"`
	RoleDisplayName   *string     `json:"role_display_name"`
	RoleType          *string     `json:"role_type"`
	HierarchyLevel    *int32      `json:"hierarchy_level"`
	ModuleID          *uuid.UUID  `json:"module_id"`
	ModuleName        *string     `json:"module_name"`
	ResourceNames     interface{} `json:"resource_names"`
	ActionNames       interface{} `json:"action_names"`
	PermissionCount   int64       `json:"permission_count"`
	AssignedUserCount int64       `json:"assigned_user_count"`
}

// Identifies potential security threats through session anomalies and audit patterns
type VSecurityThreatDashboard struct {
	UserID                 uuid.UUID   `json:"user_id"`
	Username               string      `json:"username"`
	Email                  string      `json:"email"`
	HighRiskSessions       int64       `json:"high_risk_sessions"`
	MaxRiskScore           interface{} `json:"max_risk_score"`
	CriticalEvents         int64       `json:"critical_events"`
	LastSuspiciousActivity interface{} `json:"last_suspicious_activity"`
}

type VTenantEntitySummary struct {
	TenantID           uuid.UUID `json:"tenant_id"`
	TenantName         string    `json:"tenant_name"`
	TenantStatus       string    `json:"tenant_status"`
	TotalEntities      int64     `json:"total_entities"`
	CompanyCount       int64     `json:"company_count"`
	RegionalCount      int64     `json:"regional_count"`
	DepartmentCount    int64     `json:"department_count"`
	CostCenterCount    int64     `json:"cost_center_count"`
	ProjectCount       int64     `json:"project_count"`
	ActiveEntities     int64     `json:"active_entities"`
	NonDeletedEntities int64     `json:"non_deleted_entities"`
}

type VTenantHierarchy struct {
	TenantName string    `json:"tenant_name"`
	EntityID   uuid.UUID `json:"entity_id"`
	EntityName string    `json:"entity_name"`
	EntityType string    `json:"entity_type"`
	FullPath   string    `json:"full_path"`
	Depth      int32     `json:"depth"`
}

type VTenantResourceUtilization struct {
	TenantID           uuid.UUID   `json:"tenant_id"`
	TenantName         string      `json:"tenant_name"`
	TenantStatus       string      `json:"tenant_status"`
	TotalEntities      int64       `json:"total_entities"`
	ActiveEntities     int64       `json:"active_entities"`
	NonDeletedEntities int64       `json:"non_deleted_entities"`
	SequenceStates     int64       `json:"sequence_states"`
	DocumentTypes      int64       `json:"document_types"`
	LastEntityCreated  interface{} `json:"last_entity_created"`
	LastEntityUpdated  interface{} `json:"last_entity_updated"`
}

// view combining user, person, and employee data with role aggregations and combined ABAC attributes for authorization decisions.
type VUserCompleteView struct {
	UserID             uuid.UUID    `json:"user_id"`
	TenantID           uuid.UUID    `json:"tenant_id"`
	EntityID           uuid.UUID    `json:"entity_id"`
	Username           string       `json:"username"`
	Email              string       `json:"email"`
	UserType           string       `json:"user_type"`
	AccountStatus      *string      `json:"account_status"`
	UserActive         bool         `json:"user_active"`
	LastLoginAt        sql.NullTime `json:"last_login_at"`
	MfaEnabled         *bool        `json:"mfa_enabled"`
	PersonID           *uuid.UUID   `json:"person_id"`
	FirstName          *string      `json:"first_name"`
	LastName           *string      `json:"last_name"`
	MiddleName         *string      `json:"middle_name"`
	PersonType         *string      `json:"person_type"`
	EmployeeID         *uuid.UUID   `json:"employee_id"`
	EmployeeNumber     *string      `json:"employee_number"`
	PositionTitle      *string      `json:"position_title"`
	DepartmentID       *uuid.UUID   `json:"department_id"`
	EmploymentStatus   *string      `json:"employment_status"`
	SecurityLevel      *int32       `json:"security_level"`
	CombinedAttributes interface{}  `json:"combined_attributes"`
	RoleNames          interface{}  `json:"role_names"`
	RoleIds            interface{}  `json:"role_ids"`
	ActiveRoleCount    int64        `json:"active_role_count"`
}
