DROP TABLE IF EXISTS iam_user_role CASCADE;
DROP TABLE IF EXISTS iam_api_token CASCADE;
DROP TABLE IF EXISTS iam_session CASCADE;
DROP TABLE IF EXISTS iam_role CASCADE;
DROP TABLE IF EXISTS iam_user CASCADE;
