-- -- Drop UOM Conversion table and dependencies
-- DROP INDEX IF EXISTS idx_uom_conversion_to;
-- DROP INDEX IF EXISTS idx_uom_conversion_from;
-- DROP INDEX IF EXISTS idx_uom_conversion_tenant_entity;
-- DROP TABLE IF EXISTS uom_conversion;
--
-- -- Drop UOM table and dependencies
-- DROP INDEX IF EXISTS idx_uom_base_uom_id;
-- DROP INDEX IF EXISTS idx_uom_tenant_entity_type;
-- DROP INDEX IF EXISTS idx_uom_enabled;
-- DROP INDEX IF EXISTS idx_uom_tenant_entity;
-- DROP TABLE IF EXISTS uom;
--
-- -- Drop Budgets table
-- DROP TABLE IF EXISTS budgets;
--
-- -- Drop Projects table and its unique index
-- DROP INDEX IF EXISTS tenant_code_entity_unique_idx;
-- DROP TABLE IF EXISTS projects;
