-- SUPERSEDED: roles, permissions, and role assignments are now seeded in 05_iam.sql
-- Security functions and RLS policies are handled by the migrations themselves.
-- This file is intentionally empty to preserve the old filename.
