// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: iam.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO iam_user_roles (user_id, role_id, tenant_id)
VALUES ($1, $2, current_tenant_id())
ON CONFLICT DO NOTHING
`

type AssignRoleParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	RoleID uuid.UUID `db:"role_id" json:"role_id"`
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignRole, arg.UserID, arg.RoleID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO iam_roles (id, tenant_id, name, description)
VALUES (gen_random_uuid(), current_tenant_id(), $1, $2)
RETURNING id, tenant_id, name, description, permissions, created_at, updated_at
`

type CreateRoleParams struct {
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (IamRole, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.Name, arg.Description)
	var i IamRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO iam_users (id, tenant_id, email, password_hash, status)
VALUES (gen_random_uuid(), current_tenant_id(), $1, $2, 'active')
RETURNING id, tenant_id, email, password_hash, status, metadata, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (IamUser, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, status, metadata, created_at, updated_at FROM iam_users
WHERE email = $1 AND tenant_id = current_tenant_id()
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (IamUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, status, metadata, created_at, updated_at FROM iam_users
WHERE id = $1 AND tenant_id = current_tenant_id()
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (IamUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, tenant_id, name, description, permissions, created_at, updated_at FROM iam_roles
WHERE tenant_id = current_tenant_id()
ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]IamRole, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IamRole
	for rows.Next() {
		var i IamRole
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.tenant_id, r.name, r.description, r.permissions, r.created_at, r.updated_at FROM iam_roles r
JOIN iam_user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1 AND ur.tenant_id = current_tenant_id()
`

func (q *Queries) ListUserRoles(ctx context.Context, userID uuid.UUID) ([]IamRole, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IamRole
	for rows.Next() {
		var i IamRole
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, password_hash, status, metadata, created_at, updated_at FROM iam_users
WHERE tenant_id = current_tenant_id()
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]IamUser, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IamUser
	for rows.Next() {
		var i IamUser
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRole = `-- name: RevokeRole :exec
DELETE FROM iam_user_roles
WHERE user_id = $1 AND role_id = $2 AND tenant_id = current_tenant_id()
`

type RevokeRoleParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	RoleID uuid.UUID `db:"role_id" json:"role_id"`
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.ExecContext(ctx, revokeRole, arg.UserID, arg.RoleID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE iam_users
SET status = $2, updated_at = NOW()
WHERE id = $1 AND tenant_id = current_tenant_id()
RETURNING id, tenant_id, email, password_hash, status, metadata, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (IamUser, error) {
	row := q.db.QueryRowContext(ctx, updateUserStatus, arg.ID, arg.Status)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
